Repository UNDP-Data/geohub, pull requests merged in 2022-12, with the labels that each got.

#875 fixed to use layer id from tags instead of name
  src/lib/VectorTileData.ts
Labels: bug

#877 Feature/add statistics tag api
  package.json
  pnpm-lock.yaml
  src/components/DataCategoryCardList.svelte
  src/components/DataView.svelte
  src/components/controls/Breadcrumbs.svelte
  src/routes/tags/+server.ts
Labels: enhancement

#878 removed hard coding to set header height
  src/components/Content.svelte
  src/components/ContentSidebar.svelte
  src/components/DataView.svelte
  src/components/Header.svelte
  src/components/LayerList.svelte
  src/components/Map.svelte
  src/components/StyleShare.svelte
  src/components/controls/Breadcrumbs.svelte
  src/components/controls/Tabs.svelte
  src/components/controls/TextFilter.svelte
  src/routes/+page.svelte
Labels: refactor

#879 added tag search feature
  package.json
  pnpm-lock.yaml
  src/components/DataCard.svelte
  src/components/DataView.svelte
  src/components/controls/TagFilter.svelte
  src/components/controls/TextFilter.svelte
  src/lib/constants.ts
  src/lib/types/Tag.ts
  src/routes/datasets/+server.ts
  src/routes/tags/+server.ts
Labels: enhancement, frontend

#880 added radios to select operator for tag search
  src/components/DataView.svelte
  src/components/controls/TagFilter.svelte
  src/components/controls/TextFilter.svelte
  src/routes/datasets/+server.ts
Labels: enhancement

#881 reverted sveltekit to 564
  package.json
  pnpm-lock.yaml
Labels: bug

#882 fixed clear filter text
  src/components/DataView.svelte
  src/components/controls/TextFilter.svelte
Labels: bug

#883 dynamic filter list of tags according to current search result
  src/components/DataView.svelte
  src/components/controls/TagFilter.svelte
  src/components/controls/TextFilter.svelte
  src/lib/helper/createDatasetSearchWhereExpression.ts
  src/lib/helper/index.ts
  src/routes/datasets/+server.ts
  src/routes/tags/+server.ts
Labels: enhancement

#884 Fix: don't refresh search result when filter panel is opened
  src/components/DataView.svelte
Labels: bug

#885 deleted smui/tooltip
  package.json
  pnpm-lock.yaml
  src/components/Header.svelte
  src/components/StyleShare.svelte
  src/components/controls/ActionsDropdown.svelte
  src/components/controls/DeleteButton.svelte
  src/components/controls/LayerOrderButtons.svelte
  src/components/controls/RasterBandSelector.svelte
  src/components/controls/RasterExpressionBuilder.svelte
  src/components/controls/RasterExpressionSimple.svelte
  src/components/controls/RasterLegendContainer.svelte
  src/components/controls/VectorLineContainer.svelte
  src/components/controls/VectorPolygonContainer.svelte
  src/components/controls/VectorSymbolContainer.svelte
  src/components/controls/VisibilityButton.svelte
  src/components/controls/vector-styles/IconIgnorePlacement.svelte
  src/dashboards/components/Charts.svelte
  src/dashboards/components/Content.svelte
  src/dashboards/components/DownloadData.svelte
  src/dashboards/components/ElectricityControl.svelte
  src/dashboards/components/IntroductionPanel.svelte
  src/dashboards/components/Map.svelte
  src/dashboards/components/OverlayControl.svelte
  src/lib/components/StyleSwitcher.svelte
  src/routes/+page.svelte
  src/routes/dashboards/electricity/+page.svelte
  src/routes/dashboards/electricity/+page.ts
  src/styles/theme/_smui-theme.scss
  src/styles/theme/dark/_smui-theme.scss
Labels: refactor

#886 redesigned filter buttons, and show loader in tag list
  src/components/controls/PanelButton.svelte
  src/components/controls/TagFilter.svelte
  src/components/controls/TextFilter.svelte
Labels: enhancement

#887 Fix/put cursor default
  src/components/controls/PanelButton.svelte
Labels: bug

#888 Fix/add prerender setting
  src/routes/+page.ts
  src/routes/dashboards/+page.ts
  src/routes/viewer/+page.ts
Labels: enhancement

#891 fixed tabs in colorMapPicker.svelte
  src/components/controls/ColorMapPicker.svelte
  src/components/controls/RasterLegendContainer.svelte
  src/components/controls/Tabs.svelte
  src/components/controls/VectorLineContainer.svelte
  src/components/controls/VectorPolygonContainer.svelte
  src/components/controls/VectorSymbolContainer.svelte
  src/lib/types/Tab.ts
Labels: bug

#893 exclude microsoft stac layer for style sharing feature
  src/components/DataCard.svelte
  src/components/StyleShare.svelte
  src/lib/types/Layer.ts
Labels: bug

#894 Feature/850 data card info popup
  src/components/DataCard.svelte
  src/components/DataCardInfo.svelte
  src/components/control-groups/LayerControlGroup.svelte
  src/components/controls/DataCardInfoButton.svelte
Labels: enhancement

#895 updated sveltekit
  package.json
  pnpm-lock.yaml
  src/components/Content.svelte
  src/components/ContentSidebar.svelte
  src/components/DataView.svelte
  src/components/Header.svelte
  src/components/LayerList.svelte
  src/components/controls/Breadcrumbs.svelte
  src/components/controls/TextFilter.svelte
Labels: bug

#896 fixed minimap width
  src/components/DataCard.svelte
Labels: bug

#905 Feature/901 pgtileserv function
  src/lib/helper/generateMetadataJson.ts
  src/lib/helper/getPgtileservTileJson.ts
  src/lib/helper/getStaticPbfMetadataJson.ts
  src/routes/api/vector/[source]/tile.json/+server.ts
  src/routes/api/vector/statistics/+server.ts
  static/api/docs/swagger.yaml
Labels: enhancement

#907 Fix/ci for deploy
  pnpm-lock.yaml
  sites/geohub/package.json
Labels: bug

#908 Fix/move lefthook from dev
  package.json
  pnpm-lock.yaml
Labels: bug

#909 set link-workspace-packages as deep
  .npmrc
Labels: bug

#910 Fix/disable shared workspace lockfile
  .github/workflows/main_undpgeohub.yml
  .npmrc
  pnpm-lock.yaml
  sites/geohub/pnpm-lock.yaml
Labels: bug

#912 fixed CI to pnpm install with filter geohub only
  .github/workflows/main_undpgeohub.yml
Labels: bug

#916 Feature/create style switcher package
  README.md
  packages/style-switcher/.eslintignore
  packages/style-switcher/.eslintrc.cjs
  packages/style-switcher/.gitignore
  packages/style-switcher/.npmrc
  packages/style-switcher/.prettierignore
  packages/style-switcher/.prettierrc
  packages/style-switcher/README.md
  packages/style-switcher/package.json
  packages/style-switcher/pnpm-lock.yaml
  packages/style-switcher/src/app.d.ts
  packages/style-switcher/src/app.html
  packages/style-switcher/src/example/Map.svelte
  packages/style-switcher/src/lib/StyleDefinition.ts
  packages/style-switcher/src/lib/StyleSwitcher.svelte
  packages/style-switcher/src/lib/index.ts
  packages/style-switcher/src/routes/+page.svelte
  packages/style-switcher/src/routes/+page.ts
  packages/style-switcher/static/favicon.png
  packages/style-switcher/svelte.config.js
  packages/style-switcher/tsconfig.json
  packages/style-switcher/vite.config.js
  pnpm-workspace.yaml
  sites/geohub/package.json
  sites/geohub/pnpm-lock.yaml
  sites/geohub/src/components/Map.svelte
  sites/geohub/src/dashboards/components/Map.svelte
  sites/geohub/src/lib/components/StyleSwitcher.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/types/index.ts
Labels: refactor

#917 Feature/add current location package
  README.md
  packages/current-location/.env.example
  packages/current-location/.eslintignore
  packages/current-location/.eslintrc.cjs
  packages/current-location/.gitignore
  packages/current-location/.npmrc
  packages/current-location/.prettierignore
  packages/current-location/.prettierrc
  packages/current-location/README.md
  packages/current-location/package.json
  packages/current-location/pnpm-lock.yaml
  packages/current-location/src/app.d.ts
  packages/current-location/src/app.html
  packages/current-location/src/example/Map.svelte
  packages/current-location/src/lib/AdminLayer.ts
  packages/current-location/src/lib/CurrentLocation.svelte
  packages/current-location/src/lib/index.ts
  packages/current-location/src/routes/+page.svelte
  packages/current-location/src/routes/+page.ts
  packages/current-location/static/favicon.png
  packages/current-location/svelte.config.js
  packages/current-location/tsconfig.json
  packages/current-location/vite.config.js
  sites/geohub/package.json
  sites/geohub/pnpm-lock.yaml
  sites/geohub/src/components/Map.svelte
  sites/geohub/src/dashboards/components/Map.svelte
  sites/geohub/src/dashboards/components/StyleViewer.svelte
  sites/geohub/src/lib/adminLayer.ts
  sites/geohub/src/lib/components/CurrentLocation.svelte
Labels: refactor

#918 Refactor/create dataview folder
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/controls/DataCardInfoButton.svelte
  sites/geohub/src/components/data-view/AddLayerButton.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
  sites/geohub/src/components/data-view/DataCategoryCard.svelte
  sites/geohub/src/components/data-view/DataCategoryCardList.svelte
  sites/geohub/src/components/data-view/DataStacAssetCard.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
Labels: refactor

#921 add shared-workspace-lockfile = false in .npmrc in CI instead of adding in original one
  .github/workflows/main_undpgeohub.yml
  .npmrc
  packages/current-location/pnpm-lock.yaml
  packages/geohub-cli/pnpm-lock.yaml
  packages/style-switcher/pnpm-lock.yaml
  pnpm-lock.yaml
  sites/geohub/pnpm-lock.yaml
Labels: enhancement

#923 Feature/922 add selected tags
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/SelectedTags.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/types/Tag.ts
Labels: enhancement

#927 reset tag list when tag is deleted
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/SelectedTags.svelte
Labels: bug

#929 Fix/928 reduce nodemodule size
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/helper/createDatasetSearchWhereExpression.ts
  sites/geohub/src/lib/helper/fetchVectorInfo.ts
  sites/geohub/src/lib/helper/generateMetadataJson.ts
  sites/geohub/src/lib/helper/getMartinTileJson.ts
  sites/geohub/src/lib/helper/getPgtileservTileJson.ts
  sites/geohub/src/lib/types/Tag.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/stac/mosaicjson/+server.ts
  sites/geohub/src/routes/api/storages/+server.ts
  sites/geohub/src/routes/api/tags/+server.ts
  sites/geohub/src/routes/api/vector/[source]/metadata.json/+server.ts
  sites/geohub/src/routes/api/vector/[source]/tile.json/+server.ts
  sites/geohub/src/routes/api/vector/statistics/+server.ts
Labels: enhancement

#931 Fix/930 adjust layer tab layout
  sites/geohub/src/components/LayerList.svelte
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/control-groups/LayerControlGroup.svelte
  sites/geohub/src/components/control-groups/LayerNameGroup.svelte
  sites/geohub/src/components/control-groups/StyleControlGroup.svelte
  sites/geohub/src/components/controls/ActionsDropdown.svelte
  sites/geohub/src/components/controls/DeleteButton.svelte
  sites/geohub/src/components/controls/Notification.svelte
  sites/geohub/src/components/controls/RasterContinuousLegend.svelte
  sites/geohub/src/components/controls/vector-styles/MaplibreColorPicker.svelte
  sites/geohub/src/dashboards/components/Charts.svelte
  sites/geohub/src/dashboards/components/Content.svelte
  sites/geohub/src/styles/popper.scss
Labels: bug

#933 Fix/932 undp tab layer
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/RasterExpression.svelte
  sites/geohub/src/components/controls/Tabs.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
Labels: refactor

#936 Fix/935 breadcrumb bug
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
Labels: bug

#937 deleted svelte-fa
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/BannerMessageControl.svelte
  sites/geohub/src/components/MapQueryInfoPanel.svelte
  sites/geohub/src/components/controls/ActionsDropdown.svelte
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/ColorPicker.svelte
  sites/geohub/src/components/controls/DeleteButton.svelte
  sites/geohub/src/components/controls/LayerOrderButtons.svelte
  sites/geohub/src/components/controls/Notification.svelte
  sites/geohub/src/components/controls/NumberInput.svelte
  sites/geohub/src/components/controls/RasterExpressionBuilder.svelte
  sites/geohub/src/components/controls/RasterExpressionSimple.svelte
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
  sites/geohub/src/components/controls/VectorLineContainer.svelte
  sites/geohub/src/components/controls/VectorPolygonContainer.svelte
  sites/geohub/src/components/controls/VectorSymbolContainer.svelte
  sites/geohub/src/components/controls/VisibilityButton.svelte
  sites/geohub/src/components/controls/vector-styles/IconImagePicker.svelte
  sites/geohub/src/components/controls/vector-styles/IconImagePickerCard.svelte
  sites/geohub/src/dashboards/components/DashboardHeader.svelte
  sites/geohub/src/dashboards/components/DashboardMapStyleCard.svelte
  sites/geohub/src/dashboards/components/TimeSlider.svelte
  sites/geohub/src/lib/types/OperatorCategory.ts
  sites/geohub/src/routes/dashboards/+page.svelte
Labels: refactor

#938 zoom to lv5 when MS stac is selected
  sites/geohub/src/components/DataView.svelte
Labels: enhancement

#942 fixed bug of focusing tooltip when moving by tab key
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/StyleShare.svelte
  sites/geohub/src/components/controls/ActionsDropdown.svelte
  sites/geohub/src/components/controls/DataCardInfoButton.svelte
  sites/geohub/src/components/controls/DeleteButton.svelte
  sites/geohub/src/components/controls/LayerOrderButtons.svelte
  sites/geohub/src/components/controls/VisibilityButton.svelte
  sites/geohub/src/containers.ts
Labels: bug

#943 updated NPM packages and added vscode settings
  .github/workflows/main_undpgeohub.yml
  .vscode/extensions.json
  .vscode/settings.json
  package.json
  packages/current-location/package.json
  packages/style-switcher/package.json
  pnpm-lock.yaml
  sites/geohub/package.json
Labels: enhancement

#948 fix: se new Date().getTime() instead of uuid for mosaicjson api
  sites/geohub/src/routes/api/stac/mosaicjson/+server.ts
Labels: bug

#951 fix: don't go back to top when next datasets are loaded
  sites/geohub/src/components/DataView.svelte
Labels: bug

#952 refactor: move server modules to $lib/server
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/lib/server/helpers/createDatasetSearchWhereExpression.ts
  sites/geohub/src/lib/server/helpers/fetchVectorInfo.ts
  sites/geohub/src/lib/server/helpers/generateMetadataJson.ts
  sites/geohub/src/lib/server/helpers/getMartinTileJson.ts
  sites/geohub/src/lib/server/helpers/getPgtileservTileJson.ts
  sites/geohub/src/lib/server/helpers/getStaticPbfMetadataJson.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/lib/server/variables/private.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/stac/mosaicjson/+server.ts
  sites/geohub/src/routes/api/storages/+server.ts
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/src/routes/api/style/[id].json/+server.ts
  sites/geohub/src/routes/api/style/[id]/+server.ts
  sites/geohub/src/routes/api/tags/+server.ts
  sites/geohub/src/routes/api/vector/[source]/metadata.json/+server.ts
  sites/geohub/src/routes/api/vector/[source]/tile.json/+server.ts
  sites/geohub/src/routes/api/vector/statistics/+server.ts
  sites/geohub/src/routes/dashboards/+page.server.ts
Labels: refactor

#959 Fix/953 reset tag
  sites/geohub/src/components/DataView.svelte
Labels: bug

#961 refactor: removed google font css import
  sites/geohub/src/app.html
Labels: refactor

#964 updated npm packages
  package.json
  packages/current-location/package.json
  packages/geohub-cli/package.json
  packages/style-switcher/package.json
  pnpm-lock.yaml
  sites/geohub/package.json
Labels: refactor

#946 feat: add layer order feature
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/LayerList.svelte
  sites/geohub/src/components/LayerOrder.svelte
  sites/geohub/src/components/controls/ActionsDropdown.svelte
  sites/geohub/src/components/controls/LayerOrderButtons.svelte
  sites/geohub/src/components/controls/PanelButton.svelte
Labels: enhancement

#965 fix: fixed bug of icon image picker. and also fixed some position of color picker
  sites/geohub/src/components/controls/vector-styles/HeatmapColorRow.svelte
  sites/geohub/src/components/controls/vector-styles/IconImage.svelte
  sites/geohub/src/components/controls/vector-styles/MaplibreColorPicker.svelte
Labels: bug

#966 use popperjs in panelButton component
  sites/geohub/src/components/LayerOrder.svelte
  sites/geohub/src/components/controls/PanelButton.svelte
Labels: bug

#967 refactor: created @undp-data/style-viewer package
  packages/style-viewer/.env.example
  packages/style-viewer/.eslintignore
  packages/style-viewer/.eslintrc.cjs
  packages/style-viewer/.gitignore
  packages/style-viewer/.npmrc
  packages/style-viewer/.prettierignore
  packages/style-viewer/.prettierrc
  packages/style-viewer/README.md
  packages/style-viewer/package.json
  packages/style-viewer/src/app.d.ts
  packages/style-viewer/src/app.html
  packages/style-viewer/src/lib/StyleViewer.svelte
  packages/style-viewer/src/lib/index.js
  packages/style-viewer/src/routes/+page.svelte
  packages/style-viewer/src/routes/+page.ts
  packages/style-viewer/static/favicon.png
  packages/style-viewer/svelte.config.js
  packages/style-viewer/tsconfig.json
  packages/style-viewer/vite.config.js
  pnpm-lock.yaml
  sites/geohub/.npmrc
  sites/geohub/package.json
  sites/geohub/src/app.html
  sites/geohub/src/dashboards/components/MapQueryInfoControl.svelte
  sites/geohub/src/dashboards/components/StyleViewer.svelte
  sites/geohub/src/routes/+page.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/routes/dashboards/electricity/+page.svelte
  sites/geohub/src/routes/viewer/+page.svelte
Labels: refactor

#970 refactor: move undp accordion, breadcrumb and tabs components
  README.md
  packages/svelte-undp-design/src/lib/Accordion.svelte
  packages/svelte-undp-design/src/lib/Breadcrumbs.svelte
  packages/svelte-undp-design/src/lib/Tabs.svelte
  packages/svelte-undp-design/src/lib/css/accordion.min.css
  packages/svelte-undp-design/src/lib/css/breadcrumbs.min.css
  packages/svelte-undp-design/src/lib/css/tab.min.css
  packages/svelte-undp-design/src/lib/index.ts
  packages/svelte-undp-design/src/lib/interfaces/Breadcrumb.ts
  packages/svelte-undp-design/src/lib/interfaces/Tab.ts
  packages/svelte-undp-design/src/lib/interfaces/index.ts
  packages/svelte-undp-design/src/routes/+page.svelte
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/controls/Accordion.svelte
  sites/geohub/src/components/controls/Breadcrumbs.svelte
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/RasterExpression.svelte
  sites/geohub/src/components/controls/RasterExpressionBuilder.svelte
  sites/geohub/src/components/controls/Tabs.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataCategoryCard.svelte
  sites/geohub/src/components/data-view/DataCategoryCardList.svelte
  sites/geohub/src/components/data-view/DataStacAssetCard.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/types/DataCategory.ts
  sites/geohub/src/lib/types/Tab.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/styles/undp-design/accordion.min.css
  sites/geohub/src/styles/undp-design/breadcrumbs.min.css
  sites/geohub/src/styles/undp-design/custom-select.min.css
  sites/geohub/src/styles/undp-design/input-fields.min.css
  sites/geohub/src/styles/undp-design/mobile-nav.min.css
  sites/geohub/src/styles/undp-design/modal.min.css
  sites/geohub/src/styles/undp-design/tab.min.css
Labels: refactor

#963 feat: add Dockerfile for production server environment
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: enhancement

#972 moved button component to package
  packages/svelte-undp-design/src/lib/Button.svelte
  packages/svelte-undp-design/src/lib/index.ts
  packages/svelte-undp-design/src/routes/+page.svelte
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/AddLayerButton.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/dashboards/components/DashboardMapStyleCard.svelte
  sites/geohub/src/dashboards/components/DownloadData.svelte
  sites/geohub/src/dashboards/components/IntroductionPanel.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/styles/undp-design/buttons.min.css
Labels: refactor

#974 migrated checkbox to undp-design package
  packages/svelte-undp-design/src/lib/Checkbox.svelte
  packages/svelte-undp-design/src/lib/Tabs.svelte
  packages/svelte-undp-design/src/lib/css/checkbox.min.css
  packages/svelte-undp-design/src/lib/index.ts
  packages/svelte-undp-design/src/routes/+page.svelte
  packages/svelte-undp-design/static/fonts/NotoSansMyanmar-Bold.woff
  packages/svelte-undp-design/static/fonts/NotoSansMyanmar-Bold.woff2
  packages/svelte-undp-design/static/fonts/NotoSansMyanmar-Light.woff
  packages/svelte-undp-design/static/fonts/NotoSansMyanmar-Light.woff2
  packages/svelte-undp-design/static/fonts/NotoSansMyanmar-Medium.woff
  packages/svelte-undp-design/static/fonts/NotoSansMyanmar-Medium.woff2
  packages/svelte-undp-design/static/fonts/NotoSansMyanmar-Regular.woff
  packages/svelte-undp-design/static/fonts/NotoSansMyanmar-Regular.woff2
  packages/svelte-undp-design/static/fonts/NotoSansMyanmar-SemiBold.woff
  packages/svelte-undp-design/static/fonts/NotoSansMyanmar-SemiBold.woff2
  packages/svelte-undp-design/static/fonts/Proxima Nova—bold.otf
  packages/svelte-undp-design/static/fonts/Proxima Nova—boldit.otf
  packages/svelte-undp-design/static/fonts/Proxima Nova—regular.otf
  packages/svelte-undp-design/static/fonts/Proxima Nova—regularit.otf
  packages/svelte-undp-design/static/fonts/Proxima Nova—semibold.otf
  packages/svelte-undp-design/static/fonts/Proxima Nova—semiboldit.otf
  packages/svelte-undp-design/static/fonts/SöhneBreit-Dreiviertelfett.otf
  packages/svelte-undp-design/static/fonts/SöhneBreit-DreiviertelfettKursiv.otf
  packages/svelte-undp-design/static/fonts/SöhneBreit-Fett.otf
  packages/svelte-undp-design/static/fonts/SöhneBreit-FettKursiv.otf
  packages/svelte-undp-design/static/fonts/proximanova-bold-webfont.woff
  packages/svelte-undp-design/static/fonts/proximanova-bold-webfont.woff2
  packages/svelte-undp-design/static/fonts/proximanova-boldit-webfont.woff
  packages/svelte-undp-design/static/fonts/proximanova-boldit-webfont.woff2
  packages/svelte-undp-design/static/fonts/proximanova-regular-webfont.woff
  packages/svelte-undp-design/static/fonts/proximanova-regular-webfont.woff2
  packages/svelte-undp-design/static/fonts/proximanova-regularit-webfont.woff
  packages/svelte-undp-design/static/fonts/proximanova-regularit-webfont.woff2
  packages/svelte-undp-design/static/fonts/proximanova-semibold-webfont.woff
  packages/svelte-undp-design/static/fonts/proximanova-semibold-webfont.woff2
  packages/svelte-undp-design/static/fonts/proximanova-semiboldit-webfont.woff
  packages/svelte-undp-design/static/fonts/proximanova-semiboldit-webfont.woff2
  packages/svelte-undp-design/static/fonts/soehne-breit-web-dreiviertelfett-kursiv.eot
  packages/svelte-undp-design/static/fonts/soehne-breit-web-dreiviertelfett-kursiv.woff
  packages/svelte-undp-design/static/fonts/soehne-breit-web-dreiviertelfett-kursiv.woff2
  packages/svelte-undp-design/static/fonts/soehne-breit-web-dreiviertelfett.eot
  packages/svelte-undp-design/static/fonts/soehne-breit-web-dreiviertelfett.woff
  packages/svelte-undp-design/static/fonts/soehne-breit-web-dreiviertelfett.woff2
  packages/svelte-undp-design/static/fonts/soehne-breit-web-fett-kursiv.eot
  packages/svelte-undp-design/static/fonts/soehne-breit-web-fett-kursiv.woff
  packages/svelte-undp-design/static/fonts/soehne-breit-web-fett-kursiv.woff2
  packages/svelte-undp-design/static/fonts/soehne-breit-web-fett.eot
  packages/svelte-undp-design/static/fonts/soehne-breit-web-fett.woff
  packages/svelte-undp-design/static/fonts/soehne-breit-web-fett.woff2
  sites/geohub/src/components/LayerOrder.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/styles/undp-design/checkbox.min.css
Labels: refactor

#975 Fix/973 reset tag list
  sites/geohub/src/components/DataView.svelte
Labels: bug

#978 Refactor/add cta link component
  packages/svelte-undp-design/src/lib/CtaLink.svelte
  packages/svelte-undp-design/src/lib/index.ts
  packages/svelte-undp-design/src/routes/+page.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
  sites/geohub/src/dashboards/components/DashboardMapStyleCard.svelte
  sites/geohub/src/styles/undp-design/cta-link.min.css
Labels: refactor

#979 add loader component
  packages/svelte-undp-design/src/lib/Loader.svelte
  packages/svelte-undp-design/src/lib/css/loader.min.css
  packages/svelte-undp-design/src/lib/index.ts
  packages/svelte-undp-design/src/routes/+page.svelte
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/styles/undp-design/loader.min.css
Labels: refactor

#980 fix: changed prop name for undp design's radio
  packages/svelte-undp-design/package.json
  packages/svelte-undp-design/src/lib/Radios.svelte
  packages/svelte-undp-design/src/lib/interfaces/Radio.ts
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
Labels: refactor

#982 feat: added storybook for UNDP design package
  packages/svelte-undp-design/.eslintrc.cjs
  packages/svelte-undp-design/.storybook/main.cjs
  packages/svelte-undp-design/.storybook/preview-head.html
  packages/svelte-undp-design/.storybook/preview.js
  packages/svelte-undp-design/README.md
  packages/svelte-undp-design/package.json
  packages/svelte-undp-design/src/lib/Accordion/Accordion.stories.ts
  packages/svelte-undp-design/src/lib/Accordion/Accordion.svelte
  packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.stories.ts
  packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.svelte
  packages/svelte-undp-design/src/lib/Button/Button.stories.ts
  packages/svelte-undp-design/src/lib/Button/Button.svelte
  packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.stories.ts
  packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.svelte
  packages/svelte-undp-design/src/lib/Checkbox/Checkbox.stories.ts
  packages/svelte-undp-design/src/lib/Checkbox/Checkbox.svelte
  packages/svelte-undp-design/src/lib/CtaLink/CtaLink.stories.ts
  packages/svelte-undp-design/src/lib/CtaLink/CtaLink.svelte
  packages/svelte-undp-design/src/lib/Footer/Footer.stories.ts
  packages/svelte-undp-design/src/lib/Footer/Footer.svelte
  packages/svelte-undp-design/src/lib/Header/Header.stories.ts
  packages/svelte-undp-design/src/lib/Header/Header.svelte
  packages/svelte-undp-design/src/lib/Introduction.mdx
  packages/svelte-undp-design/src/lib/Loader/Loader.stories.ts
  packages/svelte-undp-design/src/lib/Loader/Loader.svelte
  packages/svelte-undp-design/src/lib/Radios/Radios.stories.ts
  packages/svelte-undp-design/src/lib/Radios/Radios.svelte
  packages/svelte-undp-design/src/lib/Tabs/Tabs.stories.ts
  packages/svelte-undp-design/src/lib/Tabs/Tabs.svelte
  packages/svelte-undp-design/src/lib/index.ts
  packages/svelte-undp-design/src/routes/+page.svelte
  pnpm-lock.yaml
Labels: enhancement

#981 Refactor/vector layer UI
  .gitignore
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/VectorPolygonAdvanced.svelte
  sites/geohub/src/components/controls/vector-styles/PropertySelect.svelte
Labels: frontend, refactor

#983 changed style api and fixed bugs of style list in dashboard
  sites/geohub/src/dashboards/components/MapStyleCardList.svelte
  sites/geohub/src/lib/server/helpers/getStyleCount.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/src/routes/api/style/count/+server.ts
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/static/api/docs/swagger.yaml
Labels: bug, frontend, backend

#986 updated npm packages and build storybook to static folder of geohub
  .github/workflows/main_undpgeohub.yml
  packages/current-location/package.json
  packages/geohub-cli/package.json
  packages/style-switcher/package.json
  packages/style-viewer/package.json
  packages/svelte-undp-design/.gitignore
  packages/svelte-undp-design/.npmrc
  packages/svelte-undp-design/package.json
  pnpm-lock.yaml
  sites/geohub/.gitignore
  sites/geohub/package.json
Labels: bug

#990 add pagination component in undp-design package
  packages/svelte-undp-design/.eslintignore
  packages/svelte-undp-design/.prettierignore
  packages/svelte-undp-design/src/lib/Pagination/Pagination.stories.ts
  packages/svelte-undp-design/src/lib/Pagination/Pagination.svelte
  packages/svelte-undp-design/src/lib/css/pagination.min.css
  packages/svelte-undp-design/src/lib/index.ts
  sites/geohub/src/components/controls/IntervalsLegendColorMapRow.svelte
  sites/geohub/src/components/controls/RasterExpression.svelte
  sites/geohub/src/components/controls/RasterExpressionBuilder.svelte
  sites/geohub/src/components/controls/UniqueValuesLegendColorMapRow.svelte
  sites/geohub/src/dashboards/components/DashboardMapStyleCard.svelte
  sites/geohub/src/dashboards/components/MapStyleCardList.svelte
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/lib/server/helpers/pageNumber.ts
  sites/geohub/src/lib/types/DashboardMapStyle.ts
  sites/geohub/src/lib/types/Pages.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/styles/undp-design/base-minimal.min.css
  sites/geohub/src/styles/undp-design/content-card.min.css
  sites/geohub/src/styles/undp-design/pagination.min.css
  sites/geohub/src/styles/undp-design/variables.scss
  sites/geohub/static/api/docs/swagger.yaml
Labels: enhancement

#991 Feature/add relative header
  packages/svelte-undp-design/src/lib/Header/Header.stories.ts
  packages/svelte-undp-design/src/lib/Header/Header.svelte
  sites/geohub/src/components/BannerMessageControl.svelte
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/ContentSidebar.svelte
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/Map.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
Labels: refactor

#992 installed bulma-switch and bulma-divider from npm
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/controls/VectorLegendPanel.svelte
  sites/geohub/src/dashboards/components/DashboardMapStyleCard.svelte
  sites/geohub/src/dashboards/components/MapStyleCardList.svelte
  sites/geohub/src/routes/+page.svelte
  sites/geohub/src/styles/bulma-divider.min.css
  sites/geohub/src/styles/bulma-switch.min.css
Labels: refactor

#993 fixed search api for tag search with OR operator
  .github/workflows/build-packages.yml
  .github/workflows/main_undpgeohub.yml
  lefthook.yml
  package.json
  packages/current-location/.gitignore
  packages/current-location/package.json
  packages/geohub-cli/.gitignore
  packages/style-switcher/.gitignore
  packages/style-switcher/package.json
  packages/style-viewer/.gitignore
  packages/style-viewer/package.json
  packages/svelte-undp-design/.gitignore
  packages/svelte-undp-design/package.json
  pnpm-lock.yaml
  sites/geohub/.gitignore
  sites/geohub/package.json
  sites/geohub/src/routes/api/tags/+server.ts
  turbo.json
Labels: bug

#996 added tag clear button
  sites/geohub/src/components/data-view/SelectedTags.svelte
Labels: enhancement

#998 Feature/introduce carousel to dashboard
  packages/svelte-undp-design/package.json
  packages/svelte-undp-design/src/lib/FluidCarousel/FluidCarousel.stories.ts
  packages/svelte-undp-design/src/lib/FluidCarousel/FluidCarousel.svelte
  packages/svelte-undp-design/src/lib/FluidCarousel/svelte-carousel.svelte.d.ts
  packages/svelte-undp-design/src/lib/css/fluid-image-size-carousel.min.css
  packages/svelte-undp-design/src/lib/css/swiper.min.css
  packages/svelte-undp-design/src/lib/index.ts
  packages/svelte-undp-design/src/lib/interfaces/CarouselContent.ts
  packages/svelte-undp-design/src/lib/interfaces/index.ts
  packages/svelte-undp-design/static/media/fluid-carousel-img.jpg
  packages/svelte-undp-design/vite.config.js
  pnpm-lock.yaml
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/data-view/DataCategoryCardList.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/static/1200px-UNDP_logo.svg-148x300.png
  sites/geohub/static/assets/crunchy-spatial-logo.png
  sites/geohub/static/assets/electricity-snapshot.png
  sites/geohub/static/assets/maplibre.png
  sites/geohub/static/assets/sdgs/1.png
  sites/geohub/static/assets/sdgs/10.png
  sites/geohub/static/assets/sdgs/11.png
  sites/geohub/static/assets/sdgs/12.png
  sites/geohub/static/assets/sdgs/13.png
  sites/geohub/static/assets/sdgs/14.png
  sites/geohub/static/assets/sdgs/15.png
  sites/geohub/static/assets/sdgs/16.png
  sites/geohub/static/assets/sdgs/17.png
  sites/geohub/static/assets/sdgs/2.png
  sites/geohub/static/assets/sdgs/3.png
  sites/geohub/static/assets/sdgs/4.png
  sites/geohub/static/assets/sdgs/5.png
  sites/geohub/static/assets/sdgs/6.png
  sites/geohub/static/assets/sdgs/7.png
  sites/geohub/static/assets/sdgs/8.png
  sites/geohub/static/assets/sdgs/9.png
  sites/geohub/static/assets/sdgs/SDG Wheel_WEB.png
  sites/geohub/static/assets/undp-images/undp-logo-blue.svg
  sites/geohub/static/assets/undp-images/undp-logo-white.svg
  sites/geohub/static/electricity-snapshot.jpg
  sites/geohub/static/stac.png
  sites/geohub/static/undp-images/default-arrow-left.svg
  sites/geohub/static/undp-images/hamburger.svg
  sites/geohub/static/undp-images/long-arrow-left.svg
  sites/geohub/vite.config.ts
Labels: enhancement

#1000 Feature/999 enhance share
  sites/geohub/src/components/StyleShare.svelte
Labels: enhancement

#1001 added .env.example
  sites/geohub/env.example
Labels: documentation

#1002 added electricity-dashboard app
  README.md
  apps/electricity-dashboard/.env.example
  apps/electricity-dashboard/.eslintignore
  apps/electricity-dashboard/.eslintrc.cjs
  apps/electricity-dashboard/.gitignore
  apps/electricity-dashboard/.npmrc
  apps/electricity-dashboard/.prettierignore
  apps/electricity-dashboard/.prettierrc
  apps/electricity-dashboard/.turbo/turbo-lint.log
  apps/electricity-dashboard/README.md
  apps/electricity-dashboard/package.json
  apps/electricity-dashboard/src/app.d.ts
  apps/electricity-dashboard/src/app.html
  apps/electricity-dashboard/src/lib/ElectricityDashboard.svelte
  apps/electricity-dashboard/src/lib/components/Charts.svelte
  apps/electricity-dashboard/src/lib/components/Content.svelte
  apps/electricity-dashboard/src/lib/components/DownloadData.svelte
  apps/electricity-dashboard/src/lib/components/ElectricityControl.svelte
  apps/electricity-dashboard/src/lib/components/ElectricityLegend.svelte
  apps/electricity-dashboard/src/lib/components/IntroductionPanel.svelte
  apps/electricity-dashboard/src/lib/components/Map.svelte
  apps/electricity-dashboard/src/lib/components/OverlayControl.svelte
  apps/electricity-dashboard/src/lib/components/TimeSlider.svelte
  apps/electricity-dashboard/src/lib/index.ts
  apps/electricity-dashboard/src/lib/stores/index.ts
  apps/electricity-dashboard/src/lib/utils/adminLayer.ts
  apps/electricity-dashboard/src/lib/utils/downloadFile.ts
  apps/electricity-dashboard/src/routes/+page.svelte
  apps/electricity-dashboard/src/routes/+page.ts
  apps/electricity-dashboard/static/favicon.png
  apps/electricity-dashboard/svelte.config.js
  apps/electricity-dashboard/tsconfig.json
  apps/electricity-dashboard/vite.config.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
  sites/geohub/package.json
  sites/geohub/src/dashboards/components/Charts.svelte
  sites/geohub/src/dashboards/components/Content.svelte
  sites/geohub/src/dashboards/components/DownloadData.svelte
  sites/geohub/src/dashboards/components/ElectricityControl.svelte
  sites/geohub/src/dashboards/components/ElectricityLegend.svelte
  sites/geohub/src/dashboards/components/IntroductionPanel.svelte
  sites/geohub/src/dashboards/components/Map.svelte
  sites/geohub/src/dashboards/components/OverlayControl.svelte
  sites/geohub/src/dashboards/components/TimeSlider.svelte
  sites/geohub/src/dashboards/stores/index.ts
  sites/geohub/src/dashboards/utils/adminLayer.ts
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
  sites/geohub/src/lib/dashboards/MapStyleCardList.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/routes/dashboards/electricity/+page.svelte
Labels: refactor

#1004 Feature/999 style restore
  packages/geohub-cli/.gitignore
  packages/geohub-cli/docs/database.vuerd.json
  packages/geohub-cli/docs/geohub-database-erd.png
  packages/geohub-cli/docs/geohub-database.sql
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/StyleShare.svelte
  sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/VectorLineAdvanced.svelte
  sites/geohub/src/components/controls/VectorPolygonAdvanced.svelte
  sites/geohub/src/components/controls/VectorSymbolAdvanced.svelte
  sites/geohub/src/components/controls/vector-styles/SymbolPlacement.svelte
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
  sites/geohub/src/lib/dashboards/MapStyleCardList.svelte
  sites/geohub/src/lib/types/DashboardMapStyle.ts
  sites/geohub/src/lib/types/Layer.ts
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/src/routes/api/style/[id]/+server.ts
  sites/geohub/static/api/docs/swagger.yaml
Labels: enhancement, frontend, backend

#1008 added .turbo folder in gitignore
  apps/electricity-dashboard/.gitignore
  apps/electricity-dashboard/.turbo/turbo-lint.log
Labels: bug

#1012 fixed to restore vector label from previous style
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
Labels: bug

#1015 initialise opacity from style.json
  sites/geohub/src/components/controls/OpacityPanel.svelte
Labels: bug

#1018 Fix/1016 init legendtype vector layer
  pnpm-lock.yaml
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/VectorLineContainer.svelte
  sites/geohub/src/components/controls/VectorPolygonContainer.svelte
  sites/geohub/src/components/controls/VectorSymbolContainer.svelte
  sites/geohub/src/components/controls/vector-styles/PropertySelect.svelte
  sites/geohub/src/components/controls/vector-styles/TextField.svelte
  sites/geohub/src/lib/helper/getPropertyValueFromExpression.ts
  sites/geohub/src/lib/helper/index.ts
Labels: bug

#1011 Style: Enhance Styles For Top Level Tabs, Breadcrumbs and Tooltip
  packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.stories.ts
  packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.svelte
  packages/svelte-undp-design/src/lib/Tabs/Tabs.svelte
  pnpm-lock.yaml
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/controls/ActionsDropdown.svelte
  sites/geohub/src/components/controls/DataCardInfoButton.svelte
  sites/geohub/src/components/controls/DeleteButton.svelte
  sites/geohub/src/components/controls/PanelButton.svelte
  sites/geohub/src/components/controls/RasterBandSelector.svelte
  sites/geohub/src/components/controls/RasterExpressionBuilder.svelte
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
  sites/geohub/src/components/controls/VectorLineContainer.svelte
  sites/geohub/src/components/controls/VectorPolygonAdvanced.svelte
  sites/geohub/src/components/controls/VectorPolygonContainer.svelte
  sites/geohub/src/components/controls/VectorSymbolContainer.svelte
  sites/geohub/src/components/controls/VisibilityButton.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
Labels: awaiting review, frontend, refactor

#1021 fix: set classification from restored style.json fro vector and raster layer
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/LayerList.svelte
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/VectorLayer.svelte
Labels: bug

#1023 Fix/1022 restore colormap name
  sites/geohub/src/components/LayerList.svelte
  sites/geohub/src/components/StyleShare.svelte
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
  sites/geohub/src/components/controls/VectorLineContainer.svelte
  sites/geohub/src/components/controls/VectorPolygonContainer.svelte
  sites/geohub/src/components/controls/VectorSymbolAdvanced.svelte
  sites/geohub/src/components/controls/VectorSymbolContainer.svelte
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/static/api/docs/swagger.yaml
Labels: bug

#1024 fixed dashboard tooltip name
  sites/geohub/src/components/Header.svelte
Labels: bug

#1025 updated package.json
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/tsconfig.json
Labels: refactor

#1029 Increased the size of the sidebar for the tabs to fit
  sites/geohub/src/components/ContentSidebar.svelte
Labels: bug, frontend

#1031 fix: restore vector filter expression to wizard
  sites/geohub/src/components/controls/VectorFilterPanelWizard.svelte
Labels: bug

#1034 Fix map query info to display the right information for each visible layer
  sites/geohub/src/components/MapQueryInfoPanel.svelte
Labels: bug, refactor

#1037 fixed a bug of initialising raster legend from existing sytle.json
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
Labels: bug

#1038 deleted service worker since it has error
  packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.svelte
  sites/geohub/src/service-worker.ts
Labels: refactor

#1041 fixed bugs of restoring unique value legend in raster layer
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
Labels: bug

#1042 Feature/1030 state of dashboard url
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
  sites/geohub/src/lib/dashboards/MapStyleCardList.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/routes/dashboards/+page.ts
Labels: enhancement

#1044 Fix/dashboard delete
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
  sites/geohub/src/lib/dashboards/MapStyleCardList.svelte
Labels: bug

#1045 added sort by feature in dashboard
  sites/geohub/src/lib/dashboards/MapStyleCardList.svelte
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/static/api/docs/swagger.yaml
Labels: enhancement

#1046 Feature/1032 dashboard search
  sites/geohub/src/lib/dashboards/MapStyleCardList.svelte
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/static/api/docs/swagger.yaml
Labels: enhancement

#1050 redesigning map query tool
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/Map.svelte
  sites/geohub/src/components/MapQueryInfoControl.svelte
  sites/geohub/src/components/MapQueryInfoPanel.svelte
  sites/geohub/src/components/controls/Notification.svelte
Labels: enhancement

#1051 removed untargetd layers (like STAC) from saved
  sites/geohub/src/components/StyleShare.svelte
Labels: bug

#1053 automatically close other accordions if an accordion is expanded
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataStacAssetCard.svelte
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
  sites/geohub/src/lib/dashboards/MapStyleCardList.svelte
Labels: enhancement

#1054 added a button to open style map when accordion is closed in dashboard
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
Labels: enhancement

#1055 fixed layout of dashboard for responsive
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
  sites/geohub/src/lib/dashboards/MapStyleCardList.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
Labels: bug

#1057 fixed Dockerfile
  Dockerfile
Labels: bug
