Repository UNDP-Data/geohub, pull requests merged in 2022-10, with the labels that each got.

#641 migrate to pnpm
  .github/workflows/main_undpgeohub.yml
  .husky/pre-commit
  .npmrc
  .prettierrc
  README.md
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  yarn.lock
Labels: enhancement

#642 fix: only deploy node_modules for Dependencies
  .github/workflows/main_undpgeohub.yml
Labels: refactor

#643 start using build-in way to load env variables instead of using vite
  .env.example
  .github/workflows/main_undpgeohub.yml
  README.md
  src/components/BucketTreeNode.svelte
  src/components/BucketTreeNodeCardButton.svelte
  src/components/IntervalsLegend.svelte
  src/components/Map.svelte
  src/components/MapQueryInfoPanel.svelte
  src/components/RasterHistogram.svelte
  src/components/RasterLegendContainer.svelte
  src/components/UNDPComponents/Content_UNDP.svelte
  src/dashboards/components/Charts.svelte
  src/dashboards/components/ElectricityControl.svelte
  src/dashboards/components/OverlayControl.svelte
  src/dashboards/components/StyleViewer.svelte
  src/dashboards/components/TimeSlider.svelte
  src/dashboards/utils/adminLayer.ts
  src/lib/constants.ts
  src/lib/variables.ts
  src/lib/variables/private.ts
  src/lib/variables/public.ts
  src/routes/+page.server.ts
  src/routes/azstorage.json/+server.ts
  src/routes/dashboards/+page.server.ts
  src/routes/stac.json/+server.ts
  src/routes/style/+server.ts
  src/routes/style/[id].json/+server.ts
  src/routes/style/[id]/+server.ts
  src/routes/tags-generate.json/+server.ts
  src/routes/tags-search.json/+server.ts
Labels: refactor

#644 updated npm package version
  package.json
  pnpm-lock.yaml
Labels: refactor

#646 updated package scripts' name to use the default ones of sveltekit
  .github/workflows/main_undpgeohub.yml
  package.json
  src/lib/variables/private.ts
  src/lib/variables/public.ts
  src/routes/+page.server.ts
  src/routes/azstorage.json/+server.ts
Labels: refactor

#647 Create LICENSE
  LICENSE
  package.json
Labels: documentation

#648 Develop
  .env.example
  .github/workflows/main_undpgeohub.yml
  .husky/pre-commit
  .npmrc
  .prettierrc
  LICENSE
  README.md
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  src/components/BucketTreeNode.svelte
  src/components/BucketTreeNodeCardButton.svelte
  src/components/IntervalsLegend.svelte
  src/components/Map.svelte
  src/components/MapQueryInfoPanel.svelte
  src/components/RasterHistogram.svelte
  src/components/RasterLegendContainer.svelte
  src/components/UNDPComponents/Content_UNDP.svelte
  src/dashboards/components/Charts.svelte
  src/dashboards/components/ElectricityControl.svelte
  src/dashboards/components/OverlayControl.svelte
  src/dashboards/components/StyleViewer.svelte
  src/dashboards/components/TimeSlider.svelte
  src/dashboards/utils/adminLayer.ts
  src/lib/constants.ts
  src/lib/variables.ts
  src/lib/variables/private.ts
  src/lib/variables/public.ts
  src/routes/+page.server.ts
  src/routes/azstorage.json/+server.ts
  src/routes/dashboards/+page.server.ts
  src/routes/stac.json/+server.ts
  src/routes/style/+server.ts
  src/routes/style/[id].json/+server.ts
  src/routes/style/[id]/+server.ts
  src/routes/tags-generate.json/+server.ts
  src/routes/tags-search.json/+server.ts
  yarn.lock
Labels: enhancement

#650 fixed env variables for electricity dashboard
  .env.example
  .github/workflows/main_undpgeohub.yml
  src/components/Map.svelte
  src/dashboards/components/ElectricityControl.svelte
  src/dashboards/components/OverlayControl.svelte
  src/dashboards/components/StyleViewer.svelte
  src/dashboards/components/TimeSlider.svelte
  src/dashboards/utils/adminLayer.ts
  src/lib/variables/public.ts
Labels: bug

#654 Vector Filter Redesign
  package.json
  pnpm-lock.yaml
  src/components/IntervalsLegendColorMapRow.svelte
  src/components/LayerList.svelte
  src/components/MapQueryInfoPanel.svelte
  src/components/RasterExpressionSimple.svelte
  src/components/RasterHistogram.svelte
  src/components/RasterLayer.svelte
  src/components/StyleShare.svelte
  src/components/Tags.svelte
  src/components/UNDPComponents/Tabs_UNDP.svelte
  src/components/UniqueValuesLegendColorMapRow.svelte
  src/components/VectorLayer.svelte
  src/components/control-groups/Step.svelte
  src/components/control-groups/Wizard.svelte
  src/components/controls/NumberButtons.svelte
  src/components/controls/VectorFilterPanel.svelte
  src/components/controls/VectorFilterPanelWizard.svelte
  src/components/controls/VectorFilterPanel_New.svelte
  src/components/controls/VectorPolygonAdvanced.svelte
  src/components/controls/vector-styles/OperationButtons.svelte
  src/components/controls/vector-styles/PropertySelectButtons.svelte
  src/components/controls/vector-styles/ValueInput.svelte
  src/components/controls/vector-styles/VectorFilterExpressionCreator.svelte
  src/lib/constants.ts
Labels: enhancement, frontend, refactor

#663 fix: added lefthook install in prepare
  package.json
Labels: bug

#664 moved lefthook to dependencies
  package.json
  pnpm-lock.yaml
Labels: bug

#668 Refactor/tree node
  src/components/BucketTreeNode.svelte
  src/components/BucketTreeNodeDownloadButton.svelte
  src/components/BucketTreeNodeLegendIcon.svelte
  src/routes/martin.json/+server.ts
Labels: refactor

#670 Refactor/bucket tree node
  src/components/BucketTreeBranch.svelte
  src/components/BucketTreeBranchCloseButton.svelte
  src/components/BucketTreeBranchIcon.svelte
  src/components/BucketTreeBranchPagination.svelte
  src/components/BucketTreeItem.svelte
  src/components/BucketTreeItemCardButton.svelte
  src/components/BucketTreeItemDownloadButton.svelte
  src/components/BucketTreeItemIcon.svelte
  src/components/BucketTreeItemLegend.svelte
  src/components/BucketTreeItemRaster.svelte
  src/components/BucketTreeItemVector.svelte
  src/components/BucketTreeLabel.svelte
  src/components/BucketTreeNode.svelte
  src/components/BucketTreeView.svelte
  src/components/BucketView.svelte
  src/components/Map.svelte
  src/components/TagsView.svelte
  src/components/UNDPComponents/Content_UNDP.svelte
  src/lib/_tests__/Helper.test.ts
  src/lib/helper.ts
  src/lib/helper/clean.ts
  src/lib/helper/clipSprite.ts
  src/lib/helper/downloadFile.ts
  src/lib/helper/fetchUrl.ts
  src/lib/helper/fetchWithTimeout.ts
  src/lib/helper/generateColorMap.ts
  src/lib/helper/getActiveBandIndex.ts
  src/lib/helper/getBase64EncodedUrl.ts
  src/lib/helper/getIntervalList.ts
  src/lib/helper/getSampleFromInterval.ts
  src/lib/helper/getVectorInfo.ts
  src/lib/helper/groupByN.ts
  src/lib/helper/hash.ts
  src/lib/helper/index.ts
  src/lib/helper/loadImageToDataUrl.ts
  src/lib/helper/paramsToQueryString.ts
  src/lib/helper/remapInputValue.ts
  src/lib/helper/stringifyStyleJSON.ts
  src/lib/helper/updateParamsInURL.ts
Labels: bug, enhancement, frontend, refactor

#672 Feature/geohub docs
  .github/workflows/main_undpgeohub.yml
  .gitignore
  documentation/.gitignore
  documentation/Dockerfile
  documentation/LICENSE
  documentation/Pipfile
  documentation/Pipfile.lock
  documentation/README.md
  documentation/docs/assets/images/favicon.svg
  documentation/docs/assets/images/undp-logo-blue.svg
  documentation/docs/assets/images/undp-logo-white.svg
  documentation/docs/index.md
  documentation/docs/userguide/intro.md
  documentation/mkdocs.yml
Labels: documentation

#676 fixed issue#674. Put children property correctly if it is static vector tiles
  src/routes/azstorage.json/+server.ts
Labels: bug

#678 updated mkdocs yaml
  documentation/mkdocs.yml
Labels: documentation

#679 Fix/progress bar
  src/components/BucketTreeBranch.svelte
  src/components/BucketTreeBranchIcon.svelte
  src/components/BucketTreeItem.svelte
  src/components/BucketTreeItemIcon.svelte
  src/components/BucketTreeItemRaster.svelte
  src/components/BucketTreeItemVector.svelte
  src/components/BucketTreeView.svelte
  src/components/BucketView.svelte
  src/components/UNDPComponents/Content_UNDP.svelte
Labels: bug, frontend

#680 Feature/use sdg icons
  src/components/BucketCard.svelte
  src/lib/types.ts
  src/routes/+page.server.ts
Labels: enhancement, frontend, backend

#681 Fix/652
  .gitignore
  package.json
  pnpm-lock.yaml
  src/components/UNDPComponents/Content_UNDP.svelte
  src/components/UNDPComponents/Tabs_UNDP.svelte
  src/components/controls/vector-styles/TextColor.svelte
  src/components/controls/vector-styles/TextHaloCalor.svelte
  src/components/controls/vector-styles/ValueInput.svelte
  src/dashboards/components/Content.svelte
  src/dashboards/components/DashboardMapStyleCard.svelte
  src/dashboards/components/DownloadData.svelte
  src/dashboards/components/IntroductionPanel.svelte
  src/dashboards/components/MapStyleCardList.svelte
  src/dashboards/utils/adminLayer.ts
  src/lib/_tests__/Helper.test.ts
  src/lib/components/StyleSwitcher.svelte
  src/lib/helper/groupByN.ts
  src/management/components/MetadataField.svelte
  src/management/components/MetadataInput.svelte
  src/management/components/SDGSelect.svelte
  src/styles/bulma.css
  src/styles/bulma.css.map
  static/smui-dark.css
  static/smui.css
Labels: bug, frontend

#682 Fix/671
  src/components/ColorMapPickerCard.svelte
Labels: bug

#683 improved scroll in drawer content
  src/components/BucketView.svelte
  src/components/LayerList.svelte
  src/components/TagsView.svelte
  src/components/UNDPComponents/Content_UNDP.svelte
Labels: enhancement, frontend

#685 fix: removed a code to replace http to https since martin now was configured
  src/components/controls/AddLayerModal.svelte
Labels: bug

#686 added data/intro md
  documentation/README.md
  documentation/docker-compose.yml
  documentation/docs/assets/data/data_type.png
  documentation/docs/data/intro.md
  documentation/docs/index.md
  documentation/docs/mkdocs.yml
  documentation/docs/userguide/intro.md
  documentation/mkdocs.yml
Labels: documentation

#687 Refactor/types
  documentation/docs/mkdocs.yml
  src/lib/types.ts
  src/lib/types/ArithmeticOperator.ts
  src/lib/types/BandMetadata.ts
  src/lib/types/BandStatistics.ts
  src/lib/types/BannerMessage.ts
  src/lib/types/Bucket.ts
  src/lib/types/Color.ts
  src/lib/types/ContinuousLegend.ts
  src/lib/types/HeatmapColorRow.ts
  src/lib/types/IntervalLegend.ts
  src/lib/types/IntervalLegendColorMapRow.ts
  src/lib/types/Layer.ts
  src/lib/types/LayerInfoMetadata.ts
  src/lib/types/LayerList.ts
  src/lib/types/Layericon.ts
  src/lib/types/MartinLayerMetadata.ts
  src/lib/types/OperatorCategory.ts
  src/lib/types/RasterLayerStats.ts
  src/lib/types/RasterSimpleExpression.ts
  src/lib/types/RasterTileMetadata.ts
  src/lib/types/Sprite.ts
  src/lib/types/SpriteIcon.ts
  src/lib/types/SpriteImage.ts
  src/lib/types/StyleDefinition.ts
  src/lib/types/TagLayer.ts
  src/lib/types/TagsSearchResults.ts
  src/lib/types/Tree.ts
  src/lib/types/TreeNode.ts
  src/lib/types/UniqueLegend.ts
  src/lib/types/UniqueLegendColorMapRow.ts
  src/lib/types/VectorLayerMetadata.ts
  src/lib/types/VectorLayerTileStatAttribute.ts
  src/lib/types/VectorLayerTileStatLayer.ts
  src/lib/types/VectorTileMetadata.ts
  src/lib/types/index.ts
Labels: refactor

#688 added help icon
  src/components/UNDPComponents/Header_UNDP.svelte
Labels: enhancement

#689 Doc/data and visualization
  documentation/docs/assets/data/Figure_1.png
  documentation/docs/assets/data/Figure_2.png
  documentation/docs/assets/data/Figure_3.PNG
  documentation/docs/assets/images/sdgs.jpg
  documentation/docs/assets/visualization/Figure_5.png
  documentation/docs/assets/visualization/Figure_6.png
  documentation/docs/data/data structure.md
  documentation/docs/data/intro.md
  documentation/docs/data/special_buckets.md
  documentation/docs/visualization/map_view.md
  documentation/docs/visualization/search_data.md
  documentation/mkdocs.yml
Labels: documentation

#684 feat: stac API for mosaicjson
  data/mosaic-stac.json
  src/components/BucketTreeBranch.svelte
  src/components/BucketTreeItemCardButton.svelte
  src/components/BucketTreeItemRaster.svelte
  src/components/BucketTreeLabel.svelte
  src/components/BucketView.svelte
  src/components/MapQueryInfoPanel.svelte
  src/components/UNDPComponents/RasterLayer_UNDP.svelte
  src/components/control-groups/LayerNameGroup.svelte
  src/components/controls/RasterBandSelector.svelte
  src/lib/constants.ts
  src/lib/types/Layer.ts
  src/lib/types/RasterTileMetadata.ts
  src/lib/types/StacType.ts
  src/lib/types/TreeNode.ts
  src/lib/types/index.ts
  src/routes/+page.server.ts
  src/routes/stac/+server.ts
  src/routes/stac/mosaicjson/+server.ts
Labels: enhancement, frontend, backend

#695 added error handling and removed resampling in tilejson url
  lefthook.yml
  src/routes/stac/+server.ts
  src/routes/stac/mosaicjson/+server.ts
Labels: bug, backend

#696 created new endpoint to wrap azure blob endpoint
  src/components/BucketTreeItemRaster.svelte
  src/routes/stac/mosaicjson/+server.ts
  src/routes/stac/tilejson/+server.ts
Labels: bug, backend

#698 added mkdocs-video plugin
  documentation/Pipfile
  documentation/Pipfile.lock
  documentation/mkdocs.yml
Labels: documentation

#699 Fix/mosaicjson tilejson protocol
  lefthook.yml
  src/components/BucketTreeItemRaster.svelte
Labels: bug, frontend, backend

#700 added proper error handling for loading raster tile
  src/components/BucketTreeItemRaster.svelte
Labels: bug

#701 change colormap for mosaic
  src/components/BucketTreeItemRaster.svelte
  src/components/ColorMapPicker.svelte
  src/components/RasterLayer.svelte
  src/components/RasterMosaicLegendContainer.svelte
  src/routes/stac/mosaicjson/+server.ts
Labels: enhancement, frontend

#706 Feature/enable raster legend
  src/components/BucketTreeItemRaster.svelte
  src/components/IntervalsLegend.svelte
  src/components/RasterHistogram.svelte
  src/components/RasterLayer.svelte
  src/components/RasterLegendContainer.svelte
  src/components/RasterMosaicLegendContainer.svelte
Labels: enhancement, frontend

#709 Feature/mosaic layer query
  package.json
  pnpm-lock.yaml
  src/components/BucketTreeItemRaster.svelte
  src/components/MapQueryInfoPanel.svelte
Labels: bug

#710 fixed uniquevalue legend for mosaic
  src/components/BucketTreeBranch.svelte
  src/components/BucketTreeItemRaster.svelte
  src/components/RasterHistogram.svelte
  src/components/UniqueValuesLegend.svelte
  src/routes/stac/+server.ts
  src/routes/stac/mosaicjson/+server.ts
Labels: bug

#712 Refactor/create draw circle package
  lefthook.yml
  package.json
  packages/draw-circle/.eslintignore
  packages/draw-circle/.eslintrc.cjs
  packages/draw-circle/.gitignore
  packages/draw-circle/.npmrc
  packages/draw-circle/.prettierignore
  packages/draw-circle/.prettierrc
  packages/draw-circle/README.md
  packages/draw-circle/package.json
  packages/draw-circle/src/app.d.ts
  packages/draw-circle/src/app.html
  packages/draw-circle/src/example/components/Map.svelte
  packages/draw-circle/src/example/stores/index.ts
  packages/draw-circle/src/lib/DrawCircle.svelte
  packages/draw-circle/src/lib/index.ts
  packages/draw-circle/src/lib/stores.ts
  packages/draw-circle/src/routes/+page.svelte
  packages/draw-circle/src/routes/+page.ts
  packages/draw-circle/static/favicon.png
  packages/draw-circle/svelte.config.js
  packages/draw-circle/tsconfig.json
  packages/draw-circle/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  src/dashboards/components/OverlayControl.svelte
  src/dashboards/components/OverlayLegend1.svelte
  src/dashboards/components/OverlayLegend2.svelte
  src/dashboards/stores/index.ts
Labels: refactor

#716 Fix/layer info tool
  .prettierignore
  packages/draw-circle/src/example/components/Map.svelte
  packages/draw-circle/src/lib/DrawCircle.svelte
  packages/draw-circle/src/routes/+page.svelte
  src/components/BucketTreeItemCardButton.svelte
  src/components/control-groups/LayerControlGroup.svelte
  src/components/control-groups/LayerNameGroup.svelte
  src/lib/components/CurrentLocation.svelte
Labels: bug

#717 changed placement from right to right-start
  src/components/BucketTreeItemCardButton.svelte
Labels: bug

#721 change a link to div for add layer icon
  src/components/BucketTreeBranchIcon.svelte
  src/components/BucketTreeItemIcon.svelte
Labels: bug

#728 Fix/header height
  package.json
  pnpm-lock.yaml
  src/components/BucketView.svelte
  src/components/Content.svelte
  src/components/ContentSidebar.svelte
  src/components/Map.svelte
  src/routes/+page.svelte
Labels: bug

#730 Fix/issue 726
  src/components/BucketTreeItemCardButton.svelte
  src/components/BucketTreeItemLegend.svelte
  src/components/MapQueryInfoPanel.svelte
  src/components/control-groups/LayerNameGroup.svelte
  src/lib/constants.ts
Labels: bug

#732 Fix/issue 727
  src/components/BucketTreeBranch.svelte
  src/components/BucketTreeView.svelte
  src/components/TagsView.svelte
  src/routes/tags-search.json/+server.ts
Labels: bug

#734 Fix/contents layout
  src/components/BucketView.svelte
  src/components/Content.svelte
  src/components/ContentSidebar.svelte
  src/components/Tabs.svelte
  src/lib/components/CurrentLocation.svelte
Labels: bug

#735 added /vectorinfo/dynamic api
  .prettierignore
  sql/geohub.get_histogram.sql
  sql/geohub.get_vectorinfo.sql
  src/components/controls/AddLayerModal.svelte
  src/lib/helper/getVectorInfo.ts
  src/routes/vectorinfo/dynamic/+server.ts
  src/routes/vectorinfo/static/+server.ts
Labels: enhancement, backend

#737 feat: add pg_tileserv bucket
  .env.example
  .github/workflows/main_undpgeohub.yml
  data/dynamic.json
  data/martin.json
  data/mosaic-stac.json
  src/components/BucketCard.svelte
  src/components/BucketTreeBranch.svelte
  src/components/BucketTreeItemCardButton.svelte
  src/components/BucketTreeItemVector.svelte
  src/components/BucketView.svelte
  src/components/control-groups/LayerNameGroup.svelte
  src/components/controls/AddLayerModal.svelte
  src/components/controls/VectorLineContainer.svelte
  src/components/controls/VectorPolygonContainer.svelte
  src/components/controls/vector-styles/PropertySelect.svelte
  src/lib/helper/getLayerNumberProperties.ts
  src/lib/helper/getVectorInfo.ts
  src/lib/helper/index.ts
  src/lib/types/PgtileservDetailJson.ts
  src/lib/types/PgtileservIndexJson.ts
  src/lib/types/TileJson.ts
  src/lib/types/TreeNode.ts
  src/lib/types/index.ts
  src/lib/variables/public.ts
  src/routes/+page.server.ts
  src/routes/martin/+server.ts
  src/routes/pgtileserv/+server.ts
  src/routes/pgtileserv/[type]/[table]/tile.json/+server.ts
  src/routes/vectorinfo/static/+server.ts
  static/stac.png
Labels: enhancement

#740 created /martin/[table]/tile.json to share the same source code with pgtileserv in frontend
  src/components/BucketTreeItemCardButton.svelte
  src/components/BucketTreeItemVector.svelte
  src/components/controls/AddLayerModal.svelte
  src/lib/helper/getLayerNumberProperties.ts
  src/routes/martin/+server.ts
  src/routes/martin/[table]/tile.json/+server.ts
Labels: refactor

#741 Refactor/style switcher
  src/lib/aerialstyle.json
  src/lib/components/StyleSwitcher.svelte
  src/lib/style.json
Labels: refactor

#747 removed martinIndex from stores now. it is no longer necessary
  src/components/BucketTreeItemVector.svelte
  src/components/Content.svelte
  src/routes/vectorinfo/static/+server.ts
  src/stores/index.ts
Labels: refactor

#751 Fix/issue 748
  src/lib/constants.ts
  src/routes/azstorage.json/+server.ts
  src/routes/stac/mosaicjson/+server.ts
  src/routes/tags-search.json/+server.ts
Labels: enhancement, backend

#753 Fix/issue 752: disable bucket card button when share dialog is shown
  src/components/BucketView.svelte
  src/components/StyleShare.svelte
Labels: bug, frontend

#756 reverted main_undpgeohub.yml
  .github/workflows/main_undpgeohub.yml
Labels: bug
