Repository UNDP-Data/geohub, pull requests merged in 2023-03, with the labels that each got.

#1443 refactor: data upload
  sites/geohub/src/components/data-upload/DataUploadButton.svelte
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
  sites/geohub/src/routes/data/+layout.svelte
  sites/geohub/src/routes/data/+page.svelte
Labels: refactor

#1445 fix: deleted PUBLIC_AZURE_BLOB_TOKEN from electricity dashboard and to use /datasets api
  .changeset/slimy-buttons-appear.md
  .github/workflows/docker-image.yml
  .github/workflows/main_undpgeohub.yml
  .github/workflows/release.yml
  apps/electricity-dashboard/.env.example
  apps/electricity-dashboard/README.md
  apps/electricity-dashboard/package.json
  apps/electricity-dashboard/src/lib/components/Charts.svelte
  apps/electricity-dashboard/src/lib/components/TimeSlider.svelte
  apps/electricity-dashboard/src/lib/constansts.ts
  apps/electricity-dashboard/src/lib/index.ts
  apps/electricity-dashboard/src/lib/interfaces/Dataset.ts
  apps/electricity-dashboard/src/lib/interfaces/ElectricityDatasets.ts
  apps/electricity-dashboard/src/lib/interfaces/index.ts
  apps/electricity-dashboard/src/lib/stores/index.ts
  apps/electricity-dashboard/src/lib/utils/getBase64EncodedUrl.ts
  apps/electricity-dashboard/src/routes/+page.server.ts
  apps/electricity-dashboard/vite.config.js
  package.json
  pnpm-lock.yaml
  sites/geohub/.env.example
  sites/geohub/src/routes/dashboards/electricity/+page.server.ts
Labels: bug

#1451 fix: added license info in DataCardInfo
  sites/geohub/src/components/data-view/DataCardInfo.svelte
Labels: enhancement

#1454 fix: changed from +page.server.ts to +page.ts to load datasets in electricity dashboard
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/routes/dashboards/electricity/+page.server.ts
  sites/geohub/src/routes/dashboards/electricity/+page.ts
Labels: bug

#1456 fix: bug of resetting offset to 0 when the reload browser in /maps and /data page
  .changeset/kind-cats-compete.md
  packages/svelte-undp-design/.storybook/preview-head.html
  packages/svelte-undp-design/src/lib/Radios/Radios.svelte
  sites/geohub/src/components/AccessLevelSwitcher.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
  sites/geohub/src/components/maps/MapStyleCardList.svelte
  sites/geohub/src/routes/data/+page.server.ts
  sites/geohub/src/routes/maps/+page.server.ts
Labels: bug

#1458 feat: added download button in ingesting datasets table
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
Labels: enhancement

#1459 feat: add preview in /data page and /data/publish
  .changeset/quick-mice-reflect.md
  packages/svelte-undp-design/src/lib/Radios/Radios.svelte
  sites/geohub/src/components/data-upload/DataPreview.svelte
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/lib/types/DatasetFeature.ts
  sites/geohub/src/lib/types/IngestingDataset.ts
  sites/geohub/src/routes/api/datasets/ingesting/+server.ts
  sites/geohub/src/routes/data/publish/+page.server.ts
  sites/geohub/src/routes/data/publish/+page.svelte
Labels: enhancement

#1461 feat: add confirmation of deleting dataset by typing name
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
Labels: enhancement

#1463 fix: fixed mosaicjson api bug and improved tag filter
  sites/geohub/src/components/controls/PanelButton.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
  sites/geohub/src/components/data-view/AddLayerButton.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/routes/api/stac/mosaicjson/+server.ts
Labels: bug, enhancement

#1464 feat: added /api/swagger/spec.json endpoint
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/routes/api/swagger/spec.json/+server.ts
  sites/geohub/static/api/docs/swagger-initializer.js
  sites/geohub/static/api/swagger/spec.yaml
Labels: enhancement

#1465 fix: added +page.svelte with swagger-ui-dist
  .dockerignore
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/routes/api/+page.svelte
  sites/geohub/src/routes/api/+page.ts
  sites/geohub/static/api/docs/favicon-16x16.png
  sites/geohub/static/api/docs/favicon-32x32.png
  sites/geohub/static/api/docs/index.css
  sites/geohub/static/api/docs/index.html
  sites/geohub/static/api/docs/oauth2-redirect.html
  sites/geohub/static/api/docs/swagger-initializer.js
  sites/geohub/static/api/docs/swagger-ui-bundle.js
  sites/geohub/static/api/docs/swagger-ui-bundle.js.map
  sites/geohub/static/api/docs/swagger-ui-es-bundle-core.js
  sites/geohub/static/api/docs/swagger-ui-es-bundle-core.js.map
  sites/geohub/static/api/docs/swagger-ui-es-bundle.js
  sites/geohub/static/api/docs/swagger-ui-es-bundle.js.map
  sites/geohub/static/api/docs/swagger-ui-standalone-preset.js
  sites/geohub/static/api/docs/swagger-ui-standalone-preset.js.map
  sites/geohub/static/api/docs/swagger-ui.css
  sites/geohub/static/api/docs/swagger-ui.css.map
  sites/geohub/static/api/docs/swagger-ui.js
  sites/geohub/static/api/docs/swagger-ui.js.map
  sites/geohub/static/api/swagger/spec.yaml
Labels: bug

#1466 doc: added security in swagger yaml
  sites/geohub/static/api/swagger/spec.yaml
Labels: documentation

#1467 fix: disabled preview button if the original file is not pmtiles because we are not sure whether it is cloud optimised
  sites/geohub/src/components/data-upload/DataPreview.svelte
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
Labels: bug

#1468 feat: migrate bannerMessage component to svelte-toast package
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/App.svelte
  sites/geohub/src/components/BannerMessageControl.svelte
  sites/geohub/src/components/SplitterControl.svelte
  sites/geohub/src/components/control-groups/Step.svelte
  sites/geohub/src/components/controls/VectorFilter.svelte
  sites/geohub/src/components/data-view/DataStacAssetCard.svelte
  sites/geohub/src/components/data-view/DataVectorCard.svelte
  sites/geohub/src/components/data-view/Star.svelte
  sites/geohub/src/lib/MosaicJsonData.ts
  sites/geohub/src/lib/_tests__/Helper.test.ts
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/helper/fetchUrl.ts
  sites/geohub/src/lib/helper/fetchWithTimeout.ts
  sites/geohub/src/lib/types/BannerMessage.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/+layout.svelte
  sites/geohub/src/routes/api/stac/mosaicjson/+server.ts
  sites/geohub/src/routes/data/publish/+page.svelte
  sites/geohub/src/routes/data/upload/+page.svelte
  sites/geohub/src/stores/index.ts
Labels: bug, enhancement

#1469 fix: changed the position of unit to the bottom of slider
  sites/geohub/src/components/controls/RasterDefaultLegend.svelte
Labels: bug

#1472 fix: data upload bug
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
  sites/geohub/src/routes/api/datasets/[id]/+server.ts
Labels: bug

#1474 feat: added editor for raster settings
  sites/geohub/src/components/controls/RasterLegend.svelte
  sites/geohub/src/components/controls/RasterPropertyEditor.svelte
  sites/geohub/src/components/controls/raster-styles/RasterBrightnessMax.svelte
  sites/geohub/src/components/controls/raster-styles/RasterBrightnessMin.svelte
  sites/geohub/src/components/controls/raster-styles/RasterContrast.svelte
  sites/geohub/src/components/controls/raster-styles/RasterHueRotate.svelte
  sites/geohub/src/components/controls/raster-styles/RasterResampling.svelte
  sites/geohub/src/components/controls/raster-styles/RasterSaturation.svelte
  sites/geohub/src/components/controls/raster-styles/Slider.svelte
  sites/geohub/src/components/controls/raster-styles/ToggleOptions.svelte
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/types/ToggleOption.ts
  sites/geohub/src/lib/types/index.ts
Labels: enhancement

#1480 fix: set nearest for resampling of mosaicjson as default, and delete help from raster property editor to make it compact
  sites/geohub/src/components/controls/RasterPropertyEditor.svelte
  sites/geohub/src/lib/MosaicJsonData.ts
Labels: bug

#1482 fix: 1470 migrate unit
  .changeset/curvy-suits-happen.md
  .changeset/smooth-books-accept.md
  packages/geohub-cli/package.json
  packages/geohub-cli/src/cli/cog-unit-update.ts
  packages/geohub-cli/src/cli/index.ts
  packages/geohub-cli/src/interfaces/DatasetFeature.ts
  packages/geohub-cli/src/interfaces/DatasetFeatureCollection.ts
  packages/geohub-cli/src/interfaces/index.ts
  packages/geohub-cli/src/util/PgtileservManager.ts
  packages/geohub-cli/src/util/Tags.ts
  pnpm-lock.yaml
Labels: bug

#1485 fix: bug of unit in data publish page
  sites/geohub/src/components/data-upload/TagInput.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/routes/data/publish/+page.svelte
Labels: bug

#1486 fix: added file name validation in upload page
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/routes/data/upload/+page.svelte
Labels: bug

#1487 fix: added space, &, % for file name validation
  sites/geohub/src/routes/data/upload/+page.svelte
Labels: bug

#1488 fix: deleted PUBLIC_AZURE_URL from .env
  .changeset/tall-houses-march.md
  .github/workflows/docker-image.yml
  .github/workflows/main_undpgeohub.yml
  .github/workflows/release.yml
  apps/electricity-dashboard/.env.example
  apps/electricity-dashboard/README.md
  apps/electricity-dashboard/src/lib/components/Content.svelte
  apps/electricity-dashboard/src/lib/components/Map.svelte
  apps/electricity-dashboard/src/lib/components/OverlayControl.svelte
  apps/electricity-dashboard/src/lib/components/TimeSlider.svelte
  apps/electricity-dashboard/src/lib/utils/adminLayer.ts
  apps/electricity-dashboard/src/routes/+page.server.ts
  packages/current-location/.env.example
  packages/current-location/README.md
  packages/current-location/package.json
  packages/current-location/src/example/Map.svelte
  packages/current-location/src/lib/AdminLayer.ts
  packages/current-location/src/lib/CurrentLocation.svelte
  packages/current-location/src/routes/+page.server.ts
  packages/style-viewer/.env.example
  packages/style-viewer/README.md
  packages/style-viewer/package.json
  packages/style-viewer/src/lib/StyleViewer.svelte
  packages/style-viewer/src/routes/+page.server.ts
  packages/style-viewer/src/routes/+page.svelte
  pnpm-lock.yaml
  sites/geohub/.env.example
  sites/geohub/src/routes/+layout.server.ts
Labels: refactor

#1494 fix: use tag for unit instead of using from band metadata
  sites/geohub/src/components/controls/RasterDefaultLegend.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
Labels: bug

#1500 refactor: changed PUBLIC_TITILER_ENDPOINT TO private variable of TITILER_ENDPOINT
  .changeset/tidy-rice-march.md
  .dockerignore
  .github/workflows/docker-image.yml
  .github/workflows/main_undpgeohub.yml
  .github/workflows/release.yml
  Dockerfile
  apps/electricity-dashboard/.env.example
  apps/electricity-dashboard/README.md
  apps/electricity-dashboard/src/lib/components/Charts.svelte
  apps/electricity-dashboard/src/lib/components/TimeSlider.svelte
  apps/electricity-dashboard/src/routes/+page.server.ts
  docker-build.sh
  docker-run.sh
  sites/geohub/.env.example
  sites/geohub/src/components/MapQueryInfoControl.svelte
  sites/geohub/src/components/controls/RasterHistogram.svelte
  sites/geohub/src/components/controls/RasterLegend.svelte
  sites/geohub/src/components/controls/RasterTransformAdvanced.svelte
  sites/geohub/src/components/controls/RasterTransformSimple.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataStacAssetCard.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/lib/MosaicJsonData.ts
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/server/helpers/getRasterMetadata.ts
  sites/geohub/src/routes/+layout.server.ts
  sites/geohub/src/routes/api/stac/mosaicjson/+server.ts
Labels: refactor

#1508 doc: updated readme
  README.md
Labels: documentation

#1513 fix:slider cursor bounce
  sites/geohub/src/components/controls/VectorParamsPanel.svelte
Labels: bug

#1516 fix: bug of ingesting api. now it can detect all ingested datasets
  sites/geohub/src/lib/types/TileJson.ts
  sites/geohub/src/routes/api/datasets/ingesting/+server.ts
Labels: bug

#1509 test: added FillColor component test
  pnpm-lock.yaml
  sites/geohub/setupTest.ts
  sites/geohub/src/components/controls/vector-styles/FillColor.test.ts
  sites/geohub/src/components/controls/vector-styles/MaplibreColorPicker.svelte
  sites/geohub/src/lib/types/Layer.ts
  sites/geohub/vite.config.ts
Labels: test

#1518 fix: switch bands in raster layer
  sites/geohub/src/components/controls/RasterBandSelector.svelte
Labels: bug

#1520 feat: add new package for UNDP bulma style
  Dockerfile
  README.md
  packages/undp-bulma/.gitignore
  packages/undp-bulma/README.md
  packages/undp-bulma/bulma.scss
  packages/undp-bulma/index.html
  packages/undp-bulma/package.json
  packages/undp-bulma/src/main.ts
  packages/undp-bulma/src/vite-env.d.ts
  packages/undp-bulma/tsconfig.json
  packages/undp-bulma/vite.config.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
  sites/geohub/package.json
  sites/geohub/src/components/controls/VectorParamsPanel.svelte
  sites/geohub/src/routes/+error.svelte
  sites/geohub/src/routes/+layout.svelte
  sites/geohub/src/routes/+page.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/routes/data/+layout.svelte
  sites/geohub/src/routes/maps/+page.svelte
Labels: enhancement

#1522 feat: page streaming
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataCategoryCardList.svelte
  sites/geohub/src/routes/+page.server.ts
Labels: enhancement

#1524 fix: checkbox selecting in layer order panel
  sites/geohub/src/components/LayerList.svelte
  sites/geohub/src/components/layer-order/LegendPanel.svelte
Labels: bug

#1530 fix: set defaultcolor value (transparent color) for interval/categorical expression
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
Labels: bug

#1532 fix: set default iconSize and lineWidth to zero for classify legend.
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
Labels: bug

#1528 fix: Use streaming for tag filter, moved code of searching sdg sub goal to DataView, fixed several behaviour around data tab's search
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
  sites/geohub/src/components/data-view/DataCategoryCardList.svelte
  sites/geohub/src/components/data-view/SelectedTags.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/lib/config/DefaultUserConfig/DatasetSearchLimit.ts
  sites/geohub/src/routes/+page.server.ts
  sites/geohub/src/routes/data/+page.server.ts
  sites/geohub/src/routes/data/+page.svelte
Labels: bug

#1539 feat: add data link
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/lib/config/AppConfig/FooterItems.ts
  sites/geohub/src/lib/config/AppConfig/HeaderItems.ts
  sites/geohub/src/routes/data/+page.svelte
  sites/geohub/src/routes/maps/+page.svelte
  sites/geohub/src/routes/settings/+page.svelte
Labels: enhancement

#1541 fix: use streaming for saved style
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/LayerList.svelte
  sites/geohub/src/components/StyleShare.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/lib/types/SavedMapStyle.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/+page.server.ts
Labels: bug

#1542 fix: use uniquevalue legend if value is only one
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
  sites/geohub/src/lib/helper/getIntervalList.ts
Labels: bug

#1545 feat: added Makefile
  Makefile
Labels: enhancement

#1547 refactor: move breadcrumbs to backend
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
  sites/geohub/src/components/data-view/DataCategoryCardList.svelte
  sites/geohub/src/components/data-view/SelectedTags.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/lib/config/AppConfig/DatasetSearchQueryParams.ts
  sites/geohub/src/routes/+page.server.ts
Labels: refactor

#1548 doc: add admin api to swagger
  sites/geohub/src/components/data-upload/CountryPicker.svelte
  sites/geohub/src/routes/api/continents/+server.ts
  sites/geohub/src/routes/api/countries/+server.ts
  sites/geohub/src/routes/api/regions/+server.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: bug, documentation, enhancement

#1526 [FEAT] Store User Settings in Database
  packages/geohub-cli/docs/database.vuerd.json
  packages/geohub-cli/docs/geohub-database-erd.png
  packages/geohub-cli/docs/geohub-database.sql
  sites/geohub/src/components/Settings.svelte
  sites/geohub/src/lib/config/AppConfig/SidebarPositions.ts
  sites/geohub/src/lib/config/AppConfig/index.ts
  sites/geohub/src/lib/config/DefaultUserConfig/SidebarPosition.ts
  sites/geohub/src/lib/config/DefaultUserConfig/index.ts
  sites/geohub/src/routes/+layout.server.ts
  sites/geohub/src/routes/api/regions/+server.ts
  sites/geohub/src/routes/api/settings/+server.ts
  sites/geohub/src/routes/settings/+page.server.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: enhancement, work in progress, backend

#1549 feat: add country shortcut
  .changeset/afraid-owls-compete.md
  packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.stories.ts
  packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.svelte
  pnpm-lock.yaml
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/DataCategoryCard.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/lib/config/AppConfig/DataCategories.ts
  sites/geohub/src/lib/config/AppConfig/TagSearchKeys.ts
  sites/geohub/src/routes/+layout.svelte
  sites/geohub/src/routes/+page.server.ts
Labels: enhancement

#1552 fix: form action and improve styles
  sites/geohub/src/components/Settings.svelte
Labels: bug, frontend

#1561 fix: disabled commands for azblob, pgtileserv and cogunit
  .changeset/slow-gorillas-decide.md
  packages/geohub-cli/README.md
  packages/geohub-cli/src/cli/index.ts
Labels: bug

#1556 feat: enabled to edit/register pgtileserv layer if user is superuser
  sites/geohub/src/components/data-upload/DataPreview.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/routes/data/publish/+page.server.ts
  sites/geohub/src/routes/data/publish/+page.svelte
Labels: enhancement

#1563 fix: reflect sidebar position
  sites/geohub/src/components/App.svelte
  sites/geohub/src/components/Settings.svelte
  sites/geohub/src/components/SplitterControl.svelte
Labels: bug

#1567 feat: render rgb tile if layer has red, green, blue colorinterp
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/controls/RasterBandSelector.svelte
  sites/geohub/src/components/controls/RasterLegend.svelte
  sites/geohub/src/components/data-upload/DataPreview.svelte
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/lib/helper/isRasterExtension.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/lib/types/RasterTileMetadata.ts
  sites/geohub/src/routes/data/publish/+page.server.ts
Labels: enhancement

#1574 fix: bug of deleting tag in publish page
  sites/geohub/src/components/data-upload/TagInput.svelte
  sites/geohub/src/components/data-upload/Tags.svelte
  sites/geohub/src/routes/data/publish/+page.svelte
Labels: bug

#1573 Fix: layout in settings page
  sites/geohub/src/routes/settings/+page.svelte
Labels: bug, frontend

#1575 feat: implemented new country selector
  sites/geohub/src/components/data-upload/CountryPicker.svelte
  sites/geohub/src/routes/data/+layout.svelte
  sites/geohub/src/routes/data/publish/+page.server.ts
  sites/geohub/src/routes/data/publish/+page.svelte
Labels: enhancement

#1576 refactor: added missing types
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/Settings.svelte
  sites/geohub/src/components/SplitterControl.svelte
  sites/geohub/src/components/Tags.svelte
  sites/geohub/src/components/UserAccount.svelte
  sites/geohub/src/components/control-groups/Step.svelte
  sites/geohub/src/components/control-groups/Wizard.svelte
  sites/geohub/src/components/controls/LegendColorMapRow.svelte
  sites/geohub/src/components/controls/Modal.svelte
  sites/geohub/src/components/controls/Notification.svelte
  sites/geohub/src/components/controls/RasterClassifyLegend.svelte
  sites/geohub/src/components/controls/RasterDefaultLegend.svelte
  sites/geohub/src/components/controls/RasterHistogram.svelte
  sites/geohub/src/components/controls/VectorFilter.svelte
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/VectorParamsPanel.svelte
  sites/geohub/src/components/controls/vector-styles/HeatmapColorRow.svelte
  sites/geohub/src/components/controls/vector-styles/PropertySelect.svelte
  sites/geohub/src/components/controls/vector-styles/PropertySelectButtons.svelte
  sites/geohub/src/components/controls/vector-styles/TextField.svelte
  sites/geohub/src/components/controls/vector-styles/ValueInput.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/Star.svelte
  sites/geohub/src/lib/types/Color.ts
  sites/geohub/src/lib/types/RangeSliderConfig.ts
  sites/geohub/src/lib/types/SidebarPosition.ts
  sites/geohub/src/lib/types/index.ts
Labels: refactor

#1577 refactor: enhance help text for `DataView`, `RasterLegend`, `VectorLegend`
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/controls/RasterLegend.svelte
  sites/geohub/src/components/controls/VectorLegend.svelte
Labels: refactor

#1578 fix: country picker
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-upload/CountryPicker.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/lib/config/AppConfig/TagInputValues.ts
  sites/geohub/src/lib/config/AppConfig/TagSearchKeys.ts
  sites/geohub/src/routes/+page.server.ts
  sites/geohub/src/routes/data/publish/+page.svelte
Labels: bug

#1579 Fix/multi select regions
  sites/geohub/src/components/data-upload/CountryPicker.svelte
  sites/geohub/src/routes/data/publish/+page.svelte
Labels: bug

#1581 Fix/bug new registration
  sites/geohub/src/components/data-view/DataCardInfo.svelte
  sites/geohub/src/routes/data/publish/+page.server.ts
  sites/geohub/src/routes/data/publish/+page.svelte
Labels: bug

#1584 Refactor/numberinput to rangeslider
  sites/geohub/src/components/Settings.svelte
Labels: refactor

#1583 doc: added some sequence diagrams in readme
  README.md
Labels: documentation

#1585 feat: add other un agencies
  sites/geohub/src/components/data-view/DataCategoryCard.svelte
  sites/geohub/src/lib/config/AppConfig/DataCategories.ts
  sites/geohub/static/assets/fao.svg
  sites/geohub/static/assets/undp-images/undp-logo.png
  sites/geohub/static/assets/unep.png
  sites/geohub/static/assets/unicef.png
  sites/geohub/static/assets/wfp.svg
Labels: enhancement

#1588 feat: add help in settings
  sites/geohub/src/components/Help.svelte
  sites/geohub/src/components/Settings.svelte
  sites/geohub/src/components/controls/FieldControl.svelte
  sites/geohub/src/components/controls/FieldControl.test.ts
  sites/geohub/src/routes/settings/+page.svelte
Labels: enhancement

#1599 fix: loader style
  sites/geohub/src/components/StyleShare.svelte
  sites/geohub/src/components/data-upload/CountryPicker.svelte
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/components/data-view/AddLayerButton.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/routes/data/publish/+page.svelte
Labels: bug

#1604 fix: disable settings
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/UserAccount.svelte
  sites/geohub/src/routes/+error.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/routes/maps/+page.svelte
  sites/geohub/src/routes/settings/+page.server.ts
Labels: bug

#1608 feat: settings enhancement
  sites/geohub/src/components/Settings.svelte
  sites/geohub/src/routes/settings/+page.svelte
Labels: enhancement

#1609 doc: added data issue report
  .github/ISSUE_TEMPLATE/data_issue.yml
Labels: documentation

#1621 feat: add more settings extension
  Dockerfile
  sites/geohub/src/components/Settings.svelte
  sites/geohub/src/components/SplitterControl.svelte
  sites/geohub/src/components/UserAccount.svelte
  sites/geohub/src/components/controls/ColorMapPickerCard.test.ts
  sites/geohub/src/components/controls/RasterClassifyLegend.svelte
  sites/geohub/src/components/controls/RasterOpCat.svelte
  sites/geohub/src/components/controls/RasterTransformAdvanced.svelte
  sites/geohub/src/components/controls/RasterTransformNumbersInput.svelte
  sites/geohub/src/components/controls/RasterTransformSimple.svelte
  sites/geohub/src/components/controls/VectorFilter.svelte
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/VectorParamsPanel.svelte
  sites/geohub/src/components/controls/raster-styles/RasterResampling.svelte
  sites/geohub/src/components/controls/vector-styles/IconImage.svelte
  sites/geohub/src/components/controls/vector-styles/IconImagePickerCard.svelte
  sites/geohub/src/components/controls/vector-styles/IconImagePickerCard.test.ts
  sites/geohub/src/components/controls/vector-styles/IconSize.svelte
  sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
  sites/geohub/src/components/controls/vector-styles/OperationButtons.svelte
  sites/geohub/src/components/controls/vector-styles/PropertySelectButtons.svelte
  sites/geohub/src/components/controls/vector-styles/ValueInput.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataVectorCard.svelte
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/VectorTileData.ts
  sites/geohub/src/lib/config/AppConfig/ClassificationMethods.ts
  sites/geohub/src/lib/config/AppConfig/IconOverlapPriority.ts
  sites/geohub/src/lib/config/AppConfig/RasterResamplingMethods.ts
  sites/geohub/src/lib/config/AppConfig/index.ts
  sites/geohub/src/lib/config/DefaultUserConfig/ClassificationMethod.ts
  sites/geohub/src/lib/config/DefaultUserConfig/IconImage.ts
  sites/geohub/src/lib/config/DefaultUserConfig/IconOverlapPriority.ts
  sites/geohub/src/lib/config/DefaultUserConfig/IconSize.ts
  sites/geohub/src/lib/config/DefaultUserConfig/LabelFontSize.ts
  sites/geohub/src/lib/config/DefaultUserConfig/LabelHaloWidth.ts
  sites/geohub/src/lib/config/DefaultUserConfig/LayerOpacity.ts
  sites/geohub/src/lib/config/DefaultUserConfig/LinePattern.ts
  sites/geohub/src/lib/config/DefaultUserConfig/RasterResamplingMethod.ts
  sites/geohub/src/lib/config/DefaultUserConfig/index.ts
  sites/geohub/src/lib/types/MapsData.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/data/publish/+page.svelte
  sites/geohub/static/api/swagger/spec.yaml
Labels: enhancement, frontend
