Repository UNDP-Data/geohub, pull requests merged in 2023-02, with the labels that each got.

#1265 Fix: fire sourcechange event
  sites/geohub/src/components/controls/vector-styles/Legend.svelte
  sites/geohub/src/lib/helper/updateParamsInURL.ts
Labels: bug

#1268 fix: #1267 color picker
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/__tests__/ColorMapPickerCard.test.ts
  sites/geohub/src/components/controls/ColorPicker.svelte
  sites/geohub/src/components/controls/LegendColorMapRow.svelte
  sites/geohub/src/components/controls/RasterClassifyLegend.svelte
  sites/geohub/src/components/controls/RasterLegend.svelte
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
  sites/geohub/src/components/controls/vector-styles/MaplibreColorPicker.svelte
  sites/geohub/src/lib/helper/generateColorMap.ts
  sites/geohub/src/lib/helper/getMaxValueOfCharsInIntervals.ts
  sites/geohub/src/lib/helper/updateIntervalValues.ts
  sites/geohub/src/lib/types/Color.ts
  sites/geohub/src/lib/types/ColorMapRow.ts
  sites/geohub/src/lib/types/UniqueLegendColorMapRow.ts
  sites/geohub/src/lib/types/index.ts
Labels: bug

#1270 fix: adjust colormapbutton position
  package.json
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/RasterClassifyLegend.svelte
  sites/geohub/src/components/controls/RasterDefaultLegend.svelte
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
  sites/geohub/src/components/controls/vector-styles/Legend.svelte
  sites/geohub/src/lib/types/BandMetadata.ts
  sites/geohub/src/styles/geohubstyle.scss
Labels: bug, enhancement

#1271 fix: when selected property is number field, sort stops
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
Labels: bug

#1272 fix: keep random sample values same in order to compute same results for natural breaks and quantile
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
Labels: bug

#1281 feat: redesign line symbol legend
  sites/geohub/src/components/__tests__/IconImagePickerCard.test.ts
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
  sites/geohub/src/components/controls/VectorLine.svelte
  sites/geohub/src/components/controls/VectorSymbol.svelte
  sites/geohub/src/components/controls/vector-styles/IconImage.svelte
  sites/geohub/src/components/controls/vector-styles/IconImagePicker.svelte
  sites/geohub/src/components/controls/vector-styles/IconImagePickerCard.svelte
  sites/geohub/src/components/controls/vector-styles/IconOverlap.svelte
  sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
  sites/geohub/src/components/controls/vector-styles/LineWidth.svelte
Labels: bug, enhancement, refactor

#1282 fixed layout vector label and vector line in responsive
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/VectorLine.svelte
  sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
Labels: bug

#1284 fix: removed padding from vector line to adjust layout
  sites/geohub/src/components/controls/VectorLine.svelte
Labels: bug

#1286 Update2/2/23
  documentation/docs/assets/data/Map_Hide_layer_panel.png
  documentation/docs/dashboards/dashboard.md
  documentation/docs/dashboards/introduction.md
  documentation/docs/data/data_structure.md
  documentation/docs/data/introduction.md
  documentation/docs/data/special_buckets.md
  documentation/docs/index.md
  documentation/docs/visualization/header_features.md
  documentation/docs/visualization/map_view.md
  documentation/docs/visualization/search_data.md
  documentation/mkdocs.yml
Labels: documentation

#1285 enabled data tab in readonly mode, and set saved map name in head title
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/routes/+page.svelte
Labels: enhancement

#1287 capitalise and clean property text
  sites/geohub/src/components/controls/vector-styles/PropertySelect.svelte
Labels: bug

#1256 [WIP] Feat: Add parameters UI to be able to alter parameters for the HDI layer
  sites/geohub/src/components/MainApp.svelte
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/controls/VectorParamsPanel.svelte
  sites/geohub/src/components/controls/VectorParamsPanel1.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/helper/getLayerProperties.ts
  sites/geohub/src/lib/helper/updateParamsInURL.ts
Labels: enhancement, frontend

#1291 fix: revert minPrimaryWidth to 360px
  sites/geohub/src/components/MainApp.svelte
Labels: bug

#1293 fix: forgot to change URL of saved map in /style api
  sites/geohub/src/routes/api/style/+server.ts
Labels: bug

#1294 fix: set metadata title for each page
  sites/geohub/src/app.html
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/routes/+page.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/routes/dashboards/electricity/+page.svelte
  sites/geohub/src/routes/maps/+page.svelte
Labels: bug

#1296 feat: fixes #1278 to enalbe save as new map
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/StyleShare.svelte
Labels: enhancement

#1300 Vector analytics panel
  sites/geohub/src/components/MainApp.svelte
  sites/geohub/src/components/controls/VectorParamsPanel1.svelte
Labels: enhancement, frontend

#1298 fix: make progress bar smaller
  .changeset/chilly-timers-search.md
  .changeset/heavy-dolphins-sleep.md
  .changeset/ten-jokes-sell.md
  packages/svelte-undp-design/src/lib/Header/Header.stories.ts
  packages/svelte-undp-design/src/lib/Header/Header.svelte
  sites/geohub/src/components/Header.svelte
Labels: bug

#1303 change icon and styles for selected parameters
  sites/geohub/src/components/controls/VectorParamsPanel1.svelte
Labels: enhancement

#1302 feat: favourite feature
  .changeset/ten-apes-flow.md
  packages/geohub-cli/docs/database.vuerd.json
  packages/geohub-cli/docs/geohub-database-erd.png
  packages/geohub-cli/docs/geohub-database.sql
  packages/geohub-cli/src/util/Datasets.ts
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
  sites/geohub/src/components/data-view/DataVectorCard.svelte
  sites/geohub/src/components/data-view/Star.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/server/helpers/createDatasetSearchWhereExpression.ts
  sites/geohub/src/lib/types/DataSortingColumn.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/star/+server.ts
  sites/geohub/src/routes/api/tags/+server.ts
  sites/geohub/static/api/docs/swagger.yaml
  sites/geohub/static/assets/star.png
Labels: enhancement

#1304 fix bug #1290 that displayed simulation tab for all layers
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/controls/VectorParamsPanel.svelte
  sites/geohub/src/components/controls/VectorParamsPanel1.svelte
  sites/geohub/src/lib/constants.ts
Labels: enhancement

#1307 Fix #1290
  sites/geohub/src/components/VectorLayer.svelte
Labels: bug

#1308 fix: #1305 show colormap in raster unique
  sites/geohub/src/components/controls/RasterClassifyLegend.svelte
  sites/geohub/src/components/controls/RasterDefaultLegend.svelte
Labels: bug

#1313 Feature/show star count
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/data-view/DataCardInfo.svelte
  sites/geohub/src/components/data-view/Star.svelte
  sites/geohub/src/lib/server/helpers/getStarCount.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/routes/api/datasets/[id]/star/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/star/count/+server.ts
  sites/geohub/static/api/docs/swagger.yaml
Labels: enhancement

#1314 removed turbo
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: enhancement

#1316 feat: 1315 enhance sort
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/types/DataOrderType.ts
  sites/geohub/src/lib/types/DataSortingColumn.ts
Labels: enhancement

#1318 feat: uncommented code to allow only an accordion to expand
  sites/geohub/src/components/DataView.svelte
Labels: enhancement

#1321 Fix: show unique value legend by default
  sites/geohub/src/components/LayerList.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataStacAssetCard.svelte
  sites/geohub/src/lib/MosaicJsonData.ts
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/helper/getRandomColormap.ts
  sites/geohub/src/lib/types/Layer.ts
Labels: refactor

#1331 fix: made line pattern width a bit narrower
  sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
Labels: bug

#1334 fix: preload vector metadata to make add layer button work well
  sites/geohub/src/components/data-view/DataCard.svelte
Labels: bug

#1336 Style improvements
  sites/geohub/src/components/UserAccount.svelte
Labels: refactor

#1337 fix: 1273 replace popper to tippyjs
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/ColorPicker.svelte
  sites/geohub/src/components/controls/DataCardInfoButton.svelte
  sites/geohub/src/components/controls/LegendColorMapRow.svelte
  sites/geohub/src/components/controls/PanelButton.svelte
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/vector-styles/HeatmapColorRow.svelte
  sites/geohub/src/components/controls/vector-styles/IconImage.svelte
  sites/geohub/src/components/controls/vector-styles/IconImagePicker.svelte
  sites/geohub/src/components/controls/vector-styles/MaplibreColorPicker.svelte
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/lib/helper/initTippy.ts
  sites/geohub/src/lib/popper.ts
  sites/geohub/src/styles/popper.scss
Labels: bug

#1341 fix: 1338 delete button
  sites/geohub/src/components/MainApp.svelte
  sites/geohub/src/components/control-groups/LayerNameGroup.svelte
  sites/geohub/src/components/controls/DeleteButton.svelte
  sites/geohub/src/styles/button-icons-selected.scss
Labels: bug

#1342 fix: add style for acordion to make it aligned when there is no button
  .changeset/tame-llamas-retire.md
  packages/svelte-undp-design/src/lib/Accordion/Accordion.svelte
Labels: bug, frontend

#1348 refactor: 1345 delete storage table
  .changeset/seven-zebras-hope.md
  packages/geohub-cli/README.md
  packages/geohub-cli/docs/database.vuerd.json
  packages/geohub-cli/docs/geohub-database-erd.png
  packages/geohub-cli/docs/geohub-database.sql
  packages/geohub-cli/src/cli/azblob.ts
  packages/geohub-cli/src/cli/deleteStorage.ts
  packages/geohub-cli/src/cli/index.ts
  packages/geohub-cli/src/cli/martin.ts
  packages/geohub-cli/src/cli/pgtileserv.ts
  packages/geohub-cli/src/cli/stac.ts
  packages/geohub-cli/src/helpers/distinct.ts
  packages/geohub-cli/src/helpers/index.ts
  packages/geohub-cli/src/interfaces/Dataset.ts
  packages/geohub-cli/src/interfaces/Storage.ts
  packages/geohub-cli/src/util/BlobServiceAccountManager.ts
  packages/geohub-cli/src/util/DatabaseManager.ts
  packages/geohub-cli/src/util/Datasets.ts
  packages/geohub-cli/src/util/MartinManager.ts
  packages/geohub-cli/src/util/PgtileservManager.ts
  packages/geohub-cli/src/util/StacManager.ts
  packages/geohub-cli/src/util/Storages.ts
  packages/geohub-cli/src/util/Tags.ts
  packages/geohub-cli/src/util/index.ts
  sites/geohub/src/lib/server/helpers/createDatasetSearchWhereExpression.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/storages/+server.ts
  sites/geohub/static/api/docs/swagger.yaml
Labels: backend, refactor

#1352 fix: to check type is pgtilerserv or martin before setting tile.json URL
  sites/geohub/src/lib/VectorTileData.ts
Labels: bug

#1358 feat: added layer type option for polygon layer
  sites/geohub/src/components/data-view/DataVectorCard.svelte
  sites/geohub/src/lib/VectorTileData.ts
Labels: enhancement

#1359 fixed not to syncronise line pattern legend color with line color
  sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
  sites/geohub/src/components/data-view/DataVectorCard.svelte
Labels: bug

#1360 fix: default tab on colormappicker is selected by current colormap name
  sites/geohub/src/components/controls/ColorMapPicker.svelte
Labels: bug

#1361 doc: added country table into database
  packages/geohub-cli/docs/database.vuerd.json
  packages/geohub-cli/docs/geohub-database-erd.png
  packages/geohub-cli/docs/geohub-database.sql
Labels: documentation

#1364 Feature/1363 move source to tag
  .changeset/red-tomatoes-admire.md
  packages/geohub-cli/docs/database.vuerd.json
  packages/geohub-cli/docs/geohub-database-erd.png
  packages/geohub-cli/docs/geohub-database.sql
  packages/geohub-cli/src/interfaces/Dataset.ts
  packages/geohub-cli/src/util/BlobServiceAccountManager.ts
  packages/geohub-cli/src/util/Datasets.ts
  packages/geohub-cli/src/util/MartinManager.ts
  packages/geohub-cli/src/util/PgtileservManager.ts
  packages/geohub-cli/src/util/StacManager.ts
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
  sites/geohub/src/components/data-view/DataCategoryCard.svelte
  sites/geohub/src/lib/MosaicJsonData.ts
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/helper/createAttributionFromTags.ts
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/static/api/docs/swagger.yaml
  sites/geohub/static/assets/undp-images/undp-logo.png
Labels: enhancement

#1344 feat: #957 data uploading
  .github/workflows/main_undpgeohub.yml
  .github/workflows/release.yml
  pnpm-lock.yaml
  sites/geohub/.env.example
  sites/geohub/package.json
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-upload/CountryCard.svelte
  sites/geohub/src/components/data-upload/CountryPicker.svelte
  sites/geohub/src/components/data-upload/DataProviderPicker.svelte
  sites/geohub/src/components/data-upload/SdgCard.svelte
  sites/geohub/src/components/data-upload/SdgPicker.svelte
  sites/geohub/src/components/data-upload/TagInput.svelte
  sites/geohub/src/components/data-upload/Tags.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
  sites/geohub/src/components/data-view/DataStacAssetCard.svelte
  sites/geohub/src/components/data-view/DataVectorCard.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/lib/MosaicJsonData.ts
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/VectorTileData.ts
  sites/geohub/src/lib/helper/getBulmaTagColor.ts
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/lib/server/helpers/generateAzureBlobSasToken.ts
  sites/geohub/src/lib/server/helpers/generateHashKey.ts
  sites/geohub/src/lib/server/helpers/getRasterMetadata.ts
  sites/geohub/src/lib/server/helpers/getVectorMetadata.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/lib/server/helpers/isRasterExtension.ts
  sites/geohub/src/lib/server/variables/private.ts
  sites/geohub/src/lib/types/Continent.ts
  sites/geohub/src/lib/types/Country.ts
  sites/geohub/src/lib/types/DatasetFeature.ts
  sites/geohub/src/lib/types/DatasetFeatureCollection.ts
  sites/geohub/src/lib/types/Layer.ts
  sites/geohub/src/lib/types/Region.ts
  sites/geohub/src/lib/types/Tag.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/api/continents/+server.ts
  sites/geohub/src/routes/api/countries/+server.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/+server.ts
  sites/geohub/src/routes/api/regions/+server.ts
  sites/geohub/src/routes/data/+layout.svelte
  sites/geohub/src/routes/data/publish/+page.server.ts
  sites/geohub/src/routes/data/publish/+page.svelte
  sites/geohub/src/routes/data/publish/+page.ts
  sites/geohub/src/routes/data/upload/+page.server.ts
  sites/geohub/src/routes/data/upload/+page.svelte
  sites/geohub/src/routes/data/upload/+page.ts
  sites/geohub/static/api/docs/swagger.yaml
Labels: enhancement

#1367 Fix/add pmtiles to devdependencies
  pnpm-lock.yaml
  sites/geohub/package.json
Labels: bug

#1368 Docsupdate16022023
  documentation/docs/assets/data/Search_settings.png
  documentation/docs/visualization/search_data.md
Labels: documentation

#1369 feat: added created_user and updated_user in dataset table
  .changeset/friendly-shrimps-relax.md
  packages/geohub-cli/docs/database.vuerd.json
  packages/geohub-cli/docs/geohub-database-erd.png
  packages/geohub-cli/docs/geohub-database.sql
  packages/geohub-cli/src/util/Datasets.ts
  sites/geohub/src/lib/types/DatasetFeature.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/+server.ts
  sites/geohub/static/api/docs/swagger.yaml
Labels: enhancement

#1371 added +page.ts under /data route
  sites/geohub/src/routes/data/+page.ts
Labels: bug

#1372 fix: not to move docs html to prerender folder in CI
  .github/workflows/main_undpgeohub.yml
Labels: bug

#1374 update storybook version from beta-12 to beta-48
  .changeset/great-bulldogs-clean.md
  package.json
  packages/svelte-undp-design/package.json
  pnpm-lock.yaml
Labels: bug

#1376 fixed bug of Download componenent. Also, deleted storybook from GeoHub's static folder
  .changeset/modern-pumas-peel.md
  .github/workflows/main_undpgeohub.yml
  packages/svelte-undp-design/.npmrc
  packages/svelte-undp-design/.storybook/main.cjs
  packages/svelte-undp-design/.storybook/main.ts
  packages/svelte-undp-design/.storybook/preview.ts
  packages/svelte-undp-design/package.json
  packages/svelte-undp-design/src/lib/Download/Download.svelte
  packages/svelte-undp-design/src/routes/+page.svelte
  packages/svelte-undp-design/src/routes/+page.ts
  packages/svelte-undp-design/svelte.config.js
  pnpm-lock.yaml
  sites/geohub/src/lib/constants.ts
Labels: bug, documentation

#1375 fix: some properties of string type are not shown in label tab
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/vector-styles/TextField.svelte
Labels: bug

#1377 feat: deploy storybook
  .github/workflows/deploy_storybook.yml
  .github/workflows/main_undpgeohub.yml
  sites/geohub/src/lib/constants.ts
Labels: documentation

#1378 doc: deploy mkdocs to azure blob container
  .github/workflows/deploy_userguide.yml
  .github/workflows/main_undpgeohub.yml
  documentation/mkdocs.yml
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/helper/createHeaderLinks.ts
  sites/geohub/src/routes/+error.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/routes/maps/+page.svelte
Labels: documentation

#1379 fixed Dockerfile to adpot latest code. removed prepare command for lefthook install
  .github/workflows/docker-image.yml
  CONTRIBUTING.md
  Dockerfile
  docker-compose.yml
  package.json
  pnpm-lock.yaml
Labels: enhancement

#1380 feat: add sql to update metadata
  pnpm-lock.yaml
  sites/geohub/src/components/data-upload/CountryPicker.svelte
  sites/geohub/src/components/data-upload/DataProviderPicker.svelte
  sites/geohub/src/lib/server/DatabaseManager.ts
  sites/geohub/src/lib/server/DatasetManager.ts
  sites/geohub/src/lib/server/TagManager.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/lib/server/helpers/upsertDataset.ts
  sites/geohub/src/lib/types/Tag.ts
  sites/geohub/src/routes/data/publish/+page.server.ts
  sites/geohub/src/routes/data/publish/+page.svelte
Labels: enhancement

#1381 fixed bug of Dockerfile entrypoint
  Dockerfile
Labels: bug

#1400 refactor: separate data loading from frontend to +page.server.ts
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/components/maps/MapStyleCardList.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/server/helpers/createDatasetSearchWhereExpression.ts
  sites/geohub/src/routes/data/+page.server.ts
  sites/geohub/src/routes/data/+page.svelte
  sites/geohub/src/routes/data/publish/+page.server.ts
  sites/geohub/src/routes/data/upload/+page.server.ts
  sites/geohub/src/routes/maps/+page.server.ts
  sites/geohub/static/api/docs/swagger.yaml
Labels: refactor

#1405 refactor: 1403: environmental variables
  .changeset/tender-bags-ring.md
  .github/workflows/docker-image.yml
  .github/workflows/main_undpgeohub.yml
  .github/workflows/release.yml
  Dockerfile
  apps/electricity-dashboard/.env.example
  packages/current-location/.env.example
  packages/current-location/src/lib/AdminLayer.ts
  packages/current-location/src/lib/CurrentLocation.svelte
  packages/current-location/tsconfig.json
  packages/style-viewer/.env.example
  sites/geohub/.env.example
  sites/geohub/src/components/Map.svelte
  sites/geohub/src/components/MapQueryInfoControl.svelte
  sites/geohub/src/components/controls/RasterHistogram.svelte
  sites/geohub/src/components/controls/RasterLegend.svelte
  sites/geohub/src/components/controls/RasterTransformAdvanced.svelte
  sites/geohub/src/components/controls/RasterTransformSimple.svelte
  sites/geohub/src/hooks.server.ts
  sites/geohub/src/lib/MosaicJsonData.ts
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/server/DatabaseManager.ts
  sites/geohub/src/lib/server/helpers/generateAzureBlobSasToken.ts
  sites/geohub/src/lib/server/helpers/getMapStats.ts
  sites/geohub/src/lib/server/helpers/getRasterMetadata.ts
  sites/geohub/src/lib/server/helpers/getStyleById.ts
  sites/geohub/src/lib/server/helpers/getStyleCount.ts
  sites/geohub/src/lib/server/variables/private.ts
  sites/geohub/src/lib/variables/public.ts
  sites/geohub/src/routes/api/continents/+server.ts
  sites/geohub/src/routes/api/countries/+server.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/star/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/star/count/+server.ts
  sites/geohub/src/routes/api/regions/+server.ts
  sites/geohub/src/routes/api/stac/mosaicjson/+server.ts
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/src/routes/api/style/[id].json/+server.ts
  sites/geohub/src/routes/api/style/[id]/+server.ts
  sites/geohub/src/routes/api/style/count/+server.ts
  sites/geohub/src/routes/api/tags/+server.ts
  sites/geohub/src/routes/api/vector/[source]/metadata.json/+server.ts
  sites/geohub/src/routes/api/vector/[source]/tile.json/+server.ts
  sites/geohub/src/routes/data/publish/+page.server.ts
  sites/geohub/src/routes/data/upload/+page.server.ts
Labels: refactor

#1408 refactor: add interface in svelte-undp-design's index.ts, and solved lint warnings
  .changeset/strong-toys-study.md
  packages/svelte-undp-design/src/lib/index.ts
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/RasterLegend.svelte
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
  sites/geohub/src/components/controls/VectorParamsPanel.svelte
  sites/geohub/src/components/controls/vector-styles/IconImagePicker.svelte
  sites/geohub/src/components/controls/vector-styles/Legend.svelte
  sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
  sites/geohub/src/components/controls/vector-styles/TextField.svelte
  sites/geohub/src/components/controls/vector-styles/ValueInput.svelte
  sites/geohub/src/components/data-upload/CountryPicker.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataCategoryCard.svelte
  sites/geohub/src/components/data-view/DataCategoryCardList.svelte
  sites/geohub/src/components/data-view/DataVectorCard.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/components/data-view/Star.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/components/layer-order/LegendPanel.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/helper/createHeaderLinks.ts
  sites/geohub/src/lib/helper/updateParamsInURL.ts
  sites/geohub/src/lib/server/helpers/getMapStats.ts
  sites/geohub/src/routes/+error.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/routes/data/+layout.svelte
  sites/geohub/src/routes/data/publish/+page.svelte
  sites/geohub/src/routes/data/upload/+page.svelte
  sites/geohub/src/routes/maps/+page.svelte
Labels: refactor

#1409 fix: moved getMe code to hooks.server.ts from +layout.server.ts
  sites/geohub/src/hooks.server.ts
  sites/geohub/src/lib/server/helpers/getMe.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/routes/+layout.server.ts
Labels: bug

#1410 feat: #1319 data tab query params
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/LayerList.svelte
  sites/geohub/src/components/controls/Notification.svelte
  sites/geohub/src/components/data-view/SelectedTags.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/lib/helper/getSelectedTagsFromUrl.ts
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/lib/types/LegendState.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/+page.server.ts
  sites/geohub/src/routes/api/tags/+server.ts
Labels: refactor

#1411 refactor: use database manager
  sites/geohub/src/lib/server/DatabaseManager.ts
  sites/geohub/src/lib/server/helpers/getMapStats.ts
  sites/geohub/src/lib/server/helpers/getStyleById.ts
  sites/geohub/src/lib/server/helpers/getStyleCount.ts
  sites/geohub/src/routes/api/continents/+server.ts
  sites/geohub/src/routes/api/countries/+server.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/star/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/star/count/+server.ts
  sites/geohub/src/routes/api/regions/+server.ts
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/src/routes/api/style/[id].json/+server.ts
  sites/geohub/src/routes/api/style/[id]/+server.ts
  sites/geohub/src/routes/api/style/count/+server.ts
  sites/geohub/src/routes/api/tags/+server.ts
Labels: refactor

#1414 feat: add dataset delete api
  sites/geohub/src/components/data-upload/DataProviderPicker.svelte
  sites/geohub/src/components/data-upload/TagInput.svelte
  sites/geohub/src/components/data-view/SelectedTags.svelte
  sites/geohub/src/lib/server/DatasetManager.ts
  sites/geohub/src/lib/server/helpers/getDatasetById.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/routes/api/datasets/[id]/+server.ts
  sites/geohub/src/routes/data/publish/+page.server.ts
  sites/geohub/src/routes/data/publish/+page.svelte
  sites/geohub/static/api/docs/swagger.yaml
Labels: bug, enhancement, backend

#1415 fix: env variable in data upload
  sites/geohub/src/routes/data/upload/+page.server.ts
Labels: bug

#1417 feat: add permission and superuser table
  .changeset/ten-trains-mix.md
  packages/geohub-cli/docs/database.vuerd.json
  packages/geohub-cli/docs/geohub-database-erd.png
  packages/geohub-cli/docs/geohub-database.sql
  packages/geohub-cli/src/util/Datasets.ts
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/server/DatasetManager.ts
  sites/geohub/src/lib/server/helpers/createDatasetSearchWhereExpression.ts
  sites/geohub/src/lib/server/helpers/getDatasetById.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/lib/server/helpers/isSuperuser.ts
  sites/geohub/src/lib/types/DatasetFeature.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/+server.ts
  sites/geohub/src/routes/api/tags/+server.ts
  sites/geohub/src/routes/data/+page.server.ts
  sites/geohub/src/routes/data/+page.svelte
  sites/geohub/src/routes/data/publish/+page.server.ts
  sites/geohub/src/styles/geohubstyle.scss
  sites/geohub/static/api/docs/swagger.yaml
Labels: enhancement

#1419 feat: changed accordion to table in data page
  sites/geohub/src/routes/data/+page.server.ts
  sites/geohub/src/routes/data/+page.svelte
Labels: enhancement

#1412 Feat/settings page
  sites/geohub/src/components/App.svelte
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/MainApp.svelte
  sites/geohub/src/components/Settings.svelte
  sites/geohub/src/components/SplitterControl.svelte
  sites/geohub/src/components/UserAccount.svelte
  sites/geohub/src/components/controls/Notification.svelte
  sites/geohub/src/routes/+page.svelte
  sites/geohub/src/routes/settings/+page.server.ts
  sites/geohub/src/routes/settings/+page.svelte
  sites/geohub/src/routes/settings/+page.ts
  sites/geohub/static/assets/sidebar/left-sidebar.png
  sites/geohub/static/assets/sidebar/right-sidebar.png
Labels: enhancement, frontend

#1422 fix: include swagger in svelte routes folder
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/routes/api/docs/+page.server.ts
  sites/geohub/src/routes/api/docs/+page.svelte
  sites/geohub/src/routes/api/docs/+page.ts
  sites/geohub/static/api/docs/favicon-16x16.png
  sites/geohub/static/api/docs/favicon-32x32.png
  sites/geohub/static/api/docs/index.css
  sites/geohub/static/api/docs/index.html
  sites/geohub/static/api/docs/oauth2-redirect.html
  sites/geohub/static/api/docs/swagger-initializer.js
  sites/geohub/static/api/docs/swagger-ui-bundle.js
  sites/geohub/static/api/docs/swagger-ui-bundle.js.map
  sites/geohub/static/api/docs/swagger-ui-es-bundle-core.js
  sites/geohub/static/api/docs/swagger-ui-es-bundle-core.js.map
  sites/geohub/static/api/docs/swagger-ui-es-bundle.js
  sites/geohub/static/api/docs/swagger-ui-es-bundle.js.map
  sites/geohub/static/api/docs/swagger-ui-standalone-preset.js
  sites/geohub/static/api/docs/swagger-ui-standalone-preset.js.map
  sites/geohub/static/api/docs/swagger-ui.css
  sites/geohub/static/api/docs/swagger-ui.css.map
  sites/geohub/static/api/docs/swagger-ui.js
  sites/geohub/static/api/docs/swagger-ui.js.map
  sites/geohub/static/swagger.yaml
Labels: bug

#1425 fix: fetching jobtitle in hooks
  sites/geohub/src/app.d.ts
  sites/geohub/src/hooks.server.ts
Labels: bug

#1426 feat: add /datasets/ingesting API
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
  sites/geohub/src/lib/server/helpers/generateAzureBlobSasToken.ts
  sites/geohub/src/lib/server/helpers/getBlobServiceClient.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/lib/server/helpers/upload.ts
  sites/geohub/src/lib/types/IngestingDataset.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/api/datasets/ingesting/+server.ts
  sites/geohub/src/routes/data/+page.server.ts
  sites/geohub/src/routes/data/+page.svelte
  sites/geohub/src/routes/data/upload/+page.server.ts
  sites/geohub/src/routes/data/upload/+page.svelte
  sites/geohub/static/api/docs/swagger.yaml
Labels: enhancement

#1430 feat: send a message to service bus queue
  .github/workflows/docker-image.yml
  .github/workflows/main_undpgeohub.yml
  pnpm-lock.yaml
  sites/geohub/.env.example
  sites/geohub/package.json
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/lib/server/helpers/sendMessageToServiceBusQueue.ts
  sites/geohub/src/routes/data/upload/+page.server.ts
  sites/geohub/src/routes/data/upload/+page.svelte
Labels: enhancement

#1432 feat: cancel button for data uploading
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
  sites/geohub/src/routes/api/datasets/ingesting/+server.ts
  sites/geohub/src/routes/data/+page.svelte
Labels: enhancement

#1435 feat: show error log in dialog for failed uploaded data
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
Labels: enhancement

#1440 fix: delete .ingesting file when user click cancel button
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/lib/types/IngestingDataset.ts
  sites/geohub/src/routes/api/datasets/ingesting/+server.ts
Labels: bug

#1442 fix: publish delete ingesting file
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
  sites/geohub/src/components/data-view/DataVectorCard.svelte
  sites/geohub/src/lib/VectorTileData.ts
  sites/geohub/src/lib/server/helpers/generateAzureBlobSasToken.ts
  sites/geohub/src/routes/api/datasets/[id]/+server.ts
  sites/geohub/src/routes/data/+page.svelte
  sites/geohub/src/routes/data/publish/+page.server.ts
Labels: bug

#1438 feat: add description of supported formats and simple validation of file extension, and delete/recreate `.ingesting` file when publishing/deleting dataset
  sites/geohub/src/components/data-upload/IngestingDatasets.svelte
  sites/geohub/src/components/data-upload/PublishedDatasets.svelte
  sites/geohub/src/components/data-view/DataVectorCard.svelte
  sites/geohub/src/lib/VectorTileData.ts
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/server/helpers/generateAzureBlobSasToken.ts
  sites/geohub/src/lib/types/AcceptedExtension.ts
  sites/geohub/src/lib/types/IngestingDataset.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/api/datasets/[id]/+server.ts
  sites/geohub/src/routes/api/datasets/ingesting/+server.ts
  sites/geohub/src/routes/data/+page.server.ts
  sites/geohub/src/routes/data/+page.svelte
  sites/geohub/src/routes/data/publish/+page.server.ts
  sites/geohub/src/routes/data/upload/+page.svelte
Labels: enhancement

#1439 Feat/warning modal
  sites/geohub/src/components/App.svelte
  sites/geohub/src/components/Settings.svelte
  sites/geohub/src/components/UserAccount.svelte
  sites/geohub/src/components/controls/DeleteButton.svelte
  sites/geohub/src/components/controls/LegendTypeSwitcher.svelte
  sites/geohub/src/components/controls/Modal.svelte
  sites/geohub/src/routes/settings/+page.server.ts
  sites/geohub/src/routes/settings/+page.svelte
Labels: bug, frontend
