Repository UNDP-Data/geohub, pull requests merged in 2023-01, with the labels that each got.

#1059 add asset header font size options
  packages/svelte-undp-design/src/lib/Accordion/Accordion.stories.ts
  packages/svelte-undp-design/src/lib/Accordion/Accordion.svelte
  sites/geohub/src/components/data-view/DataStacAssetCard.svelte
Labels: enhancement, frontend, refactor

#1063 fix: only create label child layer when the annotation is configured
  sites/geohub/src/components/LayerOrder.svelte
  sites/geohub/src/components/controls/DeleteButton.svelte
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/vector-styles/TextField.svelte
  sites/geohub/src/lib/helper/getLayerProperties.ts
  sites/geohub/src/lib/helper/getPropertyValueFromExpression.ts
Labels: bug

#1066 fix: reset asset list when accordion is opened again
  sites/geohub/src/components/data-view/DataCard.svelte
Labels: bug

#1069 use individual variable for showing progress bar in popup rather than using variable in stores
  sites/geohub/src/components/MapQueryInfoControl.svelte
Labels: bug

#1070 fix: removed key reactivity for interval legend, so it will work well if color is changed
  sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
  sites/geohub/src/components/controls/VectorPolygonAdvanced.svelte
Labels: bug

#1071 fix: moved zoom to layer button position
  sites/geohub/src/components/control-groups/LayerControlGroup.svelte
  sites/geohub/src/components/control-groups/LayerNameGroup.svelte
  sites/geohub/src/components/controls/ActionsDropdown.svelte
  sites/geohub/src/components/controls/DeleteButton.svelte
  sites/geohub/src/components/controls/ZoomToLayerButton.svelte
  sites/geohub/src/styles/button-icons-selected.scss
Labels: enhancement

#1072 refactor: use raster band selector in layerName
  sites/geohub/src/components/control-groups/LayerNameGroup.svelte
  sites/geohub/src/components/controls/RasterBandSelector.svelte
Labels: refactor

#1058 Enhance styles for label panel
  packages/svelte-undp-design/src/lib/Tabs/Tabs.svelte
  sites/geohub/src/components/control-groups/StyleControlGroup.svelte
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/vector-styles/SymbolPlacement.svelte
Labels: frontend, refactor

#1074 refactor: created VectorHeatmapContainer component
  sites/geohub/src/components/controls/VectorHeatmapContainer.svelte
  sites/geohub/src/components/controls/VectorLegendPanel.svelte
  sites/geohub/src/components/controls/vector-styles/HeatmapColor.svelte
Labels: refactor

#1078 fixed to query only visible layers
  sites/geohub/src/components/MapQueryInfoControl.svelte
Labels: bug

#1080 refactor: merged three different vector advanced components to a components
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/controls/OpacityPanel.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
  sites/geohub/src/components/controls/VectorLineAdvanced.svelte
  sites/geohub/src/components/controls/VectorLineContainer.svelte
  sites/geohub/src/components/controls/VectorPolygonAdvanced.svelte
  sites/geohub/src/components/controls/VectorPolygonContainer.svelte
  sites/geohub/src/components/controls/VectorSymbolContainer.svelte
  sites/geohub/src/lib/constants.ts
Labels: refactor

#1079 Change button size in `DashboardMapStyleCard`
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
Labels: frontend

#1081 Added loader size options and make the loader smaller
  packages/svelte-undp-design/src/lib/Loader/Loader.stories.ts
  packages/svelte-undp-design/src/lib/Loader/Loader.svelte
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/MapQueryInfoControl.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/lib/dashboards/MapStyleCardList.svelte
Labels: frontend

#1082 refactor: vector symbol/line/polygon container
  packages/svelte-undp-design/src/lib/Accordion/Accordion.stories.ts
  packages/svelte-undp-design/src/lib/Accordion/Accordion.svelte
  sites/geohub/src/components/controls/IntervalsLegendColorMapRow.svelte
  sites/geohub/src/components/controls/VectorHeatmap.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
  sites/geohub/src/components/controls/VectorLegendPanel.svelte
  sites/geohub/src/components/controls/VectorLine.svelte
  sites/geohub/src/components/controls/VectorLineContainer.svelte
  sites/geohub/src/components/controls/VectorPolygon.svelte
  sites/geohub/src/components/controls/VectorPolygonContainer.svelte
  sites/geohub/src/components/controls/VectorSymbol.svelte
  sites/geohub/src/components/controls/VectorSymbolContainer.svelte
Labels: refactor

#1083 use activeTab to switch tab instead of using boolean flag
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/controls/OpacityPanel.svelte
  sites/geohub/src/components/controls/VectorFilterPanelWizard.svelte
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/VectorLegendPanel.svelte
  sites/geohub/src/components/controls/vector-styles/TextField.svelte
Labels: refactor

#1085 fixed bug of selecting feature on heatmap filter
  sites/geohub/src/components/controls/VectorFilterPanelWizard.svelte
  sites/geohub/src/components/controls/vector-styles/ValueInput.svelte
Labels: bug

#1086 add legend next to layer name
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/control-groups/LayerNameGroup.svelte
  sites/geohub/src/components/controls/vector-styles/HeatmapColor.svelte
  sites/geohub/src/components/controls/vector-styles/IconImage.svelte
  sites/geohub/src/components/controls/vector-styles/Legend.svelte
  sites/geohub/src/lib/constants.ts
Labels: enhancement

#1095 feat: support updating only one blob
  packages/geohub-cli/src/cli/azblob.ts
  packages/geohub-cli/src/util/BlobServiceAccountManager.ts
  packages/geohub-cli/src/util/DatabaseManager.ts
  packages/geohub-cli/src/util/Datasets.ts
Labels: enhancement, backend

#1097 added changesets
  .changeset/README.md
  .changeset/config.json
  .github/workflows/release.yml
  package.json
  pnpm-lock.yaml
Labels: enhancement

#1098 exclude geohub and electricity-dashboard
  .changeset/config.json
Labels: bug

#1099 updated package.json for releasing
  apps/electricity-dashboard/package.json
  packages/current-location/package.json
  packages/geohub-cli/package.json
  packages/style-switcher/package.json
  packages/style-viewer/package.json
  packages/svelte-undp-design/package.json
Labels: bug

#1100 changed access to public in changeset
  .changeset/config.json
Labels: bug

#1101 fix: specify workspace package folders in pnpm-workspace
  .changeset/config.json
  .changeset/smooth-comics-appear.md
  README.md
  packages/svelte-undp-design/src/lib/Loader/Loader.stories.ts
  packages/svelte-undp-design/src/lib/Loader/Loader.svelte
  pnpm-workspace.yaml
  sites/geohub/README.md
Labels: bug

#1090 Style improvements for Interval Legend and Accordion
  .changeset/green-shrimps-fail.md
  packages/svelte-undp-design/src/lib/Accordion/Accordion.svelte
  pnpm-lock.yaml
  sites/geohub/src/components/MapQueryInfoControl.svelte
  sites/geohub/src/components/controls/IntervalsLegendColorMapRow.svelte
  sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
  sites/geohub/src/lib/helper/index.ts
Labels: bug, frontend

#1103 set privete=true for geohub's package.json
  .changeset/config.json
  sites/geohub/package.json
Labels: bug

#1104 Fix/changeset move svelte to peerDependencies
  .changeset/slow-sheep-compare.md
  .changeset/twenty-mangos-cheat.md
  apps/electricity-dashboard/package.json
  packages/current-location/package.json
  packages/style-switcher/package.json
  packages/style-viewer/package.json
  packages/svelte-undp-design/package.json
  pnpm-lock.yaml
  sites/geohub/package.json
  turbo.json
Labels: bug

#1106 fixed initialising map size in electricity dashboard
  apps/electricity-dashboard/src/lib/components/Map.svelte
Labels: bug

#1107 deleted prepublishOnly script from package.json
  .github/workflows/release.yml
  apps/electricity-dashboard/package.json
  packages/current-location/package.json
  packages/style-switcher/package.json
  packages/style-viewer/package.json
  turbo.json
Labels: bug

#1113 add max width to the input
  sites/geohub/src/components/controls/IntervalsLegendColorMapRow.svelte
Labels: bug, frontend

#1115 Fix/packages remove prepare
  .changeset/little-singers-stare.md
  .github/workflows/main_undpgeohub.yml
  .github/workflows/release.yml
  README.md
  apps/electricity-dashboard/package.json
  packages/current-location/package.json
  packages/geohub-cli/package.json
  packages/style-switcher/package.json
  packages/style-viewer/package.json
  packages/svelte-undp-design/package.json
  sites/geohub/.env.example
  sites/geohub/.gitignore
Labels: enhancement

#1117 add prepack and postpack script to move package folder before publish…
  .changeset/popular-keys-tie.md
  README.md
  apps/electricity-dashboard/package.json
  packages/current-location/package.json
  packages/style-switcher/package.json
  packages/style-viewer/package.json
  packages/svelte-undp-design/package.json
Labels: bug

#1119 revert changes to use prepack
  .changeset/nervous-pants-joke.md
  .github/workflows/release.yml
  apps/electricity-dashboard/package.json
  packages/current-location/package.json
  packages/style-switcher/package.json
  packages/style-viewer/package.json
  packages/svelte-undp-design/package.json
Labels: bug

#1120 vector legend interval control invalid inputs
  sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
  sites/geohub/src/lib/helper/updateIntervalValues.ts
Labels: bug, enhancement, refactor

#1124 fixed bug of upsert SQL for dataset table and added deleting feature for azblob CLI
  .changeset/cyan-pens-lie.md
  packages/geohub-cli/src/cli/azblob.ts
  packages/geohub-cli/src/util/BlobServiceAccountManager.ts
  packages/geohub-cli/src/util/DatabaseManager.ts
  packages/geohub-cli/src/util/Datasets.ts
Labels: bug

#1132 Fix/1129 pmtiles metadata api
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/Map.svelte
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
  sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataCategoryCard.svelte
  sites/geohub/src/components/data-view/DataCategoryCardList.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/lib/VectorTileData.ts
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/server/helpers/getStaticPbfMetadataJson.ts
  sites/geohub/src/lib/types/VectorLayerTileStatAttribute.ts
  sites/geohub/src/routes/dashboards/+page.svelte
Labels: enhancement

#1135 Feature/1133 multiple vector layer
  sites/geohub/src/components/LayerOrder.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
  sites/geohub/src/components/data-view/DataVectorCard.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/lib/VectorTileData.ts
Labels: enhancement

#1138 fixed bug of computing stats for pmtiles
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/server/helpers/fetchVectorInfo.ts
  sites/geohub/src/lib/server/helpers/getStaticPbfMetadataJson.ts
Labels: bug

#1139 fixed bug of vector filter to hard code to use first layer
  sites/geohub/src/components/controls/VectorFilterPanelWizard.svelte
  sites/geohub/src/components/controls/vector-styles/PropertySelectButtons.svelte
  sites/geohub/src/components/controls/vector-styles/TextField.svelte
  sites/geohub/src/components/controls/vector-styles/ValueInput.svelte
Labels: bug

#1143 add pmtiles support for style-viewer
  .changeset/polite-pumas-study.md
  packages/style-viewer/package.json
  packages/style-viewer/src/lib/StyleViewer.svelte
  pnpm-lock.yaml
Labels: enhancement

#1128 pmtiles support
  .changeset/metal-keys-shave.md
  .changeset/polite-pumas-study.md
  packages/geohub-cli/package.json
  packages/geohub-cli/src/util/BlobServiceAccountManager.ts
  packages/style-viewer/package.json
  packages/style-viewer/src/lib/StyleViewer.svelte
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/LayerOrder.svelte
  sites/geohub/src/components/Map.svelte
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/VectorFilterPanelWizard.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
  sites/geohub/src/components/controls/vector-styles/LinePattern.svelte
  sites/geohub/src/components/controls/vector-styles/PropertySelectButtons.svelte
  sites/geohub/src/components/controls/vector-styles/TextField.svelte
  sites/geohub/src/components/controls/vector-styles/ValueInput.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
  sites/geohub/src/components/data-view/DataCategoryCard.svelte
  sites/geohub/src/components/data-view/DataCategoryCardList.svelte
  sites/geohub/src/components/data-view/DataVectorCard.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/components/data-view/TagFilter.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/lib/VectorTileData.ts
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/server/helpers/fetchVectorInfo.ts
  sites/geohub/src/lib/server/helpers/getStaticPbfMetadataJson.ts
  sites/geohub/src/lib/types/VectorLayerTileStatAttribute.ts
  sites/geohub/src/routes/dashboards/+page.svelte
Labels: enhancement

#1147 Fix/1136 layer order
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/LayerOrder.svelte
  sites/geohub/src/components/layer-order/Layer.svelte
  sites/geohub/src/components/layer-order/LegendPanel.svelte
  sites/geohub/src/lib/helper/distinct.ts
  sites/geohub/src/lib/helper/index.ts
Labels: bug

#1145 Fix/1112 move props
  sites/geohub/src/components/LayerList.svelte
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/controls/DataCardInfoButton.svelte
  sites/geohub/src/components/controls/IntervalsLegendColorMapRow.svelte
  sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
  sites/geohub/src/components/controls/VisibilityButton.svelte
Labels: refactor

#1152 Feature/1140 attribution
  sites/geohub/src/components/Map.svelte
  sites/geohub/src/components/MapQueryInfoControl.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
  sites/geohub/src/lib/MosaicJsonData.ts
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/VectorTileData.ts
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/server/helpers/getMartinTileJson.ts
  sites/geohub/src/lib/server/helpers/getPgtileservTileJson.ts
  sites/geohub/src/lib/server/helpers/getStaticPbfMetadataJson.ts
  sites/geohub/src/routes/api/stac/mosaicjson/+server.ts
Labels: enhancement

#1156 preload metadata when search in data tab
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/DataVectorCard.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/VectorTileData.ts
Labels: enhancement

#1157 add service worker
  sites/geohub/src/service-worker.ts
Labels: bug

#1168 feat: add download button in DataCardInfo.svelte
  .changeset/twelve-snakes-hammer.md
  packages/svelte-undp-design/package.json
  packages/svelte-undp-design/src/lib/Download/Download.stories.ts
  packages/svelte-undp-design/src/lib/Download/Download.svelte
  packages/svelte-undp-design/src/lib/css/download-card.min.css
  packages/svelte-undp-design/src/lib/index.ts
  pnpm-lock.yaml
  sites/geohub/src/components/controls/DataCardInfoButton.svelte
  sites/geohub/src/components/data-view/DataCardInfo.svelte
Labels: enhancement

#1171 renamed filenames
  documentation/docs/data/introduction.md
  documentation/docs/visualization/histograms.md
  documentation/docs/visualization/legend.md
Labels: bug

#1173 Add sequence diagram on README.md
  README.md
Labels: documentation

#1167 improve state management for vector layers
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/ColorMapPickerCard.svelte
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
  sites/geohub/src/components/controls/VectorLabelPanel.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
  sites/geohub/src/components/controls/VectorLegendPanel.svelte
  sites/geohub/src/components/controls/vector-styles/PropertySelect.svelte
  sites/geohub/src/components/controls/vector-styles/TextField.svelte
  sites/geohub/src/lib/_tests__/Colormaps.test.ts
  sites/geohub/src/lib/colormaps.ts
Labels: bug, work in progress, frontend, refactor

#1178 Refactor/1176 vector move colormappicker
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/controls/LegendTypeSwitcher.svelte
  sites/geohub/src/components/controls/VectorHeatmap.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
  sites/geohub/src/components/controls/VectorLegendPanel.svelte
  sites/geohub/src/components/controls/vector-styles/HeatmapColorRow.svelte
  sites/geohub/src/routes/+page.svelte
  sites/geohub/src/styles/geohubstyle.scss
Labels: refactor

#1179 docs: create contributing guidelines
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/new_feature_request.yml
  CONTRIBUTING.md
Labels: documentation

#1180 fix: fixed bug of resetting colormap when visibility button is clicked.
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
Labels: bug

#1181 refactor: removed unnecessary variables to be exported in IntervalsLegendColorMapRow component
  sites/geohub/src/components/controls/IntervalsLegendColorMapRow.svelte
  sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
Labels: refactor

#1182 refactor: Use LegendTypeSwitcher in Raster component
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
Labels: refactor

#1183 refactor: refactored and moved colormappicker to each raster legend components (#1177)
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/RasterContinuousLegend.svelte
  sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
  sites/geohub/src/components/controls/RasterUniqueValuesLegend.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
Labels: refactor

#1184 feat: added visibility button for each color row in interval legend of raster and vector
  sites/geohub/src/components/controls/IntervalsLegendColorMapRow.svelte
  sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
Labels: enhancement

#1186 doc: added PR template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#1187 fix: updated packages including svelte-awesome-colorpicker to fix #1174
  package.json
  pnpm-lock.yaml
  sites/geohub/package.json
Labels: bug

#1188 fix: bug of restoring state of visilibity button in interval legend
  sites/geohub/src/components/controls/IntervalsLegendColorMapRow.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
  sites/geohub/src/lib/helper/generateColorMap.ts
Labels: bug

#1192 fix: disabled optimizeDeps since there is an issue of dashboard page when pnpm dev is run
  sites/geohub/vite.config.ts
Labels: bug

#1194 feat: added relevant links in footer
  sites/geohub/src/routes/dashboards/+page.svelte
Labels: enhancement

#1193 feat: added signin & singout with Azure AD
  .github/workflows/main_undpgeohub.yml
  .github/workflows/release.yml
  pnpm-lock.yaml
  sites/geohub/.env.example
  sites/geohub/package.json
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/UserAccount.svelte
  sites/geohub/src/components/controls/Notification.svelte
  sites/geohub/src/hooks.server.ts
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
  sites/geohub/src/routes/+error.svelte
  sites/geohub/src/routes/+layout.server.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/src/routes/api/style/[id].json/+server.ts
  sites/geohub/src/routes/api/style/[id]/+server.ts
  sites/geohub/src/routes/api/style/count/+server.ts
  sites/geohub/src/routes/api/tags/+server.ts
  sites/geohub/src/routes/api/vector/[source]/metadata.json/+server.ts
  sites/geohub/src/routes/api/vector/[source]/tile.json/+server.ts
  sites/geohub/src/routes/api/vector/statistics/+server.ts
  sites/geohub/src/routes/dashboards/+page.svelte
Labels: enhancement

#1189 Refactor: Implement use of `IntervalsLegendColorMapRow` in RasterUniqueValues` legend (Issue #1084)
  sites/geohub/src/components/controls/IntervalsLegendColorMapRow.svelte
  sites/geohub/src/components/controls/RasterUniqueValuesLegend.svelte
  sites/geohub/src/components/controls/UniqueValuesLegendColorMapRow.svelte
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
Labels: refactor

#1195 Fix/ci error
  .github/workflows/main_undpgeohub.yml
  package.json
  pnpm-lock.yaml
  sites/geohub/package.json
Labels: bug

#1196 added trustHost in hooks.server.ts
  .github/workflows/main_undpgeohub.yml
  sites/geohub/src/hooks.server.ts
Labels: bug

#1197 added AUTH_SECRET in hooks.server.ts
  sites/geohub/src/hooks.server.ts
Labels: bug

#1198 updated layout.server.ts that only set session property in __data.json when there is session info
  sites/geohub/src/routes/+layout.server.ts
Labels: bug

#1199 fix: add csr=true in +page.ts and removed prerender settings
  sites/geohub/src/routes/+page.ts
Labels: bug

#1200 feat: replaced viewer to Geohub main app
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/LayerList.svelte
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/StyleShare.svelte
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/control-groups/LayerNameGroup.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
  sites/geohub/src/lib/types/LegendState.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/+error.svelte
  sites/geohub/src/routes/+layout.server.ts
  sites/geohub/src/routes/+page.server.ts
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/routes/viewer/+page.server.ts
  sites/geohub/src/routes/viewer/+page.svelte
  sites/geohub/src/routes/viewer/+page.ts
Labels: enhancement

#1201 Fix/user icon without image
  sites/geohub/src/components/UserAccount.svelte
Labels: bug

#1203 refactor: redesigning header
  .changeset/cool-crabs-ring.md
  packages/svelte-undp-design/src/lib/Header/Header.stories.ts
  packages/svelte-undp-design/src/lib/Header/Header.svelte
  packages/svelte-undp-design/src/lib/css/mega-menu.min.css
  packages/svelte-undp-design/src/lib/css/menu.min.css
  packages/svelte-undp-design/src/lib/css/mobile-nav.min.css
  packages/svelte-undp-design/src/lib/interfaces/HeaderLink.ts
  packages/svelte-undp-design/src/lib/interfaces/index.ts
  sites/geohub/src/components/Header.svelte
  sites/geohub/src/components/StyleShare.svelte
  sites/geohub/src/routes/+error.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/routes/dashboards/+page.ts
Labels: refactor

#1206 fix: moved share dialog component outside of header to prevent closing by clicking dialog
  .github/workflows/main_undpgeohub.yml
  pnpm-lock.yaml
  sites/geohub/src/components/Header.svelte
Labels: bug

#1208 fix: update filloutline color with new transparency of fill color in vector advanced legend
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
Labels: bug

#1210 feat: fetch login user info and add jobTitle to user card
  sites/geohub/src/components/UserAccount.svelte
  sites/geohub/src/hooks.server.ts
  sites/geohub/src/routes/+layout.server.ts
Labels: enhancement

#1212 doc: add accesslevel to style table
  .changeset/small-hairs-fry.md
  packages/geohub-cli/docs/database.vuerd.json
  packages/geohub-cli/docs/geohub-database-erd.png
  packages/geohub-cli/docs/geohub-database.sql
Labels: documentation

#1216 Feat: Implement unique values legend on string properties in vectors (Issue #1146)
  sites/geohub/src/components/controls/VectorLegendAdvanced.svelte
  sites/geohub/src/components/controls/VectorLegendPanel.svelte
  sites/geohub/src/components/controls/vector-styles/FillColor.svelte
  sites/geohub/src/components/controls/vector-styles/FillOutlineColor.svelte
  sites/geohub/src/components/controls/vector-styles/IconColor.svelte
  sites/geohub/src/components/controls/vector-styles/Legend.svelte
  sites/geohub/src/components/controls/vector-styles/LineColor.svelte
  sites/geohub/src/components/controls/vector-styles/PropertySelect.svelte
  sites/geohub/src/lib/helper/getLayerProperties.ts
  sites/geohub/src/lib/server/helpers/fetchVectorInfo.ts
Labels: enhancement

#1153 feat: 3D terrain with terrarium raster dem
  sites/geohub/src/components/Map.svelte
Labels: enhancement

#1219 fix: a bug to remove undefined properties from source of style.json
  sites/geohub/src/lib/helper/updateParamsInURL.ts
Labels: bug

#1223 Feat/1218 hillshade switch control
  sites/geohub/src/components/LayerVisibilitySwitcher.svelte
  sites/geohub/src/components/Map.svelte
  sites/geohub/src/components/MapQueryInfoControl.svelte
Labels: enhancement

#1224 feat: changed map query tool's icon since it was the same with attribution icon
  sites/geohub/src/components/MapQueryInfoControl.svelte
Labels: enhancement

#1226 doc: added refactoring template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/refactoring.yml
Labels: documentation

#1228 fix: #1225 header logo height
  .changeset/blue-deers-attend.md
  packages/svelte-undp-design/src/lib/css/country-site-header.min.css
Labels: bug

#1230 fix: map height and dashboard page height in smartphone
  sites/geohub/src/app.html
  sites/geohub/src/components/MainApp.svelte
  sites/geohub/src/components/Map.svelte
  sites/geohub/src/components/MapQueryInfoControl.svelte
  sites/geohub/src/routes/+page.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
  sites/geohub/src/routes/dashboards/electricity/+page.svelte
Labels: bug

#1231 fix: 1207 set splitter height in main geohub, and fix height of electricity dashboard content
  .changeset/angry-readers-cross.md
  apps/electricity-dashboard/src/lib/components/Content.svelte
  apps/electricity-dashboard/src/routes/+page.svelte
  sites/geohub/src/components/Content.svelte
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/LayerList.svelte
  sites/geohub/src/components/MainApp.svelte
Labels: bug

#1235 Refactor: use same component for UniqueValues and IntervalLegend in Rasters
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/controls/RasterAdvancedLegend.svelte
  sites/geohub/src/components/controls/RasterIntervalsLegend.svelte
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
  sites/geohub/src/components/controls/RasterUniqueValuesLegend.svelte
Labels: bug, enhancement, frontend

#1238 Fix/undp header footer
  .changeset/six-owls-rest.md
  packages/svelte-undp-design/src/lib/Footer/Footer.svelte
  packages/svelte-undp-design/src/lib/Header/Header.svelte
  sites/geohub/.env.example
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
Labels: bug, documentation

#1240 Fix/raster interval legend
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/RasterAdvancedLegend.svelte
Labels: bug

#1242 fix: improve dashboard map
  sites/geohub/src/components/AccessLevelSwitcher.svelte
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/StyleShare.svelte
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/lib/dashboards/DashboardMapStyleCard.svelte
  sites/geohub/src/routes/dashboards/+page.svelte
Labels: bug, enhancement

#1245 Create util functions
  sites/geohub/src/lib/helper/getValueFromRasterTileUrl.ts
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/lib/helper/loadMap.ts
  sites/geohub/src/lib/helper/updateParamsInURL.ts
  sites/geohub/src/lib/types/Layer.ts
Labels: refactor

#1246 refactor: rename maps components
  sites/geohub/src/components/maps/MapStyleCard.svelte
  sites/geohub/src/components/maps/MapStyleCardList.svelte
  sites/geohub/src/routes/maps/+page.svelte
Labels: refactor

#1247 Use name property from metadata.json or pmtiles's metadata instead of using file name if name property is present.
  .changeset/fluffy-teachers-develop.md
  packages/geohub-cli/src/util/BlobServiceAccountManager.ts
Labels: enhancement

#1251 Refactor/1217 rename default classify
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/VectorLayer.svelte
  sites/geohub/src/components/controls/LegendTypeSwitcher.svelte
  sites/geohub/src/components/controls/RasterClassifyLegend.svelte
  sites/geohub/src/components/controls/RasterDefaultLegend.svelte
  sites/geohub/src/components/controls/RasterLegend.svelte
  sites/geohub/src/components/controls/RasterLegendContainer.svelte
  sites/geohub/src/components/controls/RasterRefineContainer.svelte
  sites/geohub/src/components/controls/RasterTransform.svelte
  sites/geohub/src/components/controls/RasterTransformAdvanced.svelte
  sites/geohub/src/components/controls/RasterTransformNumbersInput.svelte
  sites/geohub/src/components/controls/RasterTransformSimple.svelte
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
  sites/geohub/src/components/controls/VectorFilter.svelte
  sites/geohub/src/components/controls/VectorLegend.svelte
  sites/geohub/src/lib/constants.ts
Labels: refactor

#1254 refactor: fix band metadata type error and lint warning
  sites/geohub/src/components/DataView.svelte
  sites/geohub/src/components/LayerOrder.svelte
  sites/geohub/src/components/LayerVisibilitySwitcher.svelte
  sites/geohub/src/components/MainApp.svelte
  sites/geohub/src/components/MapQueryInfoControl.svelte
  sites/geohub/src/components/RasterLayer.svelte
  sites/geohub/src/components/StyleShare.svelte
  sites/geohub/src/components/controls/ColorMapPicker.svelte
  sites/geohub/src/components/controls/ColorMapPickerCard.svelte
  sites/geohub/src/components/controls/NumberInput.svelte
  sites/geohub/src/components/controls/RasterBandSelector.svelte
  sites/geohub/src/components/controls/RasterClassifyLegend.svelte
  sites/geohub/src/components/controls/RasterDefaultLegend.svelte
  sites/geohub/src/components/controls/RasterLegend.svelte
  sites/geohub/src/components/controls/RasterTransformAdvanced.svelte
  sites/geohub/src/components/controls/RasterTransformSimple.svelte
  sites/geohub/src/components/controls/VectorClassifyLegend.svelte
  sites/geohub/src/components/controls/VectorFilter.svelte
  sites/geohub/src/components/controls/vector-styles/HeatmapColorRow.svelte
  sites/geohub/src/components/controls/vector-styles/IconImage.svelte
  sites/geohub/src/components/controls/vector-styles/IconImagePicker.svelte
  sites/geohub/src/components/controls/vector-styles/Legend.svelte
  sites/geohub/src/components/controls/vector-styles/MaplibreColorPicker.svelte
  sites/geohub/src/components/controls/vector-styles/OperationButtons.svelte
  sites/geohub/src/components/controls/vector-styles/PropertySelectButtons.svelte
  sites/geohub/src/components/controls/vector-styles/ValueInput.svelte
  sites/geohub/src/components/data-view/DataCard.svelte
  sites/geohub/src/components/data-view/MiniMap.svelte
  sites/geohub/src/components/data-view/TextFilter.svelte
  sites/geohub/src/components/layer-order/LegendPanel.svelte
  sites/geohub/src/hooks.server.ts
  sites/geohub/src/lib/MosaicJsonData.ts
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/helper/distinct.ts
  sites/geohub/src/lib/helper/getActiveBandIndex.ts
  sites/geohub/src/lib/helper/getPropertyValueFromExpression.ts
  sites/geohub/src/lib/types/RasterTileMetadata.ts
  sites/geohub/src/routes/api/vector/statistics/+server.ts
  sites/geohub/src/routes/dashboards/electricity/+page.svelte
Labels: refactor

#1248 feat: loadable map store
  sites/geohub/src/components/MainApp.svelte
  sites/geohub/src/lib/helper/updateParamsInURL.ts
  sites/geohub/src/stores/index.ts
Labels: refactor

#1260 feat: rename saved maps and added stats in maps page
  .changeset/sour-pumpkins-bow.md
  packages/svelte-undp-design/src/lib/Stats/Stats.stories.ts
  packages/svelte-undp-design/src/lib/Stats/Stats.svelte
  packages/svelte-undp-design/src/lib/css/stats-cards.min.css
  packages/svelte-undp-design/src/lib/index.ts
  packages/svelte-undp-design/src/lib/interfaces/StatsCard.ts
  packages/svelte-undp-design/src/lib/interfaces/index.ts
  sites/geohub/src/components/maps/MapStyleCardList.svelte
  sites/geohub/src/lib/constants.ts
  sites/geohub/src/lib/helper/createHeaderLinks.ts
  sites/geohub/src/lib/server/helpers/getMapStats.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/routes/maps/+page.server.ts
  sites/geohub/src/routes/maps/+page.svelte
Labels: enhancement

#1262 fix: bug of weird maplibre error by using new way to upload source URL
  sites/geohub/src/lib/helper/updateParamsInURL.ts
Labels: bug

#1263 fix: use css flex instead of bulma tile
  sites/geohub/src/components/maps/MapStyleCardList.svelte
  sites/geohub/src/routes/maps/+page.svelte
Labels: bug

#1264 fix: removed shortcuts for climate change and martin, and changed some icons
  sites/geohub/src/lib/constants.ts
  sites/geohub/static/assets/maplibre.png
  sites/geohub/static/assets/microsoft.png
  sites/geohub/static/assets/postgresql.png
Labels: enhancement
