Repository UNDP-Data/geohub, pull requests merged in 2024-06, with the labels that each got.

#3592 fix: fixed CORS to allow all websites to access to geohub api
  .changeset/mighty-toes-burn.md
  sites/geohub/src/hooks.server.ts
  sites/static-image-api/src/hooks.server.ts
Labels: bug

#3596 fix: use default text-font if a symbol layer does not have default te…
  .changeset/shy-plums-sparkle.md
  sites/geohub/src/lib/server/helpers/getStyleById.ts
Labels: bug

#3598 fix: set default text-font if text-field property is used without tex…
  .changeset/famous-adults-remain.md
  sites/geohub/src/lib/server/helpers/getStyleById.ts
Labels: bug

#3600 fix: add error handling for /api/style endpoint
  .changeset/fluffy-teachers-protect.md
  sites/geohub/src/routes/api/style/+server.ts
Labels: bug

#3603 fix: fixed a bug of STAC catalog explore to be able to handle if a ca…
  .changeset/fuzzy-dancers-mix.md
  sites/geohub/src/components/util/stac/StacCollectionMap.svelte
Labels: bug

#3607 fix: show tabs in popup of map mode if multiple items/collections are matched.
  .changeset/stupid-roses-ring.md
  sites/geohub/src/components/util/stac/StacCollectionMap.svelte
Labels: bug

#3608 fix: removed production deployment CI
  .github/workflows/ci.yml
Labels: backend

#2565 feat/level-2-satelitte-func
  .changeset/mighty-shirts-turn.md
  backends/database/database.vuerd.json
  backends/database/geohub-database-erd.png
  backends/database/geohub-database.sql
  sites/geohub/src/components/maplibre/raster/RasterClassifyLegend.svelte
  sites/geohub/src/components/maplibre/vector/VectorColorClassification.svelte
  sites/geohub/src/components/util/MiniMap.svelte
  sites/geohub/src/components/util/stac/StacApiExplorer.svelte
  sites/geohub/src/lib/RasterTileData.ts
  sites/geohub/src/lib/helper/getDefaultLayerStyleForStacProducts.ts
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/lib/server/defaultStyle/RasterDefaultStyle.ts
  sites/geohub/src/lib/server/helpers/createDatasetLinks.ts
  sites/geohub/src/lib/server/helpers/stac.ts
  sites/geohub/src/lib/stac/EarthSearchStac.ts
  sites/geohub/src/lib/stac/MicrosoftPlanetaryStac.ts
  sites/geohub/src/lib/stac/StacTemplate.ts
  sites/geohub/src/lib/types/AvailableStacProduct.ts
  sites/geohub/src/lib/types/StacProduct.ts
  sites/geohub/src/lib/types/Tag.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/(app)/management/stac/api/[id]/[collection]/+page.svelte
  sites/geohub/src/routes/api/products/+server.ts
  sites/geohub/src/routes/api/stac/[id]/[collection]/[...item]/products/+server.ts
  sites/geohub/src/routes/api/stac/[id]/[collection]/[product_id]/+server.ts
  sites/geohub/src/routes/api/stac/[id]/[collection]/products/+server.ts
  sites/geohub/src/routes/api/stac/style/[id]/[collection]/[...item]/[asset]/+server.ts
  sites/geohub/src/routes/api/stac/style/[id]/[collection]/[...item]/products/+server.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: enhancement

#3621 fix: fixed layout collapse of dataset section in landing page
  .changeset/polite-hotels-argue.md
  sites/geohub/src/components/pages/home/ExploreDatasets.svelte
Labels: bug

#3639 fix: tools page redesign
  .changeset/calm-carrots-study.md
  .changeset/neat-dragons-study.md
  documentation/docs/assets/analytics/geohub_tools.png
  documentation/docs/assets/analytics/nighttime_lights_dataset.png
  documentation/docs/assets/analytics/rca_input.png
  packages/svelte-undp-components/src/lib/components/HeroHeader.svelte
  sites/geohub/src/routes/(app)/tools/+page.svelte
Labels: bug, UI/UX

#3640 doc: added git-revision-date-localized plugin to mkdocs
  documentation/mkdocs.yml
  documentation/requirements.txt
Labels: documentation

#3641 fix: returns 404 error from /products/[id] endpoint. Refactored products endpoint code.
  .changeset/sharp-tools-wink.md
  sites/geohub/src/components/util/stac/StacApiExplorer.svelte
  sites/geohub/src/lib/server/Product.ts
  sites/geohub/src/lib/types/Product.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/api/products/+server.ts
  sites/geohub/src/routes/api/products/[id]/+server.ts
Labels: bug, refactor

#3642 refactor: remvoed duplicated AvailableStacProduct interface to use StacProduct interface.
  .changeset/twenty-dancers-pretend.md
  sites/geohub/src/components/util/stac/StacApiExplorer.svelte
  sites/geohub/src/lib/types/AvailableStacProduct.ts
  sites/geohub/src/lib/types/index.ts
Labels: refactor

#3643 fix: disabled pointer-events for zoom level notification message. so zoom can work over the notification message.
  .changeset/fresh-files-end.md
  sites/geohub/src/components/util/stac/StacApiExplorer.svelte
Labels: bug

#3644 refactor: changed products endpoints to /stac/[id]/[collection]/products/[product_id].
  .changeset/slow-brooms-relate.md
  sites/geohub/src/components/util/stac/StacApiExplorer.svelte
  sites/geohub/src/routes/api/stac/[id]/[collection]/products/[product_id]/+server.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: refactor

#3646 fix: force to transform user_email to lowercase in hooks.server.ts and UserPermission component
  .changeset/shaggy-news-beam.md
  sites/geohub/src/components/pages/data/datasets/UserPermission.svelte
  sites/geohub/src/lib/server/auth.ts
Labels: bug

#3649 fix: applied UNDP design system title format to Tools page by adding custmization to undp-bulma
  .changeset/large-feet-bow.md
  .changeset/moody-islands-heal.md
  .changeset/wild-birds-divide.md
  packages/svelte-undp-components/src/lib/components/HeroHeader.svelte
  packages/undp-bulma/bulma.scss
  packages/undp-bulma/fonts/soehne-breit-web-dreiviertelfett.woff
  packages/undp-bulma/fonts/soehne-breit-web-dreiviertelfett.woff2
  packages/undp-bulma/src/main.ts
  sites/geohub/src/routes/(app)/tools/+page.svelte
Labels: UI/UX

#3650 fix: add dynamic vector to tools
  .changeset/two-feet-grin.md
  sites/geohub/src/routes/(app)/tools/+page.server.ts
  sites/geohub/src/routes/(app)/tools/+page.svelte
  sites/geohub/src/routes/(app)/tools/+page.ts
Labels: bug

#3655 fix: changed card accent color to yellow for hovered color.
  .changeset/cool-tigers-notice.md
  sites/geohub/src/routes/(app)/tools/+page.svelte
Labels: bug

#3656 fix: redeploy produciton docker image
  .github/workflows/ci.yml
Labels: backend

#3661 feat: added onChapterEnter and onChapterExit to chapter properties.
  .changeset/gorgeous-spies-happen.md
  packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
  packages/svelte-maplibre-storymap/src/lib/interfaces/StoryMapChapter.ts
  packages/svelte-maplibre-storymap/src/routes/+page.server.ts
Labels: enhancement

#3665 fix: optimized docker image build for production
  .changeset/green-plants-whisper.md
  docker/Dockerfile.production
  sites/geohub/build-nodemodules.sh
  sites/geohub/pm2.json
Labels: docker

#3667 fix: fixed layout collapse of dashboard landing page and did some refactoring
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts
  sites/geohub/src/routes/(map)/dashboards/electricity/components/DownloadData.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/components/IntroductionPanel.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/components/OverlayControl.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/utils/adminLayer.ts
Labels: bug

#3668 feat: add material-icons-outlined to undp-bulma
  .changeset/ninety-eggs-jog.md
  packages/undp-bulma/bulma.scss
Labels: enhancement

#3671 fix: dashboard download button
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/utils/adminLayer.ts
  sites/geohub/static/assets/img/download.svg
  sites/geohub/static/assets/img/information.svg
Labels: bug

#3675 fix: create 'self' link if it does not exist in catalog.json
  .changeset/giant-crews-appear.md
  sites/geohub/src/components/util/stac/StacCollectionMap.svelte
Labels: bug

#3677 fix: enabled cgaz admin tool and fixed bug of time slider position
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/components/ElectricityControl.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/components/ExploreEvolution.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSliderControl.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/constansts.ts
  sites/geohub/src/routes/(map)/dashboards/electricity/interfaces/Dataset.ts
  sites/geohub/src/routes/(map)/dashboards/electricity/interfaces/index.ts
Labels: bug

#3678 fix: replaced preview image for new dashboard
  sites/geohub/static/assets/electricity-snapshot.png
Labels: bug

#3679 fix: disabled hovered feature state for dashboard
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
Labels: bug

#3683 fix: allow external HTTP sources to be registered to GeoHub
  .changeset/green-shoes-refuse.md
  sites/geohub/src/lib/server/helpers/generateAzureBlobSasToken.ts
  sites/geohub/src/lib/server/helpers/getVectorMetadata.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/lib/server/helpers/isGeoHubBlobStorage.ts
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.server.ts
Labels: bug

#3685 fix: fixed a bug of default layer style editor for vector data to avoid adding layers many times.
  .changeset/silly-ladybugs-hang.md
  sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
  sites/geohub/src/components/util/LayerTypeSwitch.svelte
Labels: bug

#3686 fix: fixed bug of editing external dataset properties.
  .changeset/honest-waves-attack.md
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.server.ts
Labels: bug

#3687 fix: Use social iamge for saved map instead of using same style image
  .changeset/curvy-dingos-wait.md
  sites/geohub/src/routes/(app)/maps/[id]/+page.server.ts
  sites/geohub/src/routes/(app)/maps/[id]/+page.ts
Labels: bug

#3690 fix: show social image for dataset preview
  .changeset/clever-pigs-hang.md
  sites/geohub/src/lib/server/helpers/createDatasetLinks.ts
  sites/geohub/src/routes/(app)/data/[id]/+page.server.ts
  sites/geohub/src/routes/(app)/data/[id]/+page.svelte
  sites/geohub/src/routes/(app)/data/[id]/+page.ts
  sites/geohub/src/routes/+layout.svelte
Labels: bug

#3692 feat: add dropdown menu to import an external file
  .changeset/angry-baboons-impress.md
  .changeset/calm-guests-sit.md
  documentation/docs/assets/data/dataupload_1.png
  documentation/docs/assets/data/remote_register_1.png
  documentation/docs/assets/data/remote_register_2.png
  documentation/docs/data/data_remotefile_register.md
  documentation/docs/data/data_upload.md
  documentation/mkdocs.yml
  packages/svelte-undp-components/src/lib/components/HeroHeader.stories.ts
  packages/svelte-undp-components/src/lib/components/HeroHeader.svelte
  sites/geohub/src/components/pages/data/datasets/DatasetPreview.svelte
  sites/geohub/src/routes/(app)/data/+page.svelte
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.server.ts
  sites/geohub/src/routes/(app)/data/[id]/+page.server.ts
  sites/geohub/src/routes/(app)/maps/[id]/+page.server.ts
Labels: enhancement

#3700 fix: fixed bugs of when user is leaving map edit page. Also, clear local storage when users add new data from /data page.
  .changeset/giant-islands-boil.md
  .changeset/ten-hotels-itch.md
  packages/cgaz-admin-tool/src/lib/index.ts
  sites/geohub/src/components/pages/data/datasets/DatasetPreview.svelte
  sites/geohub/src/lib/helper/isStyleChanged.ts
  sites/geohub/src/lib/helper/localstorage.ts
  sites/geohub/src/routes/(app)/data/[id]/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/api/[id]/[collection]/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte
  sites/geohub/src/routes/(app)/tools/+page.svelte
  sites/geohub/src/routes/(map)/maps/+layout.svelte
Labels: bug

#3708 doc: added SQLs to create storymap related tables.
  backends/database/database.vuerd.json
  backends/database/geohub-database-erd.png
  backends/database/geohub-database.sql
Labels: documentation

#3709 fix: fixed bug of returning zoom=null from /datasets/{id}/preview/sty…
  .changeset/lemon-avocados-divide.md
  sites/geohub/src/routes/api/datasets/[id]/preview/style.json/+server.ts
Labels: bug

#3713 fix: added image_alignment to place image in chapter either left, center or right of markdown
  .changeset/purple-radios-shout.md
  backends/database/database.vuerd.json
  backends/database/geohub-database-erd.png
  backends/database/geohub-database.sql
  packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
  packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
  packages/svelte-maplibre-storymap/src/lib/css/markdown-content.scss
  packages/svelte-maplibre-storymap/src/lib/interfaces/StoryMapChapter.ts
  packages/svelte-maplibre-storymap/src/lib/interfaces/StoryMapConfig.ts
  packages/svelte-maplibre-storymap/src/routes/+page.server.ts
Labels: bug

#3715 doc: added proposed storymaps endpoints in swagger.
  .changeset/five-foxes-jump.md
  sites/geohub/static/api/swagger/spec.yaml
Labels: documentation

#3718 fix: changed top-left controls order. show timeslider control first
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSliderControl.svelte
Labels: bug

#3720 fix: merged markdown css to chapter.scss
  .changeset/lovely-shoes-suffer.md
  packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
  packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
  packages/svelte-maplibre-storymap/src/lib/css/markdown-content.scss
Labels: bug

#3723 chore: upgraded pg_tileserv docker to 20240614
  backends/k8s/pgtileserv/yaml/pgtileserv-deployment.yaml
Labels: backend
