Repository UNDP-Data/geohub, pull requests merged in 2024-08, with the labels that each got.

#3847 fix: improved storymap UI, and separated header and footer to individual svelte component.
  .changeset/funny-chairs-judge.md
  packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMapFooter.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMapHeader.svelte
  packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
  packages/svelte-maplibre-storymap/src/lib/css/dark/footer.scss
  packages/svelte-maplibre-storymap/src/lib/css/dark/header.scss
  packages/svelte-maplibre-storymap/src/lib/css/dark/story.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/footer.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/header.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/story.scss
  packages/svelte-maplibre-storymap/src/routes/+page.server.ts
  packages/svelte-maplibre-storymap/src/routes/+page.svelte
  sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[id]/viewer/+page.svelte
Labels: bug

#3850 fix: replaced to zonalstats admin data with additional 2021-2023 years
  .changeset/mighty-birds-clean.md
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.server.ts
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/components/Charts.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/components/ExploreEvolution.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/components/TimeSlider.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/utils/adminLayer.ts
Labels: bug

#3848 Fix/3834 storymap header setting
  .changeset/curly-countries-peel.md
  .changeset/rude-singers-breathe.md
  packages/svelte-maplibre-storymap/src/lib/index.ts
  sites/geohub/src/components/pages/storymap/StorymapFooterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderFooterMiniPreview.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderFooterPreview.svelte
  sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapStyleSelector.svelte
  sites/geohub/src/lib/server/StorymapManager.ts
  sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: bug, UI/UX

#3853 fix: adjusted preview image size since border is hidden
  sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderFooterMiniPreview.svelte
Labels: bug

#3854 fix: chapter preview image location
  .changeset/seven-socks-exist.md
  packages/svelte-maplibre-storymap/src/lib/css/dark/footer.scss
  packages/svelte-maplibre-storymap/src/lib/css/dark/header.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/footer.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/header.scss
  sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
Labels: bug

#3857 fix: relayout /storymaps/{id} page layout by merging info and preview
  .changeset/strong-sheep-divide.md
  sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte
Labels: UI/UX

#3861 Fix/3841 pagination hidden
  .changeset/nasty-guests-kick.md
  .changeset/strange-brooms-mix.md
  packages/svelte-undp-design/src/lib/Pagination/Pagination.stories.ts
  packages/svelte-undp-design/src/lib/Pagination/Pagination.svelte
  sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
  sites/geohub/src/components/pages/home/MapStyleCardList.svelte
  sites/geohub/src/components/pages/storymap/GeoHubMapSelector.svelte
  sites/geohub/src/components/util/stac/StacCollectionMap.svelte
  sites/geohub/src/routes/(app)/storymaps/+page.svelte
  sites/geohub/src/routes/(app)/tools/+page.svelte
Labels: bug, UI/UX

#3862 fix: use h5 of undp-bulma for ModalTemplate title
  .changeset/cyan-carrots-smoke.md
  packages/svelte-undp-components/src/lib/components/ModalTemplate.svelte
Labels: bug, UI/UX

#3863 fix: bug of switching slide setting from header and chapter
  .changeset/plenty-boats-help.md
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: bug

#3864 fix: delete button and heading style of undp-bulma
  .changeset/late-olives-refuse.md
  .changeset/many-shoes-boil.md
  packages/undp-bulma/bulma.scss
  packages/undp-bulma/src/main.ts
Labels: bug, UI/UX

#3865 fix: changed active color of segment button to black. added new prop …
  .changeset/old-maps-doubt.md
  packages/svelte-undp-components/src/lib/components/SegmentButtons.stories.ts
  packages/svelte-undp-components/src/lib/components/SegmentButtons.svelte
Labels: UI/UX

#3866 Fix/storymap description
  .changeset/honest-colts-exist.md
  backends/database/database.vuerd.json
  backends/database/geohub-database-erd.png
  backends/database/geohub-database.sql
  sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderFooterMiniPreview.svelte
  sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
  sites/geohub/src/lib/server/StorymapManager.ts
  sites/geohub/src/lib/types/Storymap.ts
  sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte
Labels: UI/UX

#3871 fix: added +page.ts to show page metadata for CEEI dashboard
  sites/geohub/src/routes/(map)/dashboards/ceei/+page.ts
Labels: bug

#3872 fix: moved frontend dependencies (joi, pako, topojson-client, xlsx) to devDependencies
  pnpm-lock.yaml
  sites/geohub/package.json
Labels: bug

#3875 Fix/3856 redesign map page
  .changeset/shy-yaks-hide.md
  documentation/docs/assets/sharing/share_map_1.png
  documentation/docs/assets/sharing/share_map_2.png
  documentation/docs/assets/sharing/share_map_5.png
  documentation/docs/assets/sharing/share_map_7.png
  documentation/docs/sharing/share_map.md
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
Labels: UI/UX

#3876 Fix/3855 redesign data page
  .changeset/friendly-glasses-agree.md
  documentation/docs/assets/data/best_practice_example_1.png
  documentation/docs/assets/data/publish_8.png
  documentation/docs/assets/data/search_maxar_1.png
  documentation/docs/assets/data/search_maxar_5.png
  documentation/docs/assets/data/search_satellite_2.png
  documentation/docs/assets/data/search_satellite_3.png
  documentation/docs/assets/data/search_satellite_4.png
  documentation/docs/assets/data/search_satellite_5.png
  documentation/docs/assets/data/search_satellite_6.png
  documentation/docs/data/search_datasets_satellite.md
  sites/geohub/src/components/pages/data/datasets/PublishedDataset.svelte
  sites/geohub/src/routes/(app)/data/[id]/+page.svelte
Labels: UI/UX

#3885 fix: show GeoHub map preview next to GEOHUB MAP CATALOG button if a map is selected
  .changeset/sharp-ears-tickle.md
  sites/geohub/src/components/pages/storymap/StorymapStyleSelector.svelte
Labels: bug

#3882 fix: fixed bug of layout collapse of storymap footer together with UNDP footer
  .changeset/few-melons-complain.md
  .changeset/shiny-kings-crash.md
  packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[id]/viewer/+page.svelte
Labels: bug

#3886 feat: added scroll control to storymap component
  .changeset/moody-garlics-kiss.md
  .changeset/unlucky-papayas-add.md
  backends/database/database.vuerd.json
  backends/database/geohub-database-erd.png
  backends/database/geohub-database.sql
  packages/svelte-maplibre-storymap/package.json
  packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMapFooter.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMapHeader.svelte
  packages/svelte-maplibre-storymap/src/lib/interfaces/StoryMapConfig.ts
  packages/svelte-maplibre-storymap/src/routes/+page.server.ts
  pnpm-lock.yaml
  sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
  sites/geohub/src/lib/server/StorymapManager.ts
Labels: enhancement

#3891 fix: fixed position of BackToTop component for storymap viewer
  .changeset/eighty-pugs-complain.md
  sites/geohub/src/routes/(storymap)/storymaps/[id]/viewer/+page.svelte
Labels: bug

#3894 refactor: added +layout for both dashboards
  sites/geohub/src/routes/(map)/dashboards/+layout.server.ts
  sites/geohub/src/routes/(map)/dashboards/+layout.svelte
  sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts
Labels: refactor

#3895 refactor: Use map context api instead of global store variable
  sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/ceei/components/LayerControl.svelte
  sites/geohub/src/routes/(map)/dashboards/ceei/stores/index.ts
  sites/geohub/src/routes/(map)/dashboards/ceei/utils/layerHelper.ts
Labels: refactor

#3896 fix: added up/down button in chapter mini preview to change order.
  .changeset/stupid-starfishes-perform.md
  sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
Labels: enhancement

#3897 Chore/remove marked type
  .changeset/khaki-elephants-love.md
  packages/svelte-maplibre-storymap/package.json
  packages/svelte-undp-design/package.json
  pnpm-lock.yaml
  sites/geohub/package.json
Labels: bug

#3902 fix: added maptiler geocoder for dashboards
  sites/geohub/src/routes/(map)/dashboards/+layout.server.ts
  sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
Labels: enhancement

#3580 feat: Initial layout of CEEI dashboard
  .changeset/eleven-houses-occur.md
  .changeset/good-eagles-play.md
  packages/svelte-undp-design/src/lib/Button/Button.stories.ts
  packages/svelte-undp-design/src/lib/Button/Button.svelte
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/pages/home/DashboardContents.svelte
  sites/geohub/src/lib/server/config/FooterItems.ts
  sites/geohub/src/routes/(map)/dashboards/+layout.server.ts
  sites/geohub/src/routes/(map)/dashboards/+layout.svelte
  sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/ceei/+page.ts
  sites/geohub/src/routes/(map)/dashboards/ceei/components/DropdownSearch.svelte
  sites/geohub/src/routes/(map)/dashboards/ceei/components/LayerControl.svelte
  sites/geohub/src/routes/(map)/dashboards/ceei/components/PopupTable.svelte
  sites/geohub/src/routes/(map)/dashboards/ceei/components/UploadDataErrorToast.svelte
  sites/geohub/src/routes/(map)/dashboards/ceei/stores/index.ts
  sites/geohub/src/routes/(map)/dashboards/ceei/utils/layerHelper.ts
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.server.ts
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.ts
  sites/geohub/static/assets/ceei-snapshot.png
Labels: enhancement

#3868 fix: added breadcrumbs to storymap editor for navigation
  .changeset/funny-carrots-glow.md
  sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: UI/UX

#3904 fix: added IBM attribution to maplibre of dashboards
  .changeset/early-dodos-wonder.md
  sites/geohub/src/routes/(map)/dashboards/+layout.server.ts
  sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
Labels: bug

#3907 Fix/3869 initial setup
  .changeset/tame-chefs-speak.md
  backends/database/database.vuerd.json
  backends/database/geohub-database-erd.png
  backends/database/geohub-database.sql
  packages/svelte-maplibre-storymap/src/lib/StoryMapFooter.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderFooterPreview.svelte
  sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
  sites/geohub/src/components/util/AccessLevelSwitcher.svelte
  sites/geohub/src/lib/server/StorymapManager.ts
  sites/geohub/src/lib/types/Storymap.ts
  sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: UI/UX

#3910 Fix/3887 default logo image
  .changeset/smart-apples-sin.md
  sites/geohub/src/components/pages/storymap/ImageUploader.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
  sites/geohub/src/lib/config/DefaultUserConfig/StorymapDefaultLogo.ts
  sites/geohub/src/lib/config/DefaultUserConfig/index.ts
  sites/geohub/src/lib/helper/imageUrlToBase64.ts
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: bug

#3911 fix: add header and footer sidebar preview
  .changeset/cuddly-falcons-relax.md
  packages/svelte-maplibre-storymap/src/lib/StoryMapFooter.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMapHeader.svelte
  packages/svelte-maplibre-storymap/src/lib/css/dark/footer.scss
  packages/svelte-maplibre-storymap/src/lib/css/dark/header.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/footer.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/header.scss
  sites/geohub/src/components/pages/storymap/StorymapHeaderFooterMiniPreview.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderFooterPreview.svelte
  sites/geohub/src/lib/server/StorymapManager.ts
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: UI/UX

#3913 fix: added size prop (small or normal) to chapter. small is for mini …
  .changeset/stupid-beans-share.md
  packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
  packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
  sites/geohub/src/components/pages/storymap/ImageUploader.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: bug, UI/UX

#3914 fix: changed margin of page contents as 48px (3rem)
  .changeset/slow-spies-float.md
  sites/geohub/src/routes/(app)/data/+page.svelte
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte
  sites/geohub/src/routes/(app)/data/[id]/+page.svelte
  sites/geohub/src/routes/(app)/data/[id]/style/edit/+page.svelte
  sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
  sites/geohub/src/routes/(app)/data/upload/+page.svelte
  sites/geohub/src/routes/(app)/license/+page.svelte
  sites/geohub/src/routes/(app)/management/+page.svelte
  sites/geohub/src/routes/(app)/management/pgtileserv/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/api/[id]/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/api/[id]/[collection]/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte
  sites/geohub/src/routes/(app)/maps/+page.svelte
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
  sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte
  sites/geohub/src/routes/(app)/tools/+page.svelte
Labels: UI/UX

#3915 feat: added duplicate storymap button
  .changeset/chilly-schools-smell.md
  sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte
Labels: enhancement, UI/UX

#3916 fix: redesigned slide progress bar for storymaps
  .changeset/wicked-rules-compete.md
  packages/svelte-maplibre-storymap/package.json
  packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
  packages/svelte-maplibre-storymap/src/routes/+page.server.ts
  pnpm-lock.yaml
Labels: UI/UX

#3917 fix: removed @types/svelte-range-slider-pips from storymap plugin
  packages/svelte-maplibre-storymap/package.json
  pnpm-lock.yaml
Labels: bug

#3918 fix: fixed responsive design of storymap
  .changeset/tough-files-leave.md
  packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
  packages/svelte-maplibre-storymap/src/lib/css/dark/header.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/header.scss
Labels: bug, UI/UX

#3919 Feat/3906 switch
  .changeset/big-brooms-talk.md
  .changeset/rare-cherries-pay.md
  .changeset/shiny-dolphins-hug.md
  .github/workflows/ci.yml
  packages/svelte-undp-components/package.json
  packages/svelte-undp-components/src/lib/components/PropertyEditor.svelte
  packages/svelte-undp-design/src/lib/Switch/Switch.stories.ts
  packages/svelte-undp-design/src/lib/Switch/Switch.svelte
  packages/svelte-undp-design/src/lib/css/switch.min.css
  packages/svelte-undp-design/src/lib/index.ts
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/pages/map/layers/vector/VectorFilter.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterLayerEventEditor.svelte
  sites/geohub/src/components/pages/storymap/StorymapFooterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
  sites/geohub/src/routes/(app)/+layout@.svelte
  sites/geohub/src/routes/(app)/settings/+page.svelte
  sites/geohub/src/routes/(map)/maps/+layout.svelte
Labels: bug, enhancement, UI/UX

#3901 feat: add sky color of maplibre
  .changeset/ten-terms-dance.md
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/pages/data/datasets/DatasetMapView.svelte
  sites/geohub/src/components/pages/map/Map.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterPreview.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderFooterPreview.svelte
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/ceei/+page.svelte
  sites/geohub/src/routes/(map)/dashboards/electricity/+page.svelte
Labels: enhancement

#3884 fix: added storymaps link to header and footer
  .changeset/clean-waves-clean.md
  .changeset/cool-cherries-type.md
  .changeset/hungry-beds-approve.md
  packages/svelte-undp-design/src/lib/Footer/Footer.stories.ts
  packages/svelte-undp-design/src/lib/Footer/Footer.svelte
  packages/svelte-undp-design/src/lib/PagewideFeaturedContentCard/PagewideFeaturedContentCard.stories.ts
  packages/svelte-undp-design/src/lib/PagewideFeaturedContentCard/PagewideFeaturedContentCard.svelte
  packages/svelte-undp-design/src/lib/css/footer.min.css
  packages/svelte-undp-design/src/lib/css/page-wide-card.min.css
  packages/svelte-undp-design/src/lib/index.ts
  packages/svelte-undp-design/static/media/Pagewide.7759e116.jpg
  sites/geohub/src/lib/server/config/FooterItems.ts
  sites/geohub/src/routes/(app)/+page.svelte
  sites/geohub/src/routes/(app)/tools/+page.svelte
  sites/geohub/src/routes/+layout.server.ts
  sites/geohub/static/assets/storymap-screenshot.webp
Labels: UI/UX

#3922 feat: added create storymap button in map page.
  .changeset/sharp-cherries-help.md
  sites/geohub/src/components/pages/storymap/StorymapHeaderFooterMiniPreview.svelte
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.server.ts
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: enhancement

#3930 chore: updated dependencies of static api
  sites/static-image-api/package-lock.json
  sites/static-image-api/package.json
Labels: enhancement

#3931 fix: hide icon as default for ModalNotification component. Also, changed button color.
  .changeset/eleven-seals-fly.md
  packages/svelte-undp-components/src/lib/components/ModalNotification.stories.ts
  packages/svelte-undp-components/src/lib/components/ModalNotification.svelte
  packages/svelte-undp-components/src/lib/components/Notification.stories.ts
  packages/svelte-undp-components/src/lib/components/Notification.svelte
Labels: bug, UI/UX

#3948 fix: changed size of segment buttons to normal for slide transition.
  .changeset/eight-islands-drop.md
  sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
Labels: bug

#3949 fix: changed fontawesome to material icon for Help component.
  .changeset/grumpy-trains-learn.md
  packages/svelte-undp-components/src/lib/components/FieldControl.stories.ts
  packages/svelte-undp-components/src/lib/components/FieldControl.svelte
  packages/svelte-undp-components/src/lib/components/Help.stories.ts
  packages/svelte-undp-components/src/lib/components/Help.svelte
Labels: UI/UX

#3950 fix: change font of tabs to bold and transform to uppercase for story…
  .changeset/quick-points-dance.md
  sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
Labels: bug, UI/UX

#3951 fix: changed Card tab design of storymap editor
  .changeset/olive-ways-try.md
  sites/geohub/src/components/pages/storymap/ImageUploader.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapHeaderEdit.svelte
Labels: UI/UX

#3952 fix: changed button style to outlined except primary button.
  .changeset/odd-colts-reply.md
  documentation/docs/assets/data/publish_8.png
  documentation/docs/assets/sharing/share_map_1.png
  documentation/docs/assets/sharing/share_map_2.png
  documentation/docs/assets/sharing/share_map_3.png
  documentation/docs/assets/sharing/share_map_5.png
  documentation/docs/assets/sharing/share_map_6.png
  sites/geohub/src/components/pages/data/datasets/DatasetPreview.svelte
  sites/geohub/src/components/pages/data/datasets/UserPermission.svelte
  sites/geohub/src/routes/(app)/data/[id]/+page.svelte
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
  sites/geohub/src/routes/(app)/storymaps/[id]/+page.svelte
Labels: bug, UI/UX

#3953 fix: redesigned layer visibility component for storymap editor. also removed onExit.
  .changeset/lucky-weeks-thank.md
  sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterLayerEventEditor.svelte
  sites/geohub/src/components/util/OpacityEditor.svelte
Labels: bug, UI/UX

#3956 fix: scroll problem of storymap preview is fixed now. but progress bar was removed from preview since it has problem for preview.
  .changeset/heavy-news-serve.md
  .changeset/tough-cycles-hug.md
  packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/+layout@.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: bug

#3958 fix: only update the slide mini preview in sidebar which is updated by slide setting.
  .changeset/beige-hornets-flow.md
  .changeset/gentle-trainers-own.md
  packages/svelte-undp-design/src/lib/Switch/Switch.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterLayerEventEditor.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
  sites/geohub/src/lib/helper/getMapImageFromStyle.ts
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: bug

#3959 fix: added maptiler geocoder for maplocation prop of storymap editor.
  .changeset/violet-pugs-shake.md
  sites/geohub/src/components/pages/storymap/MapLocationSelector.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/+layout.server.ts
Labels: bug, UI/UX

#3962 fix: only update preview in sidebar if chapter has any changes.
  .changeset/short-apples-exercise.md
  sites/geohub/src/components/pages/storymap/MapLocationSelector.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: bug

#3970 Feat/add storymap setting
  .changeset/heavy-eggs-hunt.md
  sites/geohub/src/lib/config/DefaultUserConfig/StorymapChapterCardAlignment.ts
  sites/geohub/src/lib/config/DefaultUserConfig/StorymapChapterNavigationControlPosition.ts
  sites/geohub/src/lib/config/DefaultUserConfig/StorymapChapterTransitionAnimation.ts
  sites/geohub/src/lib/config/DefaultUserConfig/index.ts
  sites/geohub/src/routes/(app)/settings/+page.server.ts
  sites/geohub/src/routes/(app)/settings/+page.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: enhancement

#3971 fix: set max-width as 512px for storymap slide card.
  .changeset/lucky-crabs-remember.md
  packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
  sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
  sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte
Labels: bug, UI/UX

#3974 fix: setSky will add sky spec to style json itself. this affects checking whether style is changed. remove sky prop before saving and exclude it from checking.
  .changeset/proud-beans-applaud.md
  sites/geohub/src/lib/helper/isStyleChanged.ts
  sites/geohub/src/routes/api/style/+server.ts
Labels: bug

#3972 feat: added /style/{id}/legend endpoint for raster layers (vector is …
  .changeset/sweet-ears-laugh.md
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/lib/helper/getDecimalPlaces.ts
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/lib/server/SvgLegendCreator.ts
  sites/geohub/src/lib/server/helpers/clipSpriteServer.ts
  sites/geohub/src/lib/server/helpers/generateLegendFromStyle.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/routes/api/style/[id]/legend/+server.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: enhancement, backend

#3977 fix: changed canvas to canvas@next
  .changeset/late-jobs-look.md
  docker/docker-build-prod.sh
  pnpm-lock.yaml
  sites/geohub/package.json
Labels: bug

#3978 fix: because server is down, removed node-canvas temporally.
  .changeset/swift-buses-love.md
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/lib/server/helpers/generateLegendFromStyle.ts
  sites/geohub/src/lib/server/helpers/index.ts
Labels: bug

#3981 fix: use pngjs to crop sprite image instead of using image-clipper with node-canvas
  .changeset/healthy-lemons-rest.md
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/lib/server/SvgLegendCreator.ts
  sites/geohub/src/lib/server/helpers/clipSpriteServer.ts
  sites/geohub/src/lib/server/helpers/generateLegendFromStyle.ts
Labels: bug

#3980 fix: Use legend endpoint for the control of map page
  .changeset/late-rings-tease.md
  .changeset/mighty-crews-push.md
  .changeset/wise-gifts-refuse.md
  packages/svelte-static-image-controls/src/lib/MaplibreStaticImageControl.svelte
  packages/svelte-undp-components/src/lib/components/FloatingPanel.stories.ts
  packages/svelte-undp-components/src/lib/components/FloatingPanel.svelte
  packages/svelte-undp-components/src/lib/components/OpacityEditor.stories.ts
  packages/svelte-undp-components/src/lib/components/OpacityEditor.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
  sites/geohub/src/components/pages/map/layers/header/VisibilityButton.svelte
  sites/geohub/src/components/pages/map/plugins/MaplibreLegendControl.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterLayerEventEditor.svelte
  sites/geohub/src/components/util/OpacityEditor.svelte
  sites/geohub/src/lib/server/SvgLegendCreator.ts
  sites/geohub/src/lib/server/helpers/generateLegendFromStyle.ts
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
  sites/geohub/src/routes/api/style/[id]/legend/+server.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: enhancement

#3983 feat: moved MaplibreLegendControl from geohub to the package, and added legend to storymap component.
  .changeset/heavy-mangos-reply.md
  .changeset/modern-flowers-roll.md
  backends/database/database.vuerd.json
  backends/database/geohub-database-erd.png
  backends/database/geohub-database.sql
  packages/svelte-maplibre-storymap/package.json
  packages/svelte-maplibre-storymap/src/lib/MaplibreLegendControl.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
  packages/svelte-maplibre-storymap/src/lib/helpers.ts
  packages/svelte-maplibre-storymap/src/lib/index.ts
  packages/svelte-maplibre-storymap/src/lib/interfaces/StoryMapChapter.ts
  packages/svelte-maplibre-storymap/src/lib/stores/map.ts
  packages/svelte-maplibre-storymap/src/routes/+layout.svelte
  packages/svelte-maplibre-storymap/src/routes/+page.server.ts
  packages/svelte-maplibre-storymap/vite.config.ts
  pnpm-lock.yaml
  sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte
  sites/geohub/src/lib/server/StorymapManager.ts
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
Labels: enhancement, UI/UX

#3986 fix: changed cancel button style for ModalNotification to align with …
  .changeset/three-gorillas-unite.md
  packages/svelte-undp-components/src/lib/components/ModalNotification.svelte
Labels: bug, UI/UX

#3987 fix: changed font weight to normal for segment buttons used in storymap.
  .changeset/flat-cows-smash.md
  sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
  sites/geohub/src/routes/(app)/settings/+page.svelte
Labels: bug, UI/UX

#3988 fix: added margin-right for opacity button in OpacityEditor component…
  .changeset/perfect-eggs-provide.md
  packages/svelte-maplibre-storymap/src/lib/MaplibreLegendControl.svelte
  packages/svelte-undp-components/src/lib/components/OpacityEditor.svelte
Labels: bug, UI/UX

#3989 fix: changed slide color to blue-300 of UNDP design system.
  .changeset/two-dolphins-glow.md
  packages/svelte-undp-components/src/lib/components/Slider.svelte
Labels: bug, UI/UX

#3990 fix: update card template style on mini preview if template of storym…
  .changeset/fuzzy-wolves-smoke.md
  sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
Labels: bug

#3993 fix: changed order of buttons in ModalNotification. Bring cancel butt…
  .changeset/proud-llamas-walk.md
  packages/svelte-undp-components/src/lib/components/ModalNotification.svelte
  packages/svelte-undp-components/vite.config.ts
Labels: bug, UI/UX

#3924 fix: show confirmation dialog with access level control after clickin…
  .changeset/green-bulldogs-double.md
  .changeset/little-falcons-help.md
  packages/svelte-undp-components/src/lib/components/ModalTemplate.svelte
  packages/svelte-undp-components/src/lib/components/Notification.svelte
  sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
  sites/geohub/src/components/util/AccessLevelSwitcher.svelte
  sites/geohub/src/routes/(map)/maps/+layout.svelte
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: bug, UI/UX

#3994 fix: fixed css for full alignment, and redesigned card alignment and full width
  .changeset/calm-maps-marry.md
  .changeset/ten-gorillas-occur.md
  packages/svelte-maplibre-storymap/src/lib/css/dark/chapter.scss
  packages/svelte-maplibre-storymap/src/lib/css/light/chapter.scss
  sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte
Labels: bug, UI/UX

#3995 fix: set untitle as default value for title of storymap
  .changeset/neat-windows-train.md
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.svelte
Labels: bug, UI/UX

#4004 fix: Use PNGJS to force recoloring sprite icon image by color, and em…
  .changeset/fair-mugs-rhyme.md
  sites/geohub/src/lib/server/SvgLegendCreator.ts
  sites/geohub/src/lib/server/helpers/generateLegendFromStyle.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/lib/server/helpers/recolorPngDataUrl.ts
Labels: bug

#4005 fix: generate maplibre hillshade legend. and use legend api from sidebar of map edit page.
  .changeset/heavy-rocks-prove.md
  sites/geohub/src/components/maplibre/circle/CircleRadius.svelte
  sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
  sites/geohub/src/components/maplibre/fill-extrusion/VectorFillExtrusion.svelte
  sites/geohub/src/components/maplibre/fill/VectorPolygon.svelte
  sites/geohub/src/components/maplibre/heatmap/HeatmapColor.svelte
  sites/geohub/src/components/maplibre/heatmap/VectorHeatmap.svelte
  sites/geohub/src/components/maplibre/line/VectorLine.svelte
  sites/geohub/src/components/maplibre/raster/RasterSimpleLegend.svelte
  sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
  sites/geohub/src/components/maplibre/vector/VectorValueClassification.svelte
  sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
  sites/geohub/src/components/pages/map/layers/LayerEdit.svelte
  sites/geohub/src/components/pages/map/layers/LayerLegend.svelte
  sites/geohub/src/components/pages/map/layers/LayerList.svelte
  sites/geohub/src/components/pages/map/layers/raster/RasterSimpleLayer.svelte
  sites/geohub/src/components/pages/map/layers/vector/VectorSimpleLayer.svelte
  sites/geohub/src/lib/server/helpers/generateLegendFromStyle.ts
  sites/geohub/src/routes/api/style/legend/+server.ts
  sites/geohub/src/stores/index.ts
  sites/geohub/src/stores/legendReadonly.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: bug

#4006 fix: hide opacity slider for hillshade layer
  .changeset/ten-horses-enjoy.md
  packages/svelte-maplibre-storymap/src/lib/MaplibreLegendControl.svelte
  sites/geohub/src/components/maplibre/vector/VectorSimpleColorLegend.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterLayerEventEditor.svelte
Labels: bug

#4008 Fix/show loader only layers
  .changeset/nice-rice-tease.md
  .changeset/weak-cycles-drum.md
  packages/svelte-undp-components/src/lib/components/FloatingPanel.svelte
  sites/geohub/src/components/maplibre/hillshade/Hillshade.svelte
  sites/geohub/src/components/pages/map/Content.svelte
  sites/geohub/src/components/pages/map/layers/LayerEdit.svelte
  sites/geohub/src/components/pages/map/layers/LayerInfo.svelte
  sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
  sites/geohub/src/routes/(map)/maps/+layout.svelte
  sites/geohub/src/stores/editingLayer.ts
Labels: bug

#4009 fix: toggle layout.visibility instead of opacity for hillshade layer …
  .changeset/gold-cheetahs-provide.md
  packages/svelte-maplibre-storymap/src/lib/MaplibreLegendControl.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMapChapter.svelte
  packages/svelte-maplibre-storymap/src/lib/helpers.ts
  sites/geohub/src/components/pages/storymap/MapLocationSelector.svelte
  sites/geohub/src/components/pages/storymap/StorymapChapterMiniPreview.svelte
  sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte
Labels: bug

#4011 Feat/rename layer title
  .changeset/tiny-spies-appear.md
  sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
  sites/geohub/src/components/pages/map/layers/header/DeleteMenu.svelte
  sites/geohub/src/components/pages/map/layers/header/VisibilityButton.svelte
Labels: enhancement

#4012 fix: removed legend component from sort layer component and make it s…
  .changeset/fifty-oranges-jam.md
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/pages/map/layers/header/Legend.svelte
  sites/geohub/src/components/pages/map/layers/order/SortLayer.svelte
Labels: bug, refactor

#4013 Feat/sprite image endpoint
  .changeset/nine-walls-yawn.md
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/maplibre/symbol/IconImage.svelte
  sites/geohub/src/components/maplibre/symbol/IconImagePicker.svelte
  sites/geohub/src/components/maplibre/symbol/IconSize.svelte
  sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
  sites/geohub/src/components/pages/map/Map.svelte
  sites/geohub/src/lib/helper/clipSprite.test.ts
  sites/geohub/src/lib/helper/clipSprite.ts
  sites/geohub/src/lib/helper/getSpriteImageIist.ts
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/lib/server/helpers/clipSprite.ts
  sites/geohub/src/lib/server/helpers/generateLegendFromStyle.ts
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/routes/(app)/maps/+page.svelte
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
  sites/geohub/src/routes/(app)/settings/+page.svelte
  sites/geohub/src/routes/(map)/maps/+layout.svelte
  sites/geohub/src/routes/api/mapstyle/sprite/images/[[id]]/+server.ts
  sites/geohub/src/stores/index.ts
  sites/geohub/src/stores/spriteImageList.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: bug, enhancement

#4014 Refactor/move icon picker
  .changeset/curly-news-shake.md
  packages/svelte-undp-components/src/lib/components/IconImage.stories.ts
  packages/svelte-undp-components/src/lib/components/IconImage.svelte
  packages/svelte-undp-components/src/lib/components/IconImagePicker.svelte
  packages/svelte-undp-components/src/lib/components/IconImagePickerCard.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  packages/svelte-undp-components/src/lib/util/clean.ts
  packages/svelte-undp-components/vite.config.ts
  sites/geohub/src/components/maplibre/symbol/IconImage.svelte
  sites/geohub/src/components/maplibre/symbol/IconImagePicker.test.ts
  sites/geohub/src/components/maplibre/symbol/IconImagePickerCard.test.ts
  sites/geohub/src/components/maplibre/symbol/IconSize.svelte
  sites/geohub/src/lib/server/helpers/clipSprite.ts
  sites/geohub/src/lib/types/SpriteImage.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/(app)/settings/+page.server.ts
  sites/geohub/src/routes/(app)/settings/+page.svelte
  sites/geohub/src/routes/(app)/settings/+page.ts
  sites/geohub/src/routes/api/mapstyle/sprite/images/[[id]]/+server.ts
Labels: refactor

#4015 Fix/header icon size
  .changeset/curly-crews-unite.md
  sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
  sites/geohub/src/lib/server/SvgLegendCreator.ts
Labels: bug

#4018 fix: collapse storymap legend in small screen as default
  .changeset/tidy-jokes-compare.md
  packages/svelte-maplibre-storymap/src/lib/MaplibreLegendControl.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
Labels: bug

#4019 Fix/redesign storymap portal
  .changeset/cool-icons-cheer.md
  .changeset/thirty-hounds-lie.md
  packages/svelte-undp-components/src/lib/components/HeroHeader.svelte
  sites/geohub/src/components/pages/storymap/StorymapTable.svelte
  sites/geohub/src/components/util/AccessLevelSwitcher.svelte
  sites/geohub/src/lib/server/StorymapManager.ts
  sites/geohub/src/routes/(app)/storymaps/+page.svelte
  sites/geohub/src/routes/api/storymaps/+server.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: UI/UX

#4022 refactor: merged +page.ts to +page.server.ts for setting page title and description.
  .changeset/gentle-hats-smile.md
  sites/geohub/src/routes/(app)/+layout.server.ts
  sites/geohub/src/routes/(app)/+page.server.ts
  sites/geohub/src/routes/(app)/+page.ts
  sites/geohub/src/routes/(app)/data/+page.server.ts
  sites/geohub/src/routes/(app)/data/+page.ts
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.server.ts
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.ts
  sites/geohub/src/routes/(app)/data/[id]/+page.server.ts
  sites/geohub/src/routes/(app)/data/[id]/+page.ts
  sites/geohub/src/routes/(app)/data/[id]/style/edit/+page.server.ts
  sites/geohub/src/routes/(app)/data/[id]/style/edit/+page.ts
  sites/geohub/src/routes/(app)/data/upload/+page.server.ts
  sites/geohub/src/routes/(app)/data/upload/+page.ts
  sites/geohub/src/routes/(app)/license/+page.server.ts
  sites/geohub/src/routes/(app)/license/+page.ts
  sites/geohub/src/routes/(app)/management/pgtileserv/+page.server.ts
  sites/geohub/src/routes/(app)/management/pgtileserv/+page.ts
  sites/geohub/src/routes/(app)/management/stac/api/[id]/+page.server.ts
  sites/geohub/src/routes/(app)/management/stac/api/[id]/+page.ts
  sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.server.ts
  sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.ts
  sites/geohub/src/routes/(app)/maps/+page.server.ts
  sites/geohub/src/routes/(app)/maps/+page.ts
  sites/geohub/src/routes/(app)/maps/[id]/+page.server.ts
  sites/geohub/src/routes/(app)/maps/[id]/+page.ts
  sites/geohub/src/routes/(app)/settings/+page.server.ts
  sites/geohub/src/routes/(app)/settings/+page.ts
  sites/geohub/src/routes/(app)/storymaps/+page.server.ts
  sites/geohub/src/routes/(app)/storymaps/+page.ts
  sites/geohub/src/routes/(app)/storymaps/[id]/+page.server.ts
  sites/geohub/src/routes/(app)/storymaps/[id]/+page.ts
  sites/geohub/src/routes/(app)/tools/+page.server.ts
  sites/geohub/src/routes/(app)/tools/+page.ts
  sites/geohub/src/routes/(map)/maps/[id]/edit/+page.server.ts
  sites/geohub/src/routes/(map)/maps/[id]/edit/+page.ts
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/+layout.server.ts
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.server.ts
  sites/geohub/src/routes/(storymap)/storymaps/[[id]]/edit/+page.ts
  sites/geohub/src/routes/(storymap)/storymaps/[id]/viewer/+page.server.ts
  sites/geohub/src/routes/(storymap)/storymaps/[id]/viewer/+page.ts
Labels: refactor

#4025 feat: show changelog from user account menu
  .changeset/brown-bobcats-rush.md
  .changeset/slimy-dogs-behave.md
  packages/svelte-undp-components/src/lib/components/ModalTemplate.svelte
  sites/geohub/.gitignore
  sites/geohub/package.json
  sites/geohub/src/components/header/UserAccount.svelte
Labels: enhancement

#4027 fix: redesigned map portal
  .changeset/thin-owls-crash.md
  sites/geohub/src/components/pages/home/MapStyleCardList.svelte
  sites/geohub/src/components/pages/storymap/GeoHubMapSelector.svelte
  sites/geohub/src/components/pages/storymap/StorymapTable.svelte
  sites/geohub/src/routes/(app)/maps/+page.svelte
  sites/geohub/src/routes/(app)/storymaps/+page.svelte
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: bug, UI/UX

#4034 fix: added /api/licenses endpoint to avoid hard coded license info.
  .changeset/giant-fishes-buy.md
  backends/database/database.vuerd.json
  backends/database/geohub-database-erd.png
  backends/database/geohub-database.sql
  backends/database/init.sh
  backends/database/sql/insert-license.sql
  sites/geohub/src/lib/types/License.ts
  sites/geohub/src/lib/types/index.ts
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte
  sites/geohub/src/routes/api/licenses/+server.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: refactor

#4036 fix: renamed title of maps and storymaps page, align position of pagination left
  .changeset/twenty-otters-share.md
  documentation/docs/assets/visualization/maps_new_map.png
  sites/geohub/src/components/pages/home/MapStyleCardList.svelte
  sites/geohub/src/components/pages/storymap/StorymapTable.svelte
  sites/geohub/src/routes/(app)/maps/+page.svelte
  sites/geohub/src/routes/(app)/storymaps/+page.svelte
Labels: UI/UX

#4041 fix: show zero value for minimum label of raster linear legend.
  .changeset/lovely-brooms-juggle.md
  sites/geohub/src/lib/server/SvgLegendCreator.ts
Labels: bug

#4043 fix: fixed layout collapse of map page in responsive.
  .changeset/healthy-peaches-live.md
  sites/geohub/src/components/pages/home/MapStyleCardList.svelte
Labels: bug

#4050 fix: when users go back to storymap header, restore all style and legend setting to be initial state.
  .changeset/nine-lobsters-chew.md
  packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
Labels: bug

#4051 fix: allow users to save storymap without chapters.
  .changeset/curvy-shoes-sleep.md
  .changeset/healthy-coats-impress.md
  .changeset/hip-trains-sell.md
  .changeset/hungry-bikes-beg.md
  packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
  packages/svelte-undp-components/src/lib/components/Accordion.stories.ts
  packages/svelte-undp-components/src/lib/components/Accordion.svelte
  packages/svelte-undp-components/src/lib/util/clean.ts
  sites/geohub/src/components/pages/storymap/StorymapChapterEdit.svelte
  sites/geohub/src/components/pages/storymap/StorymapMetaEdit.svelte
  sites/geohub/src/lib/server/StorymapManager.ts
  sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+layout.server.ts
  sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.server.ts
  sites/geohub/src/routes/(app)/storymaps/[[id]]/edit/+page.svelte
  sites/geohub/src/routes/api/storymaps/+server.ts
Labels: bug, UI/UX

#4052 fix: hide invisilble layer and removed opacity/visibility buttons for storymap legend
  .changeset/healthy-fans-remember.md
  packages/svelte-maplibre-storymap/src/lib/MaplibreLegendControl.svelte
  packages/svelte-maplibre-storymap/src/lib/StoryMap.svelte
  sites/geohub/src/components/pages/storymap/StorymapEditPreview.svelte
Labels: bug, UI/UX
