Repository UNDP-Data/geohub, pull requests merged in 2024-03, with the labels that each got.

#3006 feat: implemented /api/token to issue an access token for GeoHub API. The token can be used within /api endpoints by adding 'token' query param.
  .changeset/wild-bottles-join.md
  docker/Dockerfile
  docker/Dockerfile.production
  docker/docker-compose.yml
  pnpm-lock.yaml
  sites/geohub/.env.docker.example
  sites/geohub/.env.example
  sites/geohub/package.json
  sites/geohub/src/hooks.server.ts
  sites/geohub/src/lib/config/AppConfig/DatasetSearchQueryParams.ts
  sites/geohub/src/lib/server/token.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/token/+server.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: enhancement, backend

#3012 fix: Update /api/datasets/+server.ts to remove console.log
  sites/geohub/src/routes/api/datasets/+server.ts
Labels: bug

#3016 fix: remove from app.html
  .changeset/fair-flowers-thank.md
  sites/geohub/src/app.html
Labels: bug

#3014 feat: add `/tools` page to allow users to explore datasets by tools
  .changeset/eighty-wolves-learn.md
  sites/geohub/src/components/maplibre/raster/RasterAlgorithmExplorer.svelte
  sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
  sites/geohub/src/lib/config/AppConfig/FooterItems.ts
  sites/geohub/src/routes/(app)/+page.svelte
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte
  sites/geohub/src/routes/(app)/tools/+page.server.ts
  sites/geohub/src/routes/(app)/tools/+page.svelte
  sites/geohub/src/routes/(app)/tools/+page.ts
Labels: enhancement

#3019 fix: Remove unused code from svelte-undp-design package
  .changeset/mighty-poets-provide.md
  packages/svelte-undp-design/package.json
Labels: bug

#3029 deploy docker image of static api to GHCR too
  .github/workflows/ci.yml
Labels: docker

#3032 fix: switch static image api from GHCR.fixed bug of entrypoint for do…
  docker/docker-compose.yml
  docker/static-api-entrypoint.sh
Labels: bug, docker

#3037 fix: show band description after band name in raster band selectbox if applicable
  .changeset/light-monkeys-crash.md
  sites/geohub/src/components/pages/data/datasets/RasterBandSelectbox.svelte
Labels: bug

#3040 refactor: moved Help component and initTippy & initTooltipTippy to svelte-undp-components package
  .changeset/tough-donkeys-carry.md
  packages/svelte-undp-components/package.json
  packages/svelte-undp-components/src/lib/components/Help.stories.ts
  packages/svelte-undp-components/src/lib/components/Help.svelte
  packages/svelte-undp-components/src/lib/components/Help.test.ts
  packages/svelte-undp-components/src/lib/components/index.ts
  packages/svelte-undp-components/src/lib/index.ts
  packages/svelte-undp-components/src/lib/util/index.ts
  packages/svelte-undp-components/src/lib/util/initTippy.ts
  packages/svelte-undp-components/src/stories/Introduction.mdx
  pnpm-lock.yaml
  sites/geohub/src/components/header/UserAccount.svelte
  sites/geohub/src/components/maplibre/LegendColorMapRow.svelte
  sites/geohub/src/components/maplibre/MaplibreColorPicker.svelte
  sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
  sites/geohub/src/components/maplibre/fill-extrusion/VectorFillExtrusion.svelte
  sites/geohub/src/components/maplibre/fill/VectorPolygon.svelte
  sites/geohub/src/components/maplibre/heatmap/HeatmapColorRow.svelte
  sites/geohub/src/components/maplibre/heatmap/VectorHeatmap.svelte
  sites/geohub/src/components/maplibre/hillshade/Hillshade.svelte
  sites/geohub/src/components/maplibre/line/VectorLine.svelte
  sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
  sites/geohub/src/components/maplibre/raster/RasterLegendEdit.svelte
  sites/geohub/src/components/maplibre/symbol/IconImage.svelte
  sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
  sites/geohub/src/components/maplibre/vector/VectorSimulationAccordion.svelte
  sites/geohub/src/components/pages/data/datasets/PublishedDatasetRow.svelte
  sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
  sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
  sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRowDetail.svelte
  sites/geohub/src/components/pages/map/data/AddLayerButton.svelte
  sites/geohub/src/components/pages/map/data/DataCard.svelte
  sites/geohub/src/components/pages/map/data/RasterAlgorithmExplorerButton.svelte
  sites/geohub/src/components/pages/map/data/StacExplorerButton.svelte
  sites/geohub/src/components/pages/map/layers/LayerInfo.svelte
  sites/geohub/src/components/pages/map/layers/LayerList.svelte
  sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
  sites/geohub/src/components/pages/map/layers/header/VisibilityButton.svelte
  sites/geohub/src/components/pages/map/layers/order/LayerOrderPanelButton.svelte
  sites/geohub/src/components/pages/map/layers/order/SortLayer.svelte
  sites/geohub/src/components/pages/map/layers/vector/VectorFilter.svelte
  sites/geohub/src/components/pages/map/layers/vector/VectorLabelPanel.svelte
  sites/geohub/src/components/pages/map/plugins/LayerVisibilitySwitcher.svelte
  sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
  sites/geohub/src/components/pages/map/plugins/MaplibreLegendControl.svelte
  sites/geohub/src/components/pages/map/plugins/StyleShareControl.svelte
  sites/geohub/src/components/util/Accordion.svelte
  sites/geohub/src/components/util/ColorMapPicker.svelte
  sites/geohub/src/components/util/CountryPicker.svelte
  sites/geohub/src/components/util/DataProviderPicker.svelte
  sites/geohub/src/components/util/FieldControl.svelte
  sites/geohub/src/components/util/PanelButton.svelte
  sites/geohub/src/components/util/SdgPicker.svelte
  sites/geohub/src/components/util/TagInput.svelte
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/routes/(app)/data/+page.svelte
  sites/geohub/src/routes/(app)/data/upload/+page.svelte
  sites/geohub/src/routes/(app)/settings/+page.svelte
Labels: refactor

#3042 doc: Add componentslink to footer
  .changeset/few-ladybugs-drop.md
  packages/svelte-undp-design/.storybook/main.ts
  packages/svelte-undp-design/src/lib/Accordion/Accordion.stories.ts
  packages/svelte-undp-design/src/lib/Breadcrumbs/Breadcrumbs.stories.ts
  packages/svelte-undp-design/src/lib/Button/Button.stories.ts
  packages/svelte-undp-design/src/lib/Card/Card.stories.ts
  packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.stories.ts
  packages/svelte-undp-design/src/lib/Checkbox/Checkbox.stories.ts
  packages/svelte-undp-design/src/lib/CtaLink/CtaLink.stories.ts
  packages/svelte-undp-design/src/lib/DefaultLink/DefaultLink.stories.ts
  packages/svelte-undp-design/src/lib/Download/Download.stories.ts
  packages/svelte-undp-design/src/lib/FluidCarousel/FluidCarousel.stories.ts
  packages/svelte-undp-design/src/lib/Footer/Footer.stories.ts
  packages/svelte-undp-design/src/lib/Header/Header.stories.ts
  packages/svelte-undp-design/src/lib/Introduction.mdx
  packages/svelte-undp-design/src/lib/Loader/Loader.stories.ts
  packages/svelte-undp-design/src/lib/MultiSelect/MultiSelect.stories.ts
  packages/svelte-undp-design/src/lib/Pagination/Pagination.stories.ts
  packages/svelte-undp-design/src/lib/Radios/Radios.stories.ts
  packages/svelte-undp-design/src/lib/SearchExpand/SearchExpand.stories.ts
  packages/svelte-undp-design/src/lib/Select/Select.stories.ts
  packages/svelte-undp-design/src/lib/Sidebar/Sidebar.stories.ts
  packages/svelte-undp-design/src/lib/Stats/Stats.stories.ts
  packages/svelte-undp-design/src/lib/Tabs/Tabs.stories.ts
  packages/svelte-undp-design/src/lib/TextInput/TextInput.stories.ts
  sites/geohub/src/lib/config/AppConfig/FooterItems.ts
Labels: documentation

#3043 refactor: deleted unused components of StyleControlGroup and ToggleOptions
  sites/geohub/src/components/maplibre/raster/RasterResampling.svelte
  sites/geohub/src/components/util/StyleControlGroup.svelte
  sites/geohub/src/components/util/StyleControlGroup.test.ts
  sites/geohub/src/components/util/ToggleOptions.svelte
  sites/geohub/src/lib/types/ToggleOption.ts
  sites/geohub/src/lib/types/index.ts
Labels: refactor

#3044 refactor: moved breadcrumbs to svelte-undp-components
  .changeset/ninety-baboons-cross.md
  .changeset/tiny-wombats-knock.md
  packages/svelte-undp-components/.storybook/preview-head.html
  packages/svelte-undp-components/src/lib/components/Breadcrumbs.stories.ts
  packages/svelte-undp-components/src/lib/components/Breadcrumbs.svelte
  packages/svelte-undp-components/src/lib/components/Help.mdx
  packages/svelte-undp-components/src/lib/components/Help.stories.ts
  packages/svelte-undp-components/src/lib/components/Notification.stories.ts
  packages/svelte-undp-components/src/lib/components/NumberInput.stories.ts
  packages/svelte-undp-components/src/lib/components/index.ts
  packages/svelte-undp-components/src/stories/Introduction.mdx
  pnpm-lock.yaml
  sites/geohub/src/routes/(app)/api/+page.svelte
  sites/geohub/src/routes/(app)/dashboards/+page.svelte
  sites/geohub/src/routes/(app)/data/+page.svelte
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte
  sites/geohub/src/routes/(app)/data/[id]/+page.svelte
  sites/geohub/src/routes/(app)/data/[id]/style/edit/+page.svelte
  sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
  sites/geohub/src/routes/(app)/data/upload/+page.svelte
  sites/geohub/src/routes/(app)/management/+page.svelte
  sites/geohub/src/routes/(app)/management/pgtileserv/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/api/[id]/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/api/[id]/[collection]/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte
  sites/geohub/src/routes/(app)/maps/+page.svelte
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
  sites/geohub/src/routes/(app)/settings/+page.svelte
  sites/geohub/src/routes/(app)/tools/+page.svelte
Labels: refactor

#3046 Delete packages/svelte-undp-components/src/lib/components/Help.mdx
  packages/svelte-undp-components/src/lib/components/Help.mdx
Labels: bug, documentation

#3058 refactor: moved SegmentButtons component to svelte-undp-component package
  .changeset/real-birds-march.md
  .changeset/silent-fireants-wash.md
  packages/svelte-undp-components/src/lib/components/SegmentButtons.stories.ts
  packages/svelte-undp-components/src/lib/components/SegmentButtons.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
  sites/geohub/src/components/util/AccessLevelSwitcher.svelte
  sites/geohub/src/components/util/stac/StacApiExplorer.svelte
  sites/geohub/src/components/util/stac/StacCollectionMap.svelte
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte
  sites/geohub/src/routes/(app)/settings/+page.svelte
Labels: refactor

#3060 refactor: moved ShowDetails component to svelte-undp-component
  .changeset/grumpy-eels-wash.md
  .changeset/tender-oranges-study.md
  packages/svelte-undp-components/src/lib/components/ShowDetails.stories.ts
  packages/svelte-undp-components/src/lib/components/ShowDetails.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  packages/svelte-undp-components/src/lib/util/handleEnterKey.ts
  packages/svelte-undp-components/src/lib/util/index.ts
  sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
  sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
  sites/geohub/src/components/pages/map/plugins/StyleShare.svelte
  sites/geohub/src/components/util/stac/StacApiExplorer.svelte
Labels: refactor

#3062 refactor: moved FieldControl component to svelte-undp-component
  .changeset/nervous-bears-add.md
  .changeset/purple-starfishes-itch.md
  packages/svelte-undp-components/src/lib/components/FieldControl.stories.ts
  packages/svelte-undp-components/src/lib/components/FieldControl.svelte
  packages/svelte-undp-components/src/lib/components/FieldControl.test.ts
  packages/svelte-undp-components/src/lib/components/index.ts
  sites/geohub/src/components/maplibre/fill-extrusion/FillExtrusionHeight.svelte
  sites/geohub/src/components/maplibre/fill-extrusion/VectorFillExtrusion.svelte
  sites/geohub/src/components/maplibre/raster/RasterAlgorithms.svelte
  sites/geohub/src/components/maplibre/raster/RasterClassifyLegend.svelte
  sites/geohub/src/components/maplibre/raster/RasterLegendEdit.svelte
  sites/geohub/src/components/maplibre/vector/VectorColorClassification.svelte
  sites/geohub/src/components/maplibre/vector/VectorValueClassification.svelte
  sites/geohub/src/components/pages/data/datasets/DatasetMapView.svelte
  sites/geohub/src/components/pages/data/datasets/UserPermission.svelte
  sites/geohub/src/components/pages/map/layers/LayerInfo.svelte
  sites/geohub/src/routes/(app)/settings/+page.svelte
Labels: refactor

#3064 refactor: moved Accordion component to svelte-undp-component
  .changeset/twenty-knives-cross.md
  .changeset/violet-bikes-tease.md
  packages/svelte-undp-components/src/lib/components/Accordion.stories.ts
  packages/svelte-undp-components/src/lib/components/Accordion.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  packages/svelte-undp-components/src/lib/util/clean.test.ts
  packages/svelte-undp-components/src/lib/util/clean.ts
  packages/svelte-undp-components/src/lib/util/index.ts
  sites/geohub/src/components/maplibre/circle/VectorCircle.svelte
  sites/geohub/src/components/maplibre/fill-extrusion/VectorFillExtrusion.svelte
  sites/geohub/src/components/maplibre/fill/VectorPolygon.svelte
  sites/geohub/src/components/maplibre/heatmap/VectorHeatmap.svelte
  sites/geohub/src/components/maplibre/hillshade/Hillshade.svelte
  sites/geohub/src/components/maplibre/line/VectorLine.svelte
  sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
  sites/geohub/src/components/maplibre/raster/RasterLegendEdit.svelte
  sites/geohub/src/components/maplibre/symbol/VectorSymbol.svelte
  sites/geohub/src/components/maplibre/vector/VectorSimulationAccordion.svelte
  sites/geohub/src/components/pages/map/data/DataCard.svelte
  sites/geohub/src/components/pages/map/data/DataVectorCard.svelte
  sites/geohub/src/components/pages/map/layers/LayerInfo.svelte
  sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
  sites/geohub/src/components/pages/map/layers/vector/VectorLabelPanel.svelte
  sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
  sites/geohub/src/components/util/stac/StacCatalogItem.svelte
  sites/geohub/src/components/util/stac/StacCatalogMap.svelte
Labels: refactor

#3066 Refactor/3065 backtotop
  .changeset/little-tigers-brush.md
  .changeset/lovely-pugs-admire.md
  packages/svelte-undp-components/package.json
  packages/svelte-undp-components/src/lib/components/BackToTop.stories.ts
  packages/svelte-undp-components/src/lib/components/BackToTop.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  pnpm-lock.yaml
  sites/geohub/src/routes/(app)/+layout@.svelte
Labels: refactor

#3068 refactor: moved HeroLink component to svelte-undp-component
  .changeset/cool-tomatoes-suffer.md
  .changeset/spotty-kings-decide.md
  packages/svelte-undp-components/src/lib/components/HeroLink.stories.ts
  packages/svelte-undp-components/src/lib/components/HeroLink.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  sites/geohub/src/routes/(app)/+page.svelte
  sites/geohub/src/routes/(app)/data/+page.svelte
Labels: refactor

#3070 refactor: migrated FloatingPanel to svelte-undp-component
  .changeset/four-bottles-burn.md
  .changeset/shaggy-falcons-drop.md
  packages/svelte-undp-components/src/lib/components/FloatingPanel.stories.ts
  packages/svelte-undp-components/src/lib/components/FloatingPanel.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  sites/geohub/src/components/pages/map/layers/LayerEdit.svelte
  sites/geohub/src/components/pages/map/plugins/MaplibreLegendControl.svelte
Labels: refactor

#3072 refactor: migrated PanelButton to svelte-undp-component
  .changeset/blue-lobsters-cry.md
  .changeset/lazy-vans-type.md
  packages/svelte-undp-components/src/lib/components/PanelButton.stories.ts
  packages/svelte-undp-components/src/lib/components/PanelButton.svelte
  packages/svelte-undp-components/src/lib/components/PanelButton.test.ts
  packages/svelte-undp-components/src/lib/components/index.ts
  sites/geohub/src/components/pages/data/datasets/PublishedDatasets.svelte
  sites/geohub/src/components/pages/map/data/TextFilter.svelte
Labels: refactor

#3075 Refactor/modal
  .changeset/angry-pigs-study.md
  .changeset/bright-dancers-joke.md
  .changeset/kind-readers-design.md
  .changeset/mighty-stingrays-melt.md
  packages/svelte-undp-components/src/lib/components/ModalNotification.stories.ts
  packages/svelte-undp-components/src/lib/components/ModalNotification.svelte
  packages/svelte-undp-components/src/lib/components/ModalTemplate.stories.ts
  packages/svelte-undp-components/src/lib/components/ModalTemplate.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  sites/geohub/src/components/pages/data/datasets/DefaultStyleEditor.svelte
  sites/geohub/src/components/pages/data/datasets/PublishedDatasetDeleteDialog.svelte
  sites/geohub/src/components/pages/data/datasets/UserPermission.svelte
  sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
  sites/geohub/src/components/pages/map/layers/LayerList.svelte
  sites/geohub/src/components/pages/map/layers/header/DeleteMenu.svelte
  sites/geohub/src/components/pages/map/plugins/StyleShare.svelte
  sites/geohub/src/components/util/Modal.test.ts
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/+page.svelte
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
  sites/geohub/src/routes/(map)/maps/+layout.svelte
Labels: refactor

#3078 refactor: tabs
  .changeset/dry-horses-sit.md
  .changeset/yellow-rings-sniff.md
  packages/svelte-undp-components/src/lib/components/Tabs.stories.ts
  packages/svelte-undp-components/src/lib/components/Tabs.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  sites/geohub/src/components/maplibre/symbol/IconImagePicker.svelte
  sites/geohub/src/components/pages/map/Content.svelte
  sites/geohub/src/components/pages/map/layers/raster/RasterLayer.svelte
  sites/geohub/src/components/pages/map/layers/vector/VectorLayer.svelte
  sites/geohub/src/components/util/ColorMapPicker.svelte
  sites/geohub/src/routes/(app)/data/+page.svelte
  sites/geohub/src/routes/(app)/data/[id]/+page.svelte
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
  sites/geohub/src/routes/(app)/settings/+page.svelte
Labels: refactor

#3081 refactor: Use 'clean' and 'handleEnterKey' methods from svelte-undp-components
  .changeset/quiet-flowers-clap.md
  sites/geohub/src/components/header/UserAccount.svelte
  sites/geohub/src/components/maplibre/LegendColorMapRow.svelte
  sites/geohub/src/components/maplibre/LegendTypeSwitcher.svelte
  sites/geohub/src/components/maplibre/raster/RasterAlgorithmParameter.svelte
  sites/geohub/src/components/maplibre/symbol/IconImage.svelte
  sites/geohub/src/components/maplibre/symbol/IconImagePickerCard.svelte
  sites/geohub/src/components/maplibre/symbol/PropertySelect.svelte
  sites/geohub/src/components/maplibre/symbol/SymbolPlacement.svelte
  sites/geohub/src/components/maplibre/vector/VectorSimpleColorLegend.svelte
  sites/geohub/src/components/maplibre/vector/VectorSimulationArgument.svelte
  sites/geohub/src/components/pages/data/datasets/DatasetMapView.svelte
  sites/geohub/src/components/pages/data/datasets/PublishedDataset.svelte
  sites/geohub/src/components/pages/data/datasets/TagFilter.svelte
  sites/geohub/src/components/pages/data/ingesting/IngestingDatasetHeader.svelte
  sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRow.svelte
  sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRowDetail.svelte
  sites/geohub/src/components/pages/home/ExploreDatasets.svelte
  sites/geohub/src/components/pages/map/data/DataCategoryCard.svelte
  sites/geohub/src/components/pages/map/data/DataView.svelte
  sites/geohub/src/components/pages/map/data/RasterAlgorithmExplorerButton.svelte
  sites/geohub/src/components/pages/map/data/StacExplorerButton.svelte
  sites/geohub/src/components/pages/map/layers/LayerTemplate.svelte
  sites/geohub/src/components/pages/map/layers/header/DeleteMenu.svelte
  sites/geohub/src/components/pages/map/layers/order/LayerOrderPanelButton.svelte
  sites/geohub/src/components/pages/map/layers/raster/RasterTransform.svelte
  sites/geohub/src/components/pages/map/layers/raster/RasterTransformAdvanced.svelte
  sites/geohub/src/components/pages/map/layers/raster/RasterTransformSimple.svelte
  sites/geohub/src/components/pages/map/layers/vector/OperationButtons.svelte
  sites/geohub/src/components/pages/map/layers/vector/PropertySelectButtons.svelte
  sites/geohub/src/components/pages/map/layers/vector/Tags.svelte
  sites/geohub/src/components/pages/map/layers/vector/VectorFilter.svelte
  sites/geohub/src/components/pages/map/plugins/MapQueryInfoControl.svelte
  sites/geohub/src/components/util/CountryCard.svelte
  sites/geohub/src/components/util/CountryPicker.svelte
  sites/geohub/src/components/util/DataProviderPicker.svelte
  sites/geohub/src/components/util/SdgCard.svelte
  sites/geohub/src/components/util/Star.svelte
  sites/geohub/src/components/util/TagInput.svelte
  sites/geohub/src/components/util/stac/StacCatalogExplorer.svelte
  sites/geohub/src/components/util/stac/StacCatalogItem.svelte
  sites/geohub/src/lib/helper/clean.test.ts
  sites/geohub/src/lib/helper/clean.ts
  sites/geohub/src/lib/helper/handleEnterKey.ts
  sites/geohub/src/lib/helper/index.ts
  sites/geohub/src/lib/server/helpers/getRasterMetadata.ts
  sites/geohub/src/lib/server/helpers/getVectorMetadata.ts
  sites/geohub/src/routes/(app)/+page.svelte
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.server.ts
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte
  sites/geohub/src/routes/(app)/management/pgtileserv/+page.svelte
  sites/geohub/src/routes/(app)/settings/+page.svelte
Labels: refactor

#3082 feat: created HeroHeader component
  .changeset/shiny-toes-tap.md
  .changeset/yellow-trainers-sparkle.md
  packages/svelte-undp-components/src/lib/components/HeroHeader.stories.ts
  packages/svelte-undp-components/src/lib/components/HeroHeader.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  sites/geohub/src/routes/(app)/api/+page.svelte
  sites/geohub/src/routes/(app)/dashboards/+page.svelte
  sites/geohub/src/routes/(app)/data/+page.svelte
  sites/geohub/src/routes/(app)/data/[id]/+page.svelte
  sites/geohub/src/routes/(app)/data/[id]/style/edit/+page.svelte
  sites/geohub/src/routes/(app)/data/supported-formats/+page.svelte
  sites/geohub/src/routes/(app)/data/upload/+page.svelte
  sites/geohub/src/routes/(app)/management/+page.svelte
  sites/geohub/src/routes/(app)/management/pgtileserv/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/api/[id]/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/api/[id]/[collection]/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte
  sites/geohub/src/routes/(app)/maps/+page.svelte
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
  sites/geohub/src/routes/(app)/settings/+page.svelte
  sites/geohub/src/routes/(app)/tools/+page.svelte
Labels: refactor

#3084 fix: moved star & delete button to info tab, and moved open button to…
  .changeset/empty-needles-beam.md
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
Labels: bug

#3089 Fix/3086 add accesslevel to data page
  .changeset/plenty-worms-tell.md
  .changeset/tame-islands-explode.md
  packages/svelte-undp-components/src/lib/components/FieldControl.stories.ts
  packages/svelte-undp-components/src/lib/components/FieldControl.svelte
  sites/geohub/src/components/pages/data/datasets/PublishedDataset.svelte
  sites/geohub/src/routes/(app)/data/[id]/+page.svelte
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
Labels: bug

#3092 feat: add an edit button at map page to allow users to update map tit…
  .changeset/odd-keys-whisper.md
  sites/geohub/src/components/pages/map/plugins/StyleShare.svelte
  sites/geohub/src/routes/(app)/maps/[id]/+page.svelte
Labels: enhancement

#3093 fix: show signed user list by typed string for user permission feature
  .changeset/sixty-cheetahs-rule.md
  sites/geohub/src/components/pages/data/datasets/UserPermission.svelte
  sites/geohub/src/lib/server/helpers/index.ts
  sites/geohub/src/lib/server/helpers/searchUsersByEmail.ts
  sites/geohub/src/routes/api/users/+server.ts
  sites/geohub/static/api/swagger/spec.yaml
Labels: enhancement

#3094 fix: new map url in button
  .changeset/ninety-tigers-attack.md
  sites/geohub/src/routes/(app)/maps/+page.svelte
Labels: bug

#3099 fix: remove & and | char
  .changeset/fluffy-gorillas-divide.md
  .changeset/olive-camels-beam.md
  packages/svelte-undp-design/src/lib/SearchExpand/SearchExpand.stories.ts
  packages/svelte-undp-design/src/lib/SearchExpand/SearchExpand.svelte
  sites/geohub/src/lib/server/helpers/createDatasetSearchWhereExpression.ts
  sites/geohub/src/routes/(app)/data/+page.server.ts
Labels: bug

#3102 fix: show accessibility icon on card at maps and data page
  .changeset/brave-steaks-breathe.md
  .changeset/metal-drinks-float.md
  packages/svelte-undp-design/src/lib/Card/Card.stories.ts
  packages/svelte-undp-design/src/lib/Card/Card.svelte
  packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.stories.ts
  packages/svelte-undp-design/src/lib/CardWithImage/CardWithImage.svelte
  sites/geohub/src/components/pages/data/datasets/CardView.svelte
  sites/geohub/src/components/pages/home/MapStyleCardList.svelte
Labels: bug

#3105 feat: added map list view
  .changeset/quick-pandas-wave.md
  sites/geohub/src/components/pages/data/datasets/PublishedDatasetRow.svelte
  sites/geohub/src/components/pages/home/MapStyleCardList.svelte
  sites/geohub/src/lib/config/DefaultUserConfig/MapPageTableViewType.ts
  sites/geohub/src/lib/config/DefaultUserConfig/index.ts
  sites/geohub/src/routes/(app)/maps/+page.server.ts
  sites/geohub/src/routes/(app)/maps/+page.ts
  sites/geohub/src/routes/(app)/settings/+page.svelte
Labels: enhancement

#3109 fix: changed cogserver-dev-deployment.yaml folder path
  .github/workflows/ci.yml
Labels: bug

#3114 fix: show title and description at Tools page, and show slider if minimum and maximum value are available in algorithm
  .changeset/hip-bananas-love.md
  sites/geohub/src/components/maplibre/raster/RasterAlgorithmParameter.svelte
  sites/geohub/src/lib/types/RasterAlgorithm.ts
  sites/geohub/src/routes/(app)/tools/+page.svelte
Labels: bug

#3115 fix: added robots.txt
  .changeset/four-foxes-melt.md
  sites/geohub/static/robots.txt
Labels: bug, backend

#3123 fix: fixed bug of inaccessible to data page when users do not sign in
  .changeset/swift-lamps-watch.md
  sites/geohub/src/routes/(app)/data/+page.svelte
Labels: bug

#3125 fix: close ModalTemplate by espace key if close button is shown in dialog.
  .changeset/tender-flies-shake.md
  packages/svelte-undp-components/src/lib/components/ModalTemplate.svelte
  pnpm-lock.yaml
  sites/geohub/package.json
  sites/geohub/src/components/pages/map/layers/header/DeleteMenu.svelte
Labels: refactor

#3128 fix: fixed bug of not showing attribution correctly for vector datasets, also now forcely update attribution for saved map in /style/{id} endpoint.
  .changeset/strange-crabs-dream.md
  sites/geohub/src/components/util/MiniMap.svelte
  sites/geohub/src/lib/helper/createAttributionFromTags.ts
  sites/geohub/src/lib/server/defaultStyle/VectorDefaultStyle.ts
  sites/geohub/src/lib/server/helpers/getStyleById.ts
  sites/geohub/src/routes/api/datasets/[id]/style/[layer]/[type]/+server.ts
Labels: bug

#3133 fix: show algorithm's title and description at accordion title and help at layer editor
  .changeset/neat-planes-repeat.md
  sites/geohub/src/components/maplibre/raster/RasterLegend.svelte
Labels: bug

#3142 fix: the link to map page from STAC management page was fixed
  .changeset/beige-zebras-scream.md
  sites/geohub/src/routes/(app)/management/stac/api/[id]/[collection]/+page.svelte
  sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.svelte
Labels: bug

#3143 ci: deploy docker image
  .github/workflows/ci.yml
  docker/Dockerfile.production
Labels: docker

#3144 fix: check whether it is original repo for CI jobs which deploy to ACR
  .github/workflows/ci.yml
Labels: docker

#3145 fix: add develop-ibm
  .github/workflows/ci.yml
Labels: docker

#3146 fix: push docker iamge for main branch
  .github/workflows/ci.yml
Labels: docker

#3152 refactor: moved property editor component to svelte-undp-components
  .changeset/afraid-colts-think.md
  .changeset/brown-geckos-admire.md
  packages/svelte-undp-components/package.json
  packages/svelte-undp-components/src/lib/components/PropertyEditor.stories.ts
  packages/svelte-undp-components/src/lib/components/PropertyEditor.svelte
  packages/svelte-undp-components/src/lib/components/index.ts
  pnpm-lock.yaml
  sites/geohub/src/components/maplibre/raster/RasterAlgorithmParameter.svelte
  sites/geohub/src/components/maplibre/raster/RasterAlgorithms.svelte
  sites/geohub/src/components/maplibre/vector/VectorParamsPanel.svelte
  sites/geohub/src/components/maplibre/vector/VectorSimulationArgument.svelte
  sites/geohub/src/components/pages/map/data/DataView.svelte
  sites/geohub/src/routes/(map)/maps/+layout.server.ts
Labels: bug, refactor

#3155 fix: release docker image with geohub tag version like geohub@X.X.X
  .github/workflows/ci.yml
Labels: docker

#3156 fix: set href as null instead of empty string if tab id is not starting with hash
  .changeset/healthy-cherries-enjoy.md
  packages/svelte-undp-components/src/lib/components/ColorMapPicker.svelte
  packages/svelte-undp-components/src/lib/components/Tabs.svelte
Labels: bug

#3157 fix: fixed version expression for trigger
  .github/workflows/ci.yml
Labels: docker

#3158 feat: show GeoHub version and package licenses used
  .changeset/big-fans-carry.md
  pnpm-lock.yaml
  sites/geohub/.gitignore
  sites/geohub/package.json
  sites/geohub/src/components/header/UserAccount.svelte
  sites/geohub/src/lib/config/AppConfig/FooterItems.ts
  sites/geohub/src/routes/(app)/license/+page.server.ts
  sites/geohub/src/routes/(app)/license/+page.svelte
  sites/geohub/src/routes/(app)/license/+page.ts
  sites/geohub/svelte.config.js
Labels: enhancement

#3161 Fix/user dropmenu layout
  .changeset/young-dots-chew.md
  .github/workflows/ci.yml
  sites/geohub/src/components/header/UserAccount.svelte
  sites/geohub/src/routes/(app)/+page.svelte
Labels: bug

#3167 doc: add mermaid plugin to mkdocs
  documentation/Pipfile
  documentation/Pipfile.lock
  documentation/docs/slides/tutorial.md
  documentation/mkdocs.yml
  documentation/theme_overrides/reveal.html
Labels: documentation

#3168 doc: added data upload section
  documentation/docs/assets/data/datastore_1.png
  documentation/docs/assets/data/dataupload_1.png
  documentation/docs/assets/data/dataupload_2.png
  documentation/docs/assets/data/dataupload_3.png
  documentation/docs/assets/data/dataupload_4.png
  documentation/docs/assets/data/dataupload_5.png
  documentation/docs/data/best_practices.md
  documentation/docs/data/data_formats.md
  documentation/docs/data/data_store.md
  documentation/docs/data/data_upload.md
  documentation/docs/data/open_data_license.md
  documentation/docs/data/publish_datasets.md
  documentation/docs/old_version/data_upload/upload.md
  documentation/mkdocs.yml
Labels: documentation

#3174 ci: check whether ACR_USERNAME and ACR_PASSWORD exists in CI
  .github/workflows/ci.yml
Labels: backend, docker

#3175 fix: removed hardcoded links from header and footer
  .changeset/stupid-tigers-repair.md
  docker/Dockerfile
  docker/Dockerfile.production
  docker/docker-compose.yml
  sites/geohub/.env.docker.example
  sites/geohub/.env.example
  sites/geohub/src/components/header/Header.svelte
  sites/geohub/src/lib/config/AppConfig/index.ts
  sites/geohub/src/lib/server/config/FooterItems.ts
  sites/geohub/src/lib/server/config/HeaderItems.ts
  sites/geohub/src/routes/(app)/+layout@.svelte
  sites/geohub/src/routes/(app)/+page.svelte
  sites/geohub/src/routes/+error.svelte
  sites/geohub/src/routes/+layout.server.ts
Labels: bug

#3177 fix: comment site_url because links do not work in docs-dev
  documentation/mkdocs.yml
Labels: bug, documentation

#3178 fix: fixed reveal.js path to absolute path
  documentation/mkdocs.yml
Labels: bug, documentation

#3185 fix: fixed bug not showing management link in footer correctly
  .changeset/tough-tips-burn.md
  sites/geohub/src/lib/server/config/FooterItems.ts
  sites/geohub/src/lib/server/config/HeaderItems.ts
  sites/geohub/src/routes/+layout.server.ts
Labels: bug

#3187 ci: removed deploy to develop job since AppService was migrated to Docker version intead of Node js server
  .github/workflows/ci.yml
Labels: backend

#3189 fix: remove add to map button in ingested dataset preview
  .changeset/cool-bats-impress.md
  sites/geohub/src/components/pages/data/ingesting/IngestingDatasetRowDetail.svelte
Labels: bug

#3179 doc: add documentation for publish
  documentation/docs/analytics/index.md
  documentation/docs/assets/data/publish_1.png
  documentation/docs/assets/data/publish_10.png
  documentation/docs/assets/data/publish_11.png
  documentation/docs/assets/data/publish_12.png
  documentation/docs/assets/data/publish_13.png
  documentation/docs/assets/data/publish_2.png
  documentation/docs/assets/data/publish_3.png
  documentation/docs/assets/data/publish_4.png
  documentation/docs/assets/data/publish_5.png
  documentation/docs/assets/data/publish_6.png
  documentation/docs/assets/data/publish_7.png
  documentation/docs/assets/data/publish_8.png
  documentation/docs/assets/data/publish_9.png
  documentation/docs/data/index.md
  documentation/docs/data/publish_datasets.md
  documentation/docs/visualization/index.md
  documentation/mkdocs.yml
Labels: documentation

#3194 fix: downgraded a patch version for auth.js to solve this error of ERR_INVALID_URL
  .changeset/fast-windows-try.md
  pnpm-lock.yaml
  sites/geohub/package.json
Labels: bug

#3193 fix: show colormap legend in fullwidth for color card in colormap picker
  .changeset/chilled-buckets-breathe.md
  packages/svelte-undp-components/src/lib/components/ColorMapPicker.svelte
  packages/svelte-undp-components/src/lib/components/ColorMapPickerCard.svelte
  packages/svelte-undp-components/src/lib/components/ColorMapPickerCard.test.ts
Labels: bug

#3196 refactor: use await locals.auth() instead of deprecated getSession().
  .changeset/smooth-houses-try.md
  sites/geohub/src/hooks.server.ts
  sites/geohub/src/routes/(app)/data/+page.server.ts
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.server.ts
  sites/geohub/src/routes/(app)/data/[id]/style/edit/+page.server.ts
  sites/geohub/src/routes/(app)/data/upload/+page.server.ts
  sites/geohub/src/routes/(app)/management/stac/+page.server.ts
  sites/geohub/src/routes/(app)/management/stac/api/[id]/+page.server.ts
  sites/geohub/src/routes/(app)/management/stac/catalog/[id]/+page.server.ts
  sites/geohub/src/routes/(app)/maps/+page.server.ts
  sites/geohub/src/routes/(app)/settings/+page.server.ts
  sites/geohub/src/routes/+layout.server.ts
  sites/geohub/src/routes/api/datasets/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/permission/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/preview/style.json/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/star/+server.ts
  sites/geohub/src/routes/api/datasets/[id]/style/[layer]/[type]/+server.ts
  sites/geohub/src/routes/api/datasets/ingesting/+server.ts
  sites/geohub/src/routes/api/menu/+server.ts
  sites/geohub/src/routes/api/settings/+server.ts
  sites/geohub/src/routes/api/stac/+server.ts
  sites/geohub/src/routes/api/stac/[id]/+server.ts
  sites/geohub/src/routes/api/style/+server.ts
  sites/geohub/src/routes/api/style/[id].json/+server.ts
  sites/geohub/src/routes/api/style/[id]/+server.ts
  sites/geohub/src/routes/api/style/[id]/permission/+server.ts
  sites/geohub/src/routes/api/style/[id]/star/+server.ts
  sites/geohub/src/routes/api/style/[id]/static/[bbox]/[width]x[height].[format]/+server.ts
  sites/geohub/src/routes/api/style/[id]/static/[lon],[lat],[zoom],[bearing],[pitch]/[width]x[height].[format]/+server.ts
  sites/geohub/src/routes/api/style/[id]/static/auto/[width]x[height].[format]/+server.ts
  sites/geohub/src/routes/api/tags/+server.ts
  sites/geohub/src/routes/api/token/+server.ts
  sites/geohub/src/routes/api/users/+server.ts
Labels: refactor

#3197 doc: changed some structure and added some links of UNDP
  documentation/docs/data/data_upload.md
  documentation/docs/data/index.md
  documentation/docs/data/publish_datasets.md
  documentation/docs/data/search_datasets.md
  documentation/docs/visualization/search_datasets.md
  documentation/mkdocs.yml
Labels: documentation

#3198 doc: added docs for searching datasets
  documentation/docs/assets/data/search_map_1.png
  documentation/docs/assets/data/search_map_2.png
  documentation/docs/assets/data/search_table_1.png
  documentation/docs/assets/data/search_table_2.png
  documentation/docs/assets/data/search_table_3.png
  documentation/docs/assets/data/search_table_4.png
  documentation/docs/data/search_datasets.md
  documentation/docs/data/search_datasets_on_map.md
  documentation/docs/data/search_datasets_table.md
  documentation/docs/old_version/data/data_structure.md
  documentation/docs/old_version/data/dynamic_vector.md
  documentation/docs/old_version/data/microsoft.md
  documentation/docs/old_version/data/sdg_bucket.md
  documentation/docs/old_version/data/special_buckets.md
  documentation/mkdocs.yml
Labels: documentation

#3199 fix: moved some dependencies to devDependencies and switched prod docker image to distroless image
  .changeset/real-snakes-hammer.md
  docker/Dockerfile.production
  pnpm-lock.yaml
  sites/geohub/package.json
Labels: backend, docker

#3203 doc: merged dashboard doc
  documentation/docs/assets/dashboards/electricity_function1.png
  documentation/docs/assets/dashboards/electricity_function2.png
  documentation/docs/assets/dashboards/electricity_function3.png
  documentation/docs/dashboards/electricity.md
  documentation/docs/dashboards/index.md
  documentation/docs/old_version/dashboards/dashboard.md
  documentation/docs/old_version/dashboards/functions.md
  documentation/mkdocs.yml
Labels: documentation

#3204 doc: added geo-undpstac-pipeline link on readme
  README.md
Labels: documentation

#3207 Feat/add maptiler geocoder
  .changeset/breezy-pugs-grab.md
  docker/Dockerfile
  docker/Dockerfile.production
  pnpm-lock.yaml
  sites/geohub/.env.docker.example
  sites/geohub/.env.example
  sites/geohub/package.json
  sites/geohub/src/components/pages/map/Map.svelte
  sites/geohub/src/routes/(map)/maps/+layout.server.ts
  sites/geohub/vite.config.ts
Labels: enhancement

#3213 feat: show year and resolution, admin level tag in info tab if they are applicable
  .changeset/forty-bats-sit.md
  sites/geohub/src/components/pages/data/datasets/PublishedDataset.svelte
Labels: enhancement

#3214 fix: make important tags visible
  .changeset/old-pets-sing.md
  sites/geohub/src/components/util/TagInput.svelte
  sites/geohub/src/lib/config/AppConfig/TagInputValues.ts
  sites/geohub/src/routes/(app)/data/[[id]]/edit/+page.svelte
Labels: bug

#3215 fix: updated screenshot for tags
  documentation/docs/assets/data/publish_11.png
  documentation/docs/assets/data/publish_5.png
  documentation/docs/data/publish_datasets.md
  documentation/mkdocs.yml
Labels: documentation
